### ISSUE TITLE
basis_1d.description

### ISSUE THREAD

**Issue by briantimar** [weinbe58/QuSpin#107]
Hi,
Very minor bug -- the following produces an AttributeError: (using latest quspin version, python 3.5)

```python
from quspin.basis import spin_basis_1d
b=spin_basis_1d(4)
print(b.description)
```
--- I think the basis_1d.conserved attribute should be basis_1d._conserved.
Cheers
Brian

**Comment by mgbukov** [comment]
Thanks, Brian! We'll fix this in the next release.

Please keep reporting all bugs you encounter -- I'm sure there are more of them lurking out there :)

best,
Marin

**Comment by weinbe58** [comment]
pull request merged!
