### ISSUE TITLE
Expectation value is different wether I use symmetries or not when creating the basis

### ISSUE THREAD

**Issue by FredericSauv** [weinbe58/QuSpin#117]
Hi, when computing the expected value of an operator (here the occupation number of one site in a 1D Bose Hubbard Model) I get different values whether I use symmetries or not when creating the basis. Operator and states used should be same (except that they are represented in a different basis) and I would expect to get the same result. Am I missing something?

best,

from quspin.operators import hamiltonian # Hamiltonians and operators
from quspin.basis import boson_basis_1d # Hilbert space boson basis
import numpy as np # generic math functions

### generate an Hamiltontian without interaction
def gen_H_no_inter(basis, L=5, J=1.0):
    hop=[[-J,i,(i+1)%L] for i in range(L)] #PBC
    static=[['+-',hop],['-+',hop]]
    H=hamiltonian(static,[],basis=basis,dtype=np.float64)
    return H

### generate operator for one site (by defaut 'n0')
def gen_operator_site(basis, op_string = 'n', site = 0):
    no_check_sym = {"check_symm" : False}    
    return hamiltonian([[op_string, [[1.0, site]]]], [], basis = basis, **no_check_sym)

### Basis without symmetry, get the ground state and compute expected value of n0 for this state
basis = boson_basis_1d(5, Nb=5, sps=3)
H = gen_H_no_inter(basis)
EGS, VGS = H.eigsh(time=0.0, k = 1, which = 'SA', maxiter = 1E10)
n0 = gen_operator_site(basis) 
print(n0.expt_value(VGS))

### Basis with symmetry
symH = {'kblock':0, 'pblock':1}
basis_sym = boson_basis_1d(5, Nb=5, sps=3, **symH)
H_sym = gen_H_no_inter(basis_sym)
EGS_sym, VGS_sym = H_sym.eigsh(time=0.0, k = 1, which = 'SA', maxiter = 1E10)
n0_sym = gen_operator_site(basis_sym) 
print(n0_sym.expt_value(VGS_sym))

### Recovering VGS from VGS_sym
P = basis_sym.get_proj(np.complex128, pcon=True)
VGS_recover = P.dot(VGS_sym)  # sometimes with a pi phase
print(np.allclose(VGS, VGS_recover))

### Recovering n0 from n0_sym
n0_recover = n0_sym.project_to(P.transpose())
print(np.allclose(n0.todense(), n0_recover.todense()))

**Comment by weinbe58** [comment]
Hi,

So I think the issue is the simple, if I look at how the occupation n_0 transforms under translations: T n_0 T^\dagger = n_1 != n_0 so this operator does not obey translational symmetry, and so you can't construct this operator in a single momentum sector, it would have to be a linear combination over all the momentum sectors. 

This is OK because we know that the density should be uniform over the entire system if we look into expectation values of eigenstates of our Hamiltonian, which implies that n_0 = n_1 = ... = n_{L-1} so I can construct a translationally invariant operator by taking an average over all the sites: (\sum_i n_i)/L.

To check this you can try turning the symmetry checks back on and you should find that QuSpin will raise an error when you try to construct the operator in the momentum basis.

**Comment by weinbe58** [comment]
Here is an example which shows that they work out. I construct a random state in the kblock=0 sector and when I project it up I see that the expectation value of all the local densities is uniform as one would expect and the value on each site matches the average value constructed in the momentum sector.

**Comment by mgbukov** [comment]
One should maybe mention that precisely these situations were the main reason for us to design the `block` tools.

If a Hamiltonian obeys a given symmetry, but your state does not, then the `block` tools allow you to split the state into the various symmetry sectors, perform what you want, and then put things back together. We have an example explaining how to do this in the second QuSpin paper on the arXiv. 

Also, my experience shows that disabling the checks should be done in the very very end, once u really make sure everything runs properly and makes sense physically. The checks are not costly but may become annoying, which is the main reason we put in the option to turn them off (the other reason being that maybe our algorithm for performing checks on the operator strings is not complete and someone might come up with a counterexample).

**Comment by FredericSauv** [comment]
Understood, thanks for the detailed explanation!
