### ISSUE TITLE
Data type of objects from the Hamiltonian class

### ISSUE THREAD

**Issue by jay-feynman** [weinbe58/QuSpin#128]
Hello developers!

I am using QuSpin to analyze a system of spinful fermions with 12-14 sites. Owing to this the Hamiltonian object is really large. We are encountering a peculiar error, the Hamiltonian is being generated easily by the machine but as soon as we convert it to an ndarray using the toarray() method, the machine gives a memory error. I have attached a screenshot of the error. 

We are converting it to an ndarray to use the sparse matrix methods in scipy, since calculating the eigenvalues using the normal method was taking too long. Can you help us in spotting the error? Also do you prescribe any better methods present in the QuSpin package itself, customized for large sparse matrices? Thanks a lot for your time!
![sad](https://user-images.githubusercontent.com/35796720/40702396-582dc6ac-63ff-11e8-91b0-322a09d07e70.PNG)

**Comment by jay-feynman** [comment]
Oh, what exactly do you mean by the term denationalization? I'm trying to calculate the eigensystem of Hamiltonian constructed using the Fermi-Hubbard model for spinful fermions fully occupying about 12-14 sites. The resulting Hamiltonian is pretty big because of the tensor product involved.

**Comment by weinbe58** [comment]
ooops sorry, auto correct! I mean diagonalization!

**Comment by mgbukov** [comment]
Can you also mention roughly what you want to do with the Hamilton Ian, eg
get only the ground state or get the full spectrum, etc?

Marin

**Comment by jay-feynman** [comment]
So I have a time-dependent periodic Hamiltonian. I want to obtain the ground state of the system and then evolve the state to study the expectation value of the Hamiltonian as a function of time.  What is the method for diagonalization of a sparse matrix? I check the .isdense attribute of the Hamiltonian object and it shows "False" each time.

**Comment by weinbe58** [comment]
For the ground state you can use the `eigsh` method, the arguments are the same as the sparse solver in scipy.sparse.linalg's library (see [here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html)) the extra argument we added is `time=...` to specify the time value to use for the Hamiltonian.

**Comment by mgbukov** [comment]
I just realized the doc for eigsh() only mentions eigenvalues while it can also do eig'vectors. I updated the doc in dev_0.3.0

**Comment by jay-feynman** [comment]
Found the function! It's working perfectly for me now. Thanks a lot for the help!
