### ISSUE TITLE
create new majorana fermion basis class

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#129]
[Majorana fermions](https://en.wikipedia.org/wiki/Majorana_fermion) are their own antiparticles.

This is not urgent, but it's nice to have it on the to-do list.

**Comment by BaronWolfenstein** [comment]
I can take this one.

**Comment by weinbe58** [comment]
@mgbukov and @BaronWolfenstein I was thinking about this problem today, would it not be possible to take any interacting Hamiltonian for of Majorana Fermions and just express it in terms of spinless Dirac Fermions? 

There is an issue with having an odd number of sites, but for even number of sites you just split the lattice into two sub-lattices and create a spinless Dirac Fermion by combining two Majorana sites and of course using QuSpin for that model.
