### ISSUE TITLE
Adding a constant to the Hamiltonian

### ISSUE THREAD

**Issue by thatlittleboy** [weinbe58/QuSpin#131]
Is there an in-built way to add a constant to the Hamiltonian? In a way that just shifts the eigenvalue spectrum by a fixed amount? 
I'm calculating the partition function Z = \sum exp(-beta E) and so the value of Z gets extremely large for negative energies E.

Thank you.

**Comment by weinbe58** [comment]
If you're just getting the partition function from the eigenvalues you can simply shift the eigenvalues:

`E -= E[0]` or `E -= E.min()`

**Comment by thatlittleboy** [comment]
I missed the "I" basis string in the documentation. I'm using 

```
cst = [[E0, i] if i==0 else [0,i] for i in range(L)]
static = [["zz", J_zz], ["I", cst]]
dynamic = []
H = hamiltonian(static, dynamic, basis=basis, dtype=np.float64)
```

to shift the spectrum by an amount E0 for now. Sorry for the noise.
