### ISSUE TITLE
Fermi-Hubbard model in 2d

### ISSUE THREAD

**Issue by srujans** [weinbe58/QuSpin#132]
Hello Developers,
I am currently working on theoretical part of 2-dimensional Fermi-Hubbard model and want to implement it numerically to study it in details for more results. For this purpose, I studied the 2-dimensional "Transverse-Field Ising Model" example provided in official documentation of QuSpin and tried to implement 2D Fermi-Hubbard model with "quspin.basis.spin_basis_general". But the issue is that the "pipe-symbol" is not working which is primarily used for separation of up-spins and down-spins. And so I am unable to build the static part of the Hamiltonian.
I attached the image of error below. I really appreciate any form of help in this issue.

![capture](https://user-images.githubusercontent.com/12464481/41839299-840f041c-7880-11e8-8696-eebca8aff284.PNG)

Thank you very much.

**Comment by weinbe58** [comment]
Yes the general spinful fermions have a slightly different syntax when I first wrote the code which is why I kept it out of the current release. I just added a fix which allows you to toggle between using the pipes and not using the pipes, which will be release formally very soon.

**Comment by srujans** [comment]
Thanks a lot, Phillip!
