### ISSUE TITLE
How to create spinful fermion basis with fixed total particle numbers?

### ISSUE THREAD

**Issue by qweasd3721** [weinbe58/QuSpin#134]
Hi developers,

I can construct spinful fermion basis by 

spinful_fermion_basis_1d(L=L,Nf=(Nup,Ndown)),

in which the number of spin-up and spin-down particles are fixed independently.
Now I want to study spin-flip processes, where total particle number(spin-up + spin-down) is fixed and 
spinful_fermion_basis_1d(L=L,Nf=(Nup-1,Ndown+1))  should also be defined. 

I tried spinful_fermion_basis_1d(L=L,Nf=Ntotal) but get 
"ValueError: Nf must be tuple of integers or iterable object of tuples."

How should I tackle this problem?

**Comment by weinbe58** [comment]
the argument `Nf=...` can also be an iterator so if you want to include all spin sectors with a fixed number of fermions just create a list of the different sectors you want to study, so for your example I think you would want something like:

```
Nf_list = [[(Nf_tot-i,i) for i in range(Nf_tot+1)]
basis = spinful_fermion_basis_1d(L,Nf=Nf_list)
```

**Comment by qweasd3721** [comment]
Hi,

Thanks for your reply!

But when I try
Nflist = [(Nftot-i,i) for i in range(Nftot+1)]
basis= spinful_fermion_basis_1d(L,Nf=Nflist)

I get the error:
[cid:82259694-D15C-4BA6-B965-4DD98CE20302]


Is that because my definition of Nflist is incorrect ?


On Jun 28, 2018, at 3:01 PM, Phillip Weinberg <notifications@github.com<mailto:notifications@github.com>> wrote:


the argument Nf=... can also be an iterator so if you want to include all spin sectors with a fixed number of fermions just create a list of the different sectors you want to study, so for your example I think you would want something like:

Nf_list = [[(Nf_tot-i,i) for i in range(Nf_tot+1)]
basis = spinful_fermion_basis_1d(L,Nf=Nf_list)

**Comment by weinbe58** [comment]
Oh yes, unfortunately there is a bug which is fixed but the code hasn't been released yet, you can get the fixed code by downloading and installing the `fermion_general_fix` branch on github.

We're still in the process of updating the documentation for the new release but hopefully it will be up soon!
