### ISSUE TITLE
change/update definition of +/- operators strings for the spin bases

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#139]
Currently, in the spin bases the definition of the Pauli creator and annihilator matrices goes as

$\sigma^\pm = \sigma^x \pm i \sigma^y$

It would be nice to also allow for the following definition, commonly used in quantum optics and quantum computing:

$\sigma^\pm = 0.5( \sigma^x \pm i \sigma^y )$

**Comment by Vutshi** [comment]
Hi Marin,
I looked into couple of books and thought a bit more. Maybe there is no problem here. Are there actual research papers using the definition $\sigma^\pm = \sigma^x \pm i \sigma^y$ ?
Currently my theory is whoever wrote this definition did it for the sake of definition and by analogy with spin-1/2 operators, but did not actually use it. I can't think of any useful property of such definition.
The second definition $\sigma^\pm = 0.5( \sigma^x \pm i \sigma^y )$ is used in practice a lot.
For example in this book:
- S. Sachdev, Quantum Phase Transitions, Cambridge University Press, New York (1997) [6357 citations]

In the end there could be only one definition of a raising (creation) operator for a two-level system: $sigma^+ = |1><0|$

**Comment by weinbe58** [comment]
If we decide to implement this we will just add an extra flag in the `spin_basis_...` classes. For this convention of Pauli Matrices we will set the flag to -1: so the options would be:

1: pauli matrices as they are now
0: spin-1/2
-1: new Pauli matrices with sigma^+/- having off diagonals of 1

**Comment by mgbukov** [comment]
I added this functionality to dev_0.3.1 branch. Will appear in next official release.

**Comment by mgbukov** [comment]
this is fixed in v. 0.3.1
