### ISSUE TITLE
Hamiltonian symmetries

### ISSUE THREAD

**Issue by CattoG** [weinbe58/QuSpin#143]
I have an hamiltonian with a lot of degenerate eigenvalues. If I get it right, I can restrict my basis to the states with a definite parity and momentum adding pblock and kblock, in order to take away some of them. Is there a way to define others operators in the same way? 
For example, in the Ising model I want to take only the eigenstates psi that obey the relation 
Q psi = (+1) psi 
where the operator Q is the product of the third Pauli matrix on every lattice site. I can define Q:

L=10
basis_o=spin_basis_1d(L,pauli=True)
z_list=[[1,i,i+1,i+2,i+3,i+4,i+5,i+6,i+7,i+8,i+9] for i in range(1)]
op_list=[['zzzzzzzzzz',z_list]]
operator_dict=dict(s_z=op_list)
operator = quantum_operator(operator_dict,basis=basis_o)

Now, I want to use it to get my restricted hamiltonian. I'd expect something like

basis = spin_basis_1d(L,pauli=True, operator=+1)
J_x1=[[J,i,(i+1)%L] for i in range (L)]
J_z=[[I,i] for i in range (L)]
static=[['xx',J_x1],['z', J_z]]
dynamic=[]
H_I=hamiltonian(static,dynamic,basis=basis,dtype=np.float64)

Is it in some way possible?
Thanks

**Comment by mgbukov** [comment]
Hi, there might be a way to define these additional symmetries.

Did you have a look at the [general basis class](http://weinbe58.github.io/QuSpin/generated/quspin.basis.spin_basis_general.html#quspin.basis.spin_basis_general) which supports some user-defined symmetries?

There is also an example (the one on the 2D transverse field Ising model) in Sec. 2.6 of the [QuSpin II paper ](https://arxiv.org/abs/1804.06782) which has the details of the tutorial for the general classes. 

-- marin

**Comment by weinbe58** [comment]
Oh!!! this symmetry is actually just even and odd magnetization sectors, to see this easier we can transform your Hamiltonian to hardcore bosons:

sigma^z -> 2 * n - 1
sigma^x -> a + a^\dagger

which clearly shows that the your operator Q just counts whether there are even or odd numbers of hard core bosons. or in other words  you're sigma^z sigma^z operator conserves boson number mod 2. 

To take advantage of this symmetry you can specify a list of magnetization sectors to include in your basis, using `Nup=range(0,L+1,2)` for even or `Nup=range(1,L+1,2)` for odd.

Phil
