### ISSUE TITLE
Building module quspin.basis.basis_1d._basis_1d_core.hcp_basis failed

### ISSUE THREAD

**Issue by quaneural** [weinbe58/QuSpin#144]
I'm just getting started with QuSpin and am trying to run the first example script. The code won't compile and I'm getting an import error that has to do with the basis module failing somehow. How can I resolve this issue? Here are the two errors:

  File "C:\Users\djpom\Anaconda3\lib\distutils\_msvccompiler.py", line 425, in compile
    raise CompileError(msg)

ImportError: Building module quspin.basis.basis_1d._basis_1d_core.hcp_basis failed: ["distutils.errors.CompileError: command 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2017\\\\Community\\\\VC\\\\Tools\\\\MSVC\\\\14.14.26428\\\\bin\\\\HostX86\\\\x64\\\\cl.exe' failed with exit status 2\n"]

**Comment by weinbe58** [comment]
Is there any reason why you are building the code yourself? There is a pre-compiled version available via anaconda which should work on most windows platforms (at least all the ones I have tested myself). 

I would recommend this method over trying to build it yourself as it requires installing new visual c++ compilers and can be a bit involved. 

to do this, install anaconda and then in the anaconda prompt type `conda install -c weinbe58 quspin`.

**Comment by quaneural** [comment]
I had already installed the quspin package through the anaconda prompt without any issue, but when I try to run the code in Spyder it gave me those error messages.

**Comment by quaneural** [comment]
Okay I reinstalled and it said the package was already there. I just tried running the code again and it seems to be working now. It shows the 11 couplings and then says the Hamiltonian is not Hermitian. Is it supposed to do that?

**Comment by mgbukov** [comment]
which example code are you running?

**Comment by quaneural** [comment]
Code 1

**Comment by mgbukov** [comment]
Then something went wrong with the installation. Example0.py and Example1.py should run without errors.

Since it is not clear what caused the original failure, and how the code started running afterwards, I suggest that you uninstall quspin, and install it again.  To do this u do 

`conda list` # this should show quspin in the list
`conda remove quspin` # uninstall quspin
`conda list` # check that quspin is gone

`conda install -c weinbe58 quspin`

**Comment by quaneural** [comment]
Okay, I think it is running correctly now. Here is the output with no errors:

runfile('C:/Users/djpom/Research/quspinExample0.py', wdir='C:/Users/djpom/Research')
Hermiticity check passed!
Symmetry checks passed!
Particle conservation check passed!

Is this the full output? I was hoping to see how the inner workings a little more so I can learn how to fully utilize quspin for my research project. I am an undergraduate physics student researching how to use machine learning techniques in ED on time independent Hamiltonians and quspin seems like a tremendous tool to help me with this.

**Comment by mgbukov** [comment]
Excellent! Yes, this is the complete output.  

To learn more about how to use quspin, I suggest u do the following:

1) read the two tutorial papers:

[https://arxiv.org/abs/1610.03042](https://arxiv.org/abs/1610.03042)
[https://arxiv.org/abs/1804.06782](https://arxiv.org/abs/1804.06782)

They contain 10 different examples which show a lot of QuSpin's functionality. This is a great starting point. The example codes can be [downloaded here](http://weinbe58.github.io/QuSpin/Examples.html). If you run Examples 1-10 you will have more interesting output :), which is described in the papers above. 

2) you can also read the [online documentation](http://weinbe58.github.io/QuSpin/). In there, all functions and classes come with examples, so you can play with them too. 

Hope this helps ;)
