### ISSUE TITLE
Two-spin correlator with quantum_LinearOperator

### ISSUE THREAD

**Issue by thatlittleboy** [weinbe58/QuSpin#148]
> Quspin 0.3.0, Anaconda 64bit Windows, Python 3.6

### Problem statement

I would like to create a two-spin correlator operator for calculating spin-spin correlations in a 1D Ising chain (simplest possible case) with nearest neighbour interactions only. (I know I can use classical spins +-1, but eventually I need to use this for quantum spins as well in more complicated lattice structure).

Suppose L = 6, the spin chain (periodic bc) looks like

    - 0 - 1 - 2 - 3 - 4 - 5 -

and the following MWE:

```
from quspin.operators import hamiltonian, quantum_LinearOperator
from quspin.basis import spin_basis_1d
import numpy as np

NN_PAIRS = [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 0)]
Jzz = [[1, i, j] for (i, j) in NN_PAIRS]  # NN only, with pbc
static = [["zz", Jzz]]
basis = spin_basis_1d(6, S='1/2', pauli=True)
H = hamiltonian(static, [], basis=basis)
eigvals, eigvecs = H.eigh()

uu_coeff = [[1.0, 0, 4]]  # want <s0 s4>
uu_op = quantum_LinearOperator(static_list=[['zz', uu_coeff]], basis=basis,
                               check_herm=False, check_symm=False)

# Below, for context only
ss_avg, Z = 0., 0.
kT = 0.04309

# shift eigenvalue spectrum to avoid negative E and large Z values; leaves thermal avg unchanged
eigvals -= eigvals.min()

for E_n, n in zip(eigvals, eigvecs):
    ss_avg += np.dot(n.conj(), uu_op.matvec(n)) * np.exp(-E_n / kT)
    Z += np.exp(-E_n / kT)

print(ss_avg/Z)
```

For context:
I'm generating `uu_op` in order to calculate, for example, the (real-space) spin-spin correlation between spin 0 and spin 4, using the thermal average (n and E_n are eigenvecs and eigenvals of H respectively):

![chrome_2018-09-12_16-45-55](https://user-images.githubusercontent.com/30731072/45452216-6b42c180-b6ab-11e8-834f-0aca03e44222.png)

If my physics is right, this shouldn't give 0 at the end (if you run my MWE).

-------------------

So something's clearly wrong, but first **a question related to Quspin's functionality**: 

I was inspecting the `uu_op` (i.e., of the quantum_LinearOperator module) object properties and realized its `static_list` is empty. Am I doing something wrong? I would've expected the static list would contain the list I passed in (`uu_coeff` in MWE above), but it does not (see pic below). Whereas, the Hamiltonian `H` contains the static list just fine.

![pycharm64_2018-09-12_16-56-44](https://user-images.githubusercontent.com/30731072/45452753-d640c800-b6ac-11e8-8f20-87e1f36a8d08.png)

(`uu_op.static_list.__len__ = 0`)

**Comment by thatlittleboy** [comment]
Hi Marin,

Thank you very much for looking into this: the zipping over the wrong axis was not a possibility I had even considered. Indeed `quantum_LinearOperator` seems to work as expected too once the change was made to `zip(eigvals, eigvecs.T)`. But anyway, I think I will switch over to using `hamiltonian` (as suggested) in `uu_op` for now -- I just didn't think it was possible before. Sorry for the noise.

------

A class example for `quantum_LinearOperator` in the documentation would be lovely. :) 
My (non-)issue here is resolved, so feel free to close this once the `static_list` thing is fixed.

**Comment by mgbukov** [comment]
Great! I'd rather keep the issue open so we can fix the issued with the
attribute and the online doc.

We'll close it when we're done.

Marin

**Comment by weinbe58** [comment]
TODO: Add a list, self._static_list_public which is just a copy of the input static list which is exposed to the public API via the property: static_list.

**Comment by mgbukov** [comment]
this is fixed in v. 0.3.1
