### ISSUE TITLE
Partial trace induces MemoryError

### ISSUE THREAD

**Issue by qweasd3721** [weinbe58/QuSpin#149]
Hi, 

I want to use partial_trace function to obtain reduced density matrix for one site in a bosonic 1d chain. 
The chain contains 12 sites and 12 particles. 

Code: 
from quspin.operators import hamiltonian, exp_op # operators
from quspin.basis import boson_basis_1d
import numpy as np 
###### define model parameters ######
Lx = 12 ###whole length of the 1d chain

mu=0 # chemical potential
maxparticlenum = 12
maxsingle = 12
basis=boson_basis_1d(L=Lx,Nb=maxparticlenum,sps=maxsingle,kblock=0,pblock=+1)

####NN hopping
Ja1 = 1
Ja2 = 1
hopiaib=[[-Ja1/2,(i//2)*2,((i//2)*2+1)%Lx] for i in range(Lx)]
hopibipa=[[-Ja2/2,(i//2)*2+1,((i//2)*2+2)%Lx] for i in range(Lx)]
    

Vstat = 0
Ustat = 10
potential=[[-mu-0.5*Ustat,i] for i in range(Lx)]
Uinteraction = [[0.5*Ustat,i,i] for i in range(Lx)]
Vinteraction=[[Vstat,i,(i+1)%Lx] for i in range(Lx)]
static=[
            ["+-",hopiaib],
            ["-+",hopiaib],
            ["+-",hopibipa],
            ["-+",hopibipa],
            ["n",potential],
            ["nn",Uinteraction],
            ["nn",Vinteraction]
        ]
# build hamiltonian
H=hamiltonian(static,[],basis=basis,check_symm=False,check_pcon=False,check_herm=False)
# diagonalise H, only for ground states
E_GS,V_GS=H.eigsh(k=2,which='SA',maxiter=1E10) 
psi1 = V_GS[:,0]
subsys = basis.partial_trace(psi1,[0], subsys_ordering=True, return_rdm='A')
print(subsys)

The I get the following information:
  File "/Users/simon/Desktop/DMBHM/PhysicalQuant.py", line 229, in Prob
    subsys = basis.partial_trace(wavefuncion, sub_sys_A, subsys_ordering=True, return_rdm='A')
  File "/Users/simon/anaconda3/lib/python3.6/site-packages/quspin/basis/base.py", line 258, in partial_trace
    enforce_pure=enforce_pure,sparse=sparse)
  File "/Users/simon/anaconda3/lib/python3.6/site-packages/quspin/basis/lattice.py", line 186, in _partial_trace
    state=self.get_vec(state,sparse=False)
  File "/Users/simon/anaconda3/lib/python3.6/site-packages/quspin/basis/basis_1d/base_1d.py", line 650, in get_vec
    return  _np.squeeze(_get_vec_dense(self._bitops,self._pars,v0,self._basis,norms,ind_neg,ind_pos,shape,C,self._L,**self._blocks_1d))
  File "/Users/simon/anaconda3/lib/python3.6/site-packages/quspin/basis/basis_1d/base_1d.py", line 2136, in _get_vec_dense
    v = _np.zeros(shape,dtype=v0.dtype)
MemoryError

 I am guessing in lattice.py file, get_vec function generate an oversize full basis, then it will cost too much memory to construct density matrix. Any suggestions to solve this problem?

Thanks a lot!

**Comment by weinbe58** [comment]
Try setting ‘sparse=True’ this will use a spare representation for the wave
function and use the sparse svd solver to get the singular values.

**Comment by qweasd3721** [comment]
Hi Phillip,

Thanks for reply!

Do you mean I should use
basis.partial_trace(wavefuncion, sub_sys_A, subsys_ordering=True, return_rdm='A',sparse=True)?
But it still cause memory error.


On Sep 19, 2018, at 9:38 PM, Phillip Weinberg <notifications@github.com<mailto:notifications@github.com>> wrote:

Try setting ‘sparse=True’ this will use a spare representation for the wave
function and use the sparse svd solver to get the singular values.

**Comment by weinbe58** [comment]
Sorry I was on my phone so I could not check the numbers, the method we use to calculate the partial trace requires the wavefunction in the full Hilbert space and in your case the number of states is very large, However with the latest version of SciPy I might be able to fix things to get around this. 

It may take some time unfortunately, sorry about that!

**Comment by weinbe58** [comment]
Unfortunately this will require some work ,effectively I need to write a special function to calculate the following two operators on CSC format matricies:

![image](https://user-images.githubusercontent.com/10360423/45826667-e36c4100-bcc2-11e8-940b-fb390a18de21.png)
(Don't worry the image is just for my records so I know what I have to do later on)
Which is not impossible but a fairly non-trivial task which I can't do right now. Your best bet would be either:

1) change the subsystem size of A such that:
  a) the size of subsystem B can be allocated as a csr_matrix
  b) the size of subsystem A can be converted to a dense matrix.
Once you convert the density matrix to a dense format you can then use partial trace to trace out the rest of the sites. All this depends on how much memory your computer has.

2) reduce the size of the local Hilbert space. This is not ideal, but if you do it systematically you might be able to extrapolate to 12.

**Comment by mgbukov** [comment]
Hi qweasd3721,

Reflecting on Phil's point 2 above: I don't know how important this is for your project, but I noticed your on-site interaction $U$ is fairly large. In this case you are in the atomic limit and most likely you won't need to keep the local on-site Hilbert space dimension so large (u currently allow as many particles per site as there are sites, but these states will hardly gonna be occupied at low energies).

What you could do is go to a smaller system size and check what minimal value of `sps` gives within a reasonable precision the correct answer, then try to extrapolate to larger systems.

**Comment by qweasd3721** [comment]
Hi,

Thanks for the suggestion. I already have considered this point. The previous code is only an example. In my study, systems with small U are also investigated, and some important behaviors disappear by setting a small sps.

On Sep 20, 2018, at 4:59 PM, Marin Bukov <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi qweasd3721,

Reflecting on Phil's point 2 above: I don't know how important this is for your project, but I noticed your on-site interaction $U$ is fairly large. In this case you are in the atomic limit and most likely you won't need to keep the local on-site Hilbert space dimension so large (u currently allow as many particles per site as there are sites, but these states will hardly gonna be occupied at low energies).

What you could do is go to a smaller system size and check what minimal value of sps gives within a reasonable precision the correct answer, then try to extrapolate to larger systems.
