### ISSUE TITLE
Time-dependent hamiltonian with a parameter

### ISSUE THREAD

**Issue by Chapa1** [weinbe58/QuSpin#153]
Hello developers of QuSpin!
I managed to construct the time-dependent Hamiltonian "H(t; G)" with a particular value of its parameter, say "G=0.2", and solve the Schroedinger eq. However, I need to obtain the solution for various values of "G". Is there any example of the code related to my issue?
The Hamiltonian depends on "G" as follows: H(t,G)=H0(t)/G
PS. I found http://weinbe58.github.io/QuSpin/generated/quspin.operators.quantum_operator.html#quspin.operators.quantum_operator.H
However, the example for a time-independent Hamiltonian.

**Comment by mgbukov** [comment]
1) the G-dependence of your Hamiltonian is fairly simple. The `hamiltonian` class supports division so what you can do is 

(i) create the Hamiltonian `H0`, 
(ii) loop over the different values of `G` and in the loop set H = H0/G, and 
(iii) use `H.evolve()`. 

2) alternatively, you can go back to Schroedinger's equation for H0(t)/G as as starting point, and rescale time to absorb the G-dependence in the time-dependence. Then G will be added to the parameters of your drive. Once a time-dependent `hamiltonian` is created, drive parameters can be modified by using `H0.dynamic` which is a dictionary (see documentation of the `hamiltonian` class).

**Comment by Chapa1** [comment]
Thank you very much, mgbukov!  It works!
I also have some questions, which not directly related to QuSpin and very general.  I will be very greatful if you could answer them.
1) Are there any packages  in Fortran similar to QuSpin or QuTip?
2) I found that there is  a numerical framework written in Julia (see qojulia.org).
I am interested in your opinion about this framework. Is it worth studying julia programming language to simulate quantum systems or python is enough.
