### ISSUE TITLE
add support for large integer types in general_basis 

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#157]
New option (coming up soon) in general basis to access the symmetry operation functions from the general_basis constructors without constructing the full basis. This might be useful when using Monte-Carlo methods, or other sampling algorithms.

It would be helpful to add support for large integer types (uint128, uint256, etc.) to enable access to larger systems (currently limited to 64 sites). 

One way might be the [Boost library](https://www.boost.org/doc/libs/1_57_0/libs/multiprecision/doc/html/boost_multiprecision/tut/ints/cpp_int.html), see also

[https://stackoverflow.com/questions/5242819/c-128-256-bit-fixed-size-integer-types](https://stackoverflow.com/questions/5242819/c-128-256-bit-fixed-size-integer-types)

**Comment by weinbe58** [comment]
TODO for this:

1) create wrapper function in C++ which takes the boost integer and turns it into a string which can be printed by the basis function
2) create .pxd file with header files to trick cython into figuring out that the boost integers are actually C-types.
3) figure out a procedure to find anaconda's default directory for headers. Depending on whether boost is being used as it template library form, or if its being used as a dynamically linked library will determine how portable this code is. 

My comments:

One problem with this is that users who install QuSpin manually will make it hard for us as we would in principle like them to be able to reproduce this build. However, if they  are not be using Anaconda, one would need to come up with a mechanism which either can find boost installation directory dynamically or be able to allow the user to specify the directory. This is probably where most of the work will actually be.

**Comment by mgbukov** [comment]
This btw goes hand in hand with #122

**Comment by mgbukov** [comment]
this is fixed in v. 0.3.1
