### ISSUE TITLE
ground energy_square lattice

### ISSUE THREAD

**Issue by Chapa1** [weinbe58/QuSpin#161]
Hello! I would like to calculate the ground state of free spinless fermions on a square lattice 4x4.
Hamiltonian is the same as in [(http://weinbe58.github.io/QuSpin/generated/quspin.basis.spinless_fermion_basis_general.html#quspin.basis.spinless_fermion_basis_general)]
but with mu=0 and U=0.
1) When I write basis_2d=spinless_fermion_basis_general(N_2d, Nf=1, kxblock=(T_x,0),kyblock=(T_y,0),pxblock=(P_x,0),pyblock=(P_y,0))?
I got the warning 
```
 GeneralBasisWarning: using non-commuting symmetries can lead to unwanted behaviour of general basis, make sure that quantum numbers are invariant under non-commuting symmetries!
  exec(compile(f.read(), filename, 'exec'), namespace)
```
2) when I set the number if fermions Nf=2 I got the error:

`ValueError: zero-size array to reduction operation minimum which has no identity`

3) I also tried this one
`basis_2d=spinless_fermion_basis_general(N_2d,Nf=2)`

but the ground energy (E_g) seems to be wrong:
I expect (the hopping J=1) 
E_g =-4 for Nf =1
E_g =-6 for Nf =2
E_g =-8 for Nf =3
E_g =-8 for Nf =4
E_g =-8 for Nf =5 and so on
but 
I got E_g =-10 for Nf =4

PS. Is it possible to delete my previous issue?

**Comment by mgbukov** [comment]
Hi,

can you upload a minimal python script which reproduces these issues. This
will help us investigate them faster.

Note that you have to save your script as a .txt file to upload it.

Marin

**Comment by Chapa1** [comment]
[2D_square_lattice.txt](https://github.com/weinbe58/QuSpin/files/2787847/2D_square_lattice.txt)
There are 3 versions of basis_2d for different values of the fermions Nf:
1st ---computes the ground energy and  gives the warning : GeneralBasisWarning: using non-commuting 
can the result be wrong because of the warning?
2nd and 3rd --- give the result which I do not expect.
Should I insert kxblock=(T_x,0),kyblock=(T_y,0),pxblock=(P_x,0),pyblock=(P_y,0) for simple square lattice with periodic boundary conditions?
Could you plz recommend me the paper/book when I can read about symmetries, symmetry blocks etc. for one/two dimensional lattices

PS. The ground energy for particular values of Nf I obtained via
E=- sum Cos(k_x)+Cos(k_y) where k_x and k_y take values -Pi, -Pi/2, 0 and Pi/2 each for 4x4 lattice

**Comment by mgbukov** [comment]
We were able to reproduce the bug. We'll try to fix it asap. 

1): the warning message tells you that the momentum and parity symmetries do not commute. In general, this is true. However, in the momentum k=0,pi sectors they do commute. The warning is to make the user alert, so they can double check by turning on and off the symmetries.

In principle, if one ignores the warning, the results could be wrong.

"Should I insert kxblock=(T_x,0),kyblock=(T_y,0),pxblock=(P_x,0),pyblock=(P_y,0) for simple square lattice with periodic boundary conditions?"

This depends on your Hamiltonian.

A good review which explains the symmetries is [https://arxiv.org/abs/1101.3281](https://arxiv.org/abs/1101.3281) 
 
We'll let you know once the issue has been fixed.

**Comment by Chapa1** [comment]
I mad a mistake. The correct ground energies (E_g) for the system (free fermions on 4x4 lattice, Nf-number of fermions) are
E_g =-4 for Nf =1
E_g =-6 for Nf =2
E_g =-8 for Nf =3
E_g =-10 for Nf =4
E_g =-12 for Nf =5
E_g =-12 for Nf =6
E_g =-12 for Nf =7
E_g =-12 for Nf =8
and so on
The program with basis_2d=spinless_fermion_basis_general(N_2d,Nf=8) gives the correct energies.

**Comment by mgbukov** [comment]
The issue I found is that for some particle sectors the general basis class w/o any symmetries creates diagonal matrix elements which is wrong. This is why some particle-numbers are OK.

If you want to study a non-interacting fermion system, you won't get far by using ED in the full many-body basis (which is exponentially large so that's an overkill). In such studies, it is common to solve for a single-particle `N_f=1` and then manually fill in the Fermi sea, or whatever many-body free-fermion state you need. Have a look at this [example](http://weinbe58.github.io/QuSpin/examples/example5.html#example5-label) and the supporting tutorial in [Sec 2.2 of our paper](https://arxiv.org/pdf/1804.06782.pdf).

**Comment by mgbukov** [comment]
Seems like I was wrong, too. The `spinless_fermion_general` was fine all along, there is indeed no bug.
