### ISSUE TITLE
One-boson-problem 

### ISSUE THREAD

**Issue by Chapa1** [weinbe58/QuSpin#169]
Hello!
I want to consider two-dimensional Bose-Hubbard model with only one boson.
When I write 
basis=boson_basis_general(N_2d,Nb=1)
I got 
"l=Np//(sps-1)
ZeroDivisionError: integer division or modulo by zero"
How one can create basis with only one boson?
Thanks in advance!

**Comment by Chapa1** [comment]
I think the right basis would be
basis=boson_basis_general(N_2d,Nb=1, sps=2)
for this case.

**Comment by mgbukov** [comment]
The variable `sps` controls the `s`tates `p`er `s`ite, i.e. the local on-site Hilbert space dimension. If you choose `sps=2` you will construct a 2-dim Hilbert space, i.e. a single qubit. To enable more states, as common for a harmonic oscillator (a single boson), use a higher value for `sps`. 

I'll look into the `ZeroDevisionError` you reported above.

**Comment by mgbukov** [comment]
OK, I fixed the error message. In the new release, for `Nb=1` the user will be prompted to use `sps >= 2`.
