### ISSUE TITLE
approximation techniques

### ISSUE THREAD

**Issue by Chapa1** [weinbe58/QuSpin#170]
Hello everyone!
Are there (in QuSpin) any approximation techniques to simulate systems?
May be there are methods to compute ground states only?
For example, I want to calculate the ground energy only for the two-dimensional Fermi-Hubbard model
(lattice 5x5 with total 9 fermions). txt file is attached. I terminate the program after 5 hours run on my laptop. 
Thank you.
[with_impurity_2D_table.txt](https://github.com/weinbe58/QuSpin/files/2824333/with_impurity_2D_table.txt)

**Comment by mgbukov** [comment]
Hi, one of the problems with exact diagonalization methods is that they
don't scale conveniently with the system size.

The best you can do is use the eigsh function, which you already do, but if
the system size becomes too large (as in your example) then it depends on
your computing power. State of the art calculations are usually performed
on computing clusters but even clusters struggle when the Hilbert space
dimension basis.Ns becomes too large.

QuSpin does not support any approximate methods, such as DMRG or other
MPS-based techniques as of now. You can google the ALPS project, which has
such features.

Note that in certain cases, if you know the state (like the GS of the
Hubbard model for U>>J), you can write down the wavefunction (sometimes you
can still compute the basis even if diagonalization is not feasible) and
maybe evolve the state in time for larger systems than ED is
available/doable.

Not sure how much this helps,
Marin

**Comment by mgbukov** [comment]
So, the exact ground state can be constructed in the case `J=0` and `U>0` -- the system is frozen, there is no kinetic energy so the eigenstates are the Fock states. Depending on the filling, you will have a degenerate GS or not. The Hamiltonian is diagonal, so there is no need to diagonalize. 

In the atomic limit, $U/J >> 1$, I think the exact GS is not known analytically, but one can use (degenerate) perturbation theory to construct it. I do not know a paper for this, but I would look for something old, like from the 70's or so. An elegant way to avoid using degenerate perturbation theory is to apply a Schrieffer-Wolff transformation, but this won't give you the state -- it is operator-valued perturbation theory, so you'll end up with an effective Hamiltonian to diagonalize.

**Comment by BaronWolfenstein** [comment]
Schrieffer-Wolff is a good idea, but you might try looking in the book by Negele and Orland, I think they might have a section on this sort of perturbation theory.
