### ISSUE TITLE
reshaping for entropy calculation fails for system sizes N>31

### ISSUE THREAD

**Issue by weinbe58** [weinbe58/QuSpin#176]
So I recently was made away that NumPy only allows for reshaping arrays with a maximum tuple length of 32:

```
import numpy as np

a = np.empty(2**32,dtype=np.int8)
a_r = a.reshape(tuple(2 for i in range(32))+(-1,))
```

this means that for people calculating the entanglement for large system sizes this will fail to reshape the array. I'm pretty sure NumPy will not be changing this anytime soon and so we are kind of left with 2 options:

1) try to do the reshaping/transposing in 2 or more steps.
2) write a low level function to do this operation ourselves. 

I actually don't think 2) is a bad idea because it will give us more control over the memory allocation. we could just write _reshape_subsys.py to make it a cython script. What do you think @mgbukov?

**Comment by weinbe58** [comment]
This seems to be a long term issue: https://github.com/numpy/numpy/issues/5744

**Comment by mgbukov** [comment]
this is fixed in v. 0.3.1
