### ISSUE TITLE
add under-the-hood p_con feature to basis.ent_entropy and basis.partial_trace

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#181]
it may be possible to use the p_con feature in `basis.partial_trace()` to gain some efficiency. In v. 0.3.1, any state is transformed into the full 2^N basis before it can be reduced.

Note: for this to work, the reduced density matrix will have to be allowed to have matrix elements in all p_con sectors up to the number of particles, even if the original (non-reduced) density matrix has a fixed number of particles. 

Before implementing this, one can test the feasibility of the idea using the `basis.proj()` function.

**Comment by weinbe58** [comment]
Implementing the proper get_vec code is basically there in basis_general but needs to be implemented in basis_1d, however this won't be too difficult. 

The issue is that how do we reshape the vector in order to do the partial trace to begin with.
