### ISSUE TITLE
dynamic list scalar multiplication bug

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#182]
scalar multiplication by a `hamiltonian` object which consists of a dynamic list only, is erroneously assumed in-place by default, and appears to modify the dynamic list.

see minimal bug script:
[bug.txt](https://github.com/weinbe58/QuSpin/files/2887947/bug.txt)

**Comment by weinbe58** [comment]
ah thanks, this is a simple bug to fix, it will be fixed in the next release. 

for now you can fix this by doing:

```
H = S_z_dyn.copy(deep=True)
H *= (tau/(2*J+1))
```

unfortunately the default flag for `deep` is `False` which caused the issue.
