### ISSUE TITLE
Build QuSpin with Intel compilers.

### ISSUE THREAD

**Issue by weinbe58** [weinbe58/QuSpin#187]
I think this would be a pretty neat thing to try, it would allow QuSpin to be optimized for Intel processors and would also allow user to use co-processors like the Xeon-Phi. 

@mgbukov I'll try to build this on the SCC and access the Xeon-Phi processor they have on the cluster to see if QuSpin benefits from this massive parallel architecture, it has 64 cores on a single chip!

**Comment by mgbukov** [comment]
architectures have changed a lot
