### ISSUE TITLE
general_basis.make() failing because Ns_block_est is not set properly.

### ISSUE THREAD

**Issue by weinbe58** [weinbe58/QuSpin#196]
this method will end up stalling due to the fact that the block estimate is not set properly in the python code and also there is an issue with the general_basis_core code not properly throwing an error when this estimate is too low.

**Comment by mgbukov** [comment]
here's a minimal script
[bug.txt](https://github.com/weinbe58/QuSpin/files/2962307/bug.txt)

**Comment by mgbukov** [comment]
This is fixed in branch `partial_get_vec` by adding a new attribute `self._Ns_block_est` to `basis_general`
