### ISSUE TITLE
slightly different values. Imrove the accuracy.

### ISSUE THREAD

**Issue by Chapa1** [weinbe58/QuSpin#199]
Hello everyone!
I have found out that the ground energies obtained after the successive run of the program are slightly different. I wonder what the origin of the error is? 
see the .txt file.
It gives the energies
-10.34699311
-10.34699251
-10.34697718
-10.34699064 
and so on.
Is it possible somehow to increase the accuracy?
Also, if the repulsion becomes U = 100000000000000000.0
then it gives strange values like
-62.39853452
-157.23615337 and so on.
[hard-core_bosons.txt.txt](https://github.com/weinbe58/QuSpin/files/2971055/hard-core_bosons.txt.txt)

**Comment by weinbe58** [comment]
that's weird, what operating system are you running? I can't reproduce the results on Linux.

**Comment by weinbe58** [comment]
OK its also not produced on windows.

**Comment by weinbe58** [comment]
could you give me the OS, and version of QuSpin (e.g. 0.3.2 omp or 0.3.2 no omp)

**Comment by Chapa1** [comment]
Windows 10 Pro
How can I found the version of QuSpin?

**Comment by weinbe58** [comment]
in the anaconda prompt run: conda list quspin

**Comment by Chapa1** [comment]
QuSpin 0.3.0 and python 36

**Comment by weinbe58** [comment]
OK what happens if you run: conda update -c weinbe58 quspin?

**Comment by Chapa1** [comment]
I updated  quspin  0.3.2            py36h9702182_0    weinbe58
Now the program gives 
[-10.34698565]
[-10.3469892]
[-10.34699073]

**Comment by weinbe58** [comment]
OK, so far I'm trying to reproduce this and I can't seem to get it to work. I'm on linux and using spyder with python=3.6 and it gives the same result every time. could you list which versions of numpy and scipy you have installed?

**Comment by Chapa1** [comment]
# Name                    Version                   Build  Channel
numpy                     1.15.4           py36h19fb1c0_0
numpy-base                1.15.4           py36hc3f5095_0
numpydoc                  0.8.0                      py_1    conda-forge
scipy                     1.2.0            py36h29ff71c_0

**Comment by weinbe58** [comment]
OK its reproducing the bug with these settings.

**Comment by weinbe58** [comment]
I think there is an issue with convergence issue with scipy.sparse.linalg.eigsh, the algorithm is iterative and starts from a random initial state, if you fix the random seed using: np.random.seed(0) you get the same result you will see that the result becomes fixed. 

I don't think its an issue with QuSpin, but let me try and come up with a simple example which will reproduce this without quspin.

**Comment by Chapa1** [comment]
I write np.random.seed(0) 
before 
E_GS,V_GS=H.eigsh(k=1, which='SA')
and still get different results:
[-10.34699452]
[-10.34699288]
[-10.34700697]

**Comment by weinbe58** [comment]
That's true I'm getting that with a larger U, I still think it is a convergence issue with eigsh unfortunately, you're pushing the U to be quite large, 1e16 and remember numerical precision is around 1e-16.

**Comment by weinbe58** [comment]
OK this seems to give similar results:

```
from scipy.sparse import dia_matrix,random
from scipy.sparse.linalg import eigsh
import numpy as np

N = 4000
U = 100000000000000.0

diag = np.atleast_2d(np.random.choice([0,U,8*U],p=[0.05,0.45,0.5],size=N))

D = dia_matrix((diag,[0]),shape=(N,N))
A = -random(N,N,format="csr",density=np.log(N)/N)

A = (A+A.T)/2.0 + D


for i in range(100):
    E,V = eigsh(A,k=1,which="SA")
    
    print(E)
```

**Comment by Chapa1** [comment]
Thank you for your help, Phillip!
I understand that I should not set large values for the repulsion. 
For U = 10000000.0 I get the same results.

**Comment by Chapa1** [comment]
Is it possible to simulate in QuSpin hard-core bosons without setting strong repulsion?

**Comment by mgbukov** [comment]
Yes, hardcore bosons are the same as spin-1/2 particles.

Marin

**Comment by weinbe58** [comment]
yes to do this, just use the boson basis with sps=2 it will only allow one boson per site.
