### ISSUE TITLE
Python3 doesn't need "from itertools import zip"

### ISSUE THREAD

**Issue by alexandreday** [weinbe58/QuSpin#20]
In python3 zip is predefined and you don't need to import it. The following line in 
"quspin/tools/block_tools.py":
 `from itertools import zip` 
This generates an error for python3. To fix perhaps just remove the import (there are 3 of them) and change `izip` for `zip`. For portability between python2 and python3, you may find the suggestions [here](https://github.com/nschloe/matplotlib2tikz/issues/20) useful.

**Comment by weinbe58** [comment]
fixed by [#21](https://github.com/weinbe58/QuSpin/pull/21)
