### ISSUE TITLE
missing contiguity check for bitwise ops can lead to wrong results

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#200]
there is a missing check for the contiguity of the input arrays in the bitwise operation functions of the general basis classes. This may lead to wrong results, see this example:

```
rom quspin.basis import bitwise_not,bitwise_and,bitwise_or,bitwise_xor,bitwise_leftshift,bitwise_rightshift
import numpy as np

b=np.array([35740, 35740, 35740, 35740, 35740, 35740, 35740, 35740, 35740, 35740],dtype=np.uint32)
i=np.array([ 2, 10,  3,  8,  9, 11, 13,  4,  6,  2],dtype=np.uint32)

I=np.array([ [2,1], [10,1],  [3,1],  [8,1],  [9,1], [11,1], [13,1],  [4,1],  [6,1],  [2,1]],dtype=np.uint32)
ii=I[:,0] 

print(i.flags['C_CONTIGUOUS'])
print(ii.flags['C_CONTIGUOUS'])

print('i-ii:', i-ii)
print('i:',bitwise_rightshift(b,i) )
print('ii:',bitwise_rightshift(b,ii) )
```

**Comment by weinbe58** [comment]
oh yes definitely I think we talked about this at some point during the implementation. 

In the future I will see if we can implement these functions as a numpy ufunc which will take care of this issue.

**Comment by mgbukov** [comment]
c-contiguity should be fixed now in branch partial_get_vec.

I'm leaving the issue open because of the numpy ufunc which we need to implement at some point of time

**Comment by mgbukov** [comment]
fixed in partial_get_vec branch, merged into dev_0.3.3
