### ISSUE TITLE
About the sort issue of H.eigsh's energies

### ISSUE THREAD

**Issue by zuozw** [weinbe58/QuSpin#201]
Hi, I am using the spinless class to calculate the energies about the interaction system, but I found two problems.
1) the energies of H.eigsh is not sorted.
2) the energies are not consist with the papers (Fig.3e in arXiv:1210.7696). About the long-range electron interaction terms (like Coulomb interaction).

For the first, maybe it should be the issue of scipy.sparse.linalg.eigsh. I can use the np.argsort to sort these energies and fix this problem.
Second one, these energies are not the same to the paper, I can not find the bug.

**Comment by weinbe58** [comment]
Ah I see, OK nu is related to the number of unit cells not sites. OK I need to read this if this going to make any sense

**Comment by zuozw** [comment]
It should be the long-range electron interaction(like Coulomb interaction) inducing this discrepancy. I should not omit the long-range term. In principle, I should add infinity sites list for the interaction terms. Numerically, we should add as much as possible terms.

In a word, it is the calculation of Coulomb Interactions in a periodic lattice. For example, https://journals.aps.org/prb/abstract/10.1103/PhysRevB.15.1959
