### ISSUE TITLE
About installing the new QuSpin version

### ISSUE THREAD

**Issue by srujans** [weinbe58/QuSpin#202]
Hello Developers,
   I am facing some issue while installing the QuSpin which is quite unusual for me. I am unable to install the 0.3.2 version on my cluster account as you can see from the attached .png file. 

![image](https://user-images.githubusercontent.com/12464481/54598432-84fc0180-4a5e-11e9-9d60-20d7e197e807.png)

I realized this issue of version when I get the following error in my code.

![image](https://user-images.githubusercontent.com/12464481/54598778-4581e500-4a5f-11e9-80ce-f24c9f3ee0fa.png)

I really appreciate any form of help regarding this issue.

Thank You.

**Comment by srujans** [comment]
While doing the installation for the first time, I got the following issue which I resolved using the command shown in below .png files.  
![previous_try](https://user-images.githubusercontent.com/12464481/54600407-b676cc00-4a62-11e9-8b49-83e481d7c109.png)

![previous_try11](https://user-images.githubusercontent.com/12464481/54600439-c8f10580-4a62-11e9-935d-c33fa86d979b.png)

Thank You.

**Comment by weinbe58** [comment]
This doesn't seem right, the latest version is 0.3.2

how about you try the following:

$ conda create -n test_install -c weinbe58 quspin

**Comment by srujans** [comment]
Hello weinbe58,

Thanks for the reply. Actually, QuSpin updated perfectly on my local system but not on my institute cluster account. I tried the above command and got below output which seems similar to the output during first attempt of updating QuSpin-0.3.1 on cluster.

![image](https://user-images.githubusercontent.com/12464481/54614877-1ed5a580-4a83-11e9-879f-a03afa7948b9.png)

Thanks.

**Comment by weinbe58** [comment]
this seems to be a common issue: https://github.com/conda/conda/issues/6121 try following what is discussed here maybe.

**Comment by srujans** [comment]
Hello weinbe58,
Thanks a lot for the link. I looked into it. 
Actually, I realized that even if "conda list quspin" is not showing correct version I am still able to use most of the functionality of the updated version on cluster. And since this issue is more general and not directly related to the QuSpin, I think closing this issue here is ok, right?

**Comment by mgbukov** [comment]
@srujans, can u post here the anaconda version on your cluster? 

One way out which should work is to install miniconda locally in your cluster home directory. Then you can have a recent version of anaconda :), so u can just create an environment and install quspin.

**Comment by srujans** [comment]
Hello mgbukov,
Here's the output to "conda list anaconda"

![image](https://user-images.githubusercontent.com/12464481/54941059-f3a2f880-4f51-11e9-8291-9dfa6d08af47.png)

Sure, I will try above method.

**Comment by mgbukov** [comment]
did installing your own miniconda version work?

I guess part of the problem is coming from the anaconda version. Anaconda had a major new release with version 2.5 (your cluster currently has an older one).

**Comment by srujans** [comment]
Hello mgbukov, 
I apologise for the late reply. The thing is that even though it's not showing 0.3.2, I am able to use most of the necessary newly modified functions like "get_vec"  and "get_proj".  Also it is generating expected pre-thermalized behaviour in my project work. So that's why I didn't try above approach yet. I will do it as soon as possible (immediately after project presentation).
Thanks a lot!

**Comment by srujans** [comment]
Hello mgbukov,
        I tried creating a new environment and updated the anaconda version. The specifications are in the below image. Still, I am getting the same error (please see the second image). I think it's not a problem because almost all new improvements (which are necessary for my project) are working without any error. 

![image](https://user-images.githubusercontent.com/12464481/56404663-8b5fe200-6285-11e9-9013-597eecc072a8.png)

![image](https://user-images.githubusercontent.com/12464481/56404842-a8e17b80-6286-11e9-822e-96e270e3c7fb.png)

**Comment by srujans** [comment]
Hello Developers, 
    I think since this issue is not directly related to "QuSpin"  package (issue particular to my system), I am closing this issue here (most of the functionality working fine in the cluster as well).
