### ISSUE TITLE
change order of loops

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#203]
there is a speedup if the momentum loops are the innermost ones.

**Comment by mgbukov** [comment]
For the time being, the users can use the `block_order` optional argument in the `basis_general` classes.

@weinbe58 we need to update the doc to specify that the rightmost string in the `block_order` list is executed in the innermost loop of the internal cpp code, so momentum symmetries should go last.

**Comment by weinbe58** [comment]
TODO:
1. reverse order of the `block_order` list so that the first elements are in the inner most loops of the appear first
2. update the documentation to reflect 1. 
3. update example11.py line 60,73 reverse the order to reflect this change.
