### ISSUE TITLE
Is it possible to store the "spin_basis_general" object to a file?

### ISSUE THREAD

**Issue by zenonofelea** [weinbe58/QuSpin#213]
It would be useful when creation of symmetries-respecting basis takes long time. Thanks.

**Comment by weinbe58** [comment]
@zenonofelea Did you find a work around for this? 

I know that at this point it is not possible to pickle the general basis objects because of the underlying implementation, This is definitely something we would like to fix in the future.

**Comment by zenonofelea** [comment]
> @zenonofelea Did you find a work around for this?
Not really. Just was not sure about importance of this for other user (that is why I "closed" the issue)

**Comment by weinbe58** [comment]
I've added this feature for the general basis classes into #205

**Comment by zenonofelea** [comment]
> I've added this feature for the general basis classes into #205

Excellent, thanks. Will try it.
