### ISSUE TITLE
Critical installation issue on Linux Mint 18.3

### ISSUE THREAD

**Issue by DarthMalloc** [weinbe58/QuSpin#214]
I am running a Linux Mint 18.3 64-bit machine, with gcc/g++ 7.1, and I have encountered a cython compilation error trying to install QuSpin manually for Python3, as shown here:

In file included from /home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/general_basis_utils.cpp:630:0:
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/source/general_basis_core.h:38:57: error: ‘>>’ should be ‘> >’ within a nested template argument list
   bool check_pcon(const I,const std::set<std::vector<int>>&);
                                                         ^
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/source/general_basis_core.h:201:80: error: ‘>>’ should be ‘> >’ within a nested template argument list
 eral_basis_core<I>::check_pcon(const I s,const std::set<std::vector<int>> &Np){
                                                                        ^
In file included from /home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/general_basis_utils.cpp:630:0:
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/source/general_basis_core.h: In member function ‘bool basis_general::general_basis_core<I>::check_pcon(I, const std::set<std::vector<int> >&)’:
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/source/general_basis_core.h:208:35: error: ‘>>’ should be ‘> >’ within a nested template argument list
  typename std::set<std::vector<int>>::iterator it;
                                   ^
In file included from /home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/general_basis_utils.cpp:632:0:
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/source/general_basis_op.h: At global scope:
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/source/general_basis_op.h:350:39: error: ‘>>’ should be ‘> >’ within a nested template argument list
         const std::set<std::vector<int>> &Np_set, // array with particle conser
                                       ^
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/source/general_basis_op.h: In function ‘int basis_general::general_op_bra_ket_pcon(basis_general::general_basis_core<I>*, int, const char*, const int*, std::complex<double>, npy_intp, const std::set<std::vector<int> >&, const I*, I*, T*)’:
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/source/general_basis_op.h:360:33: error: ‘>>’ should be ‘> >’ within a nested template argument list
   const std::set<std::vector<int>> Np_set_local = Np_set;
                                 ^
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/general_basis_utils.cpp: In function ‘PyObject* __pyx_fuse_2__pyx_f_18general_basis_core_basis_to_python(basis_general::uint256_t*)’:
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/general_basis_utils.cpp:29735:60: error: invalid cast from type ‘boost::enable_if_c<true, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> > >::type {aka boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<256u, 256u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> >}’ to type ‘int’
     __pyx_t_2 = __Pyx_PyInt_From_int(((int)(__pyx_v_val & 1))); if (unlikely(!_
                                                            ^
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/general_basis_utils.cpp: In function ‘PyObject* __pyx_fuse_3__pyx_f_18general_basis_core_basis_to_python(basis_general::uint1024_t*)’:
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/general_basis_utils.cpp:29860:60: error: invalid cast from type ‘boost::enable_if_c<true, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<1024u, 1024u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> > >::type {aka boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<1024u, 1024u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> >}’ to type ‘int’
     __pyx_t_2 = __Pyx_PyInt_From_int(((int)(__pyx_v_val & 1))); if (unlikely(!_
                                                            ^
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/general_basis_utils.cpp: In function ‘PyObject* __pyx_fuse_4__pyx_f_18general_basis_core_basis_to_python(basis_general::uint4096_t*)’:
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/general_basis_utils.cpp:29985:60: error: invalid cast from type ‘boost::enable_if_c<true, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<4096u, 4096u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> > >::type {aka boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<4096u, 4096u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> >}’ to type ‘int’
     __pyx_t_2 = __Pyx_PyInt_From_int(((int)(__pyx_v_val & 1))); if (unlikely(!_
                                                            ^
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/general_basis_utils.cpp: In function ‘PyObject* __pyx_fuse_5__pyx_f_18general_basis_core_basis_to_python(basis_general::uint16384_t*)’:
/home/justin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/general_basis_utils.cpp:30110:60: error: invalid cast from type ‘boost::enable_if_c<true, boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<16384u, 16384u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> > >::type {aka boost::multiprecision::number<boost::multiprecision::backends::cpp_int_backend<16384u, 16384u, (boost::multiprecision::cpp_integer_type)0u, (boost::multiprecision::cpp_int_check_type)0u, void> >}’ to type ‘int’
     __pyx_t_2 = __Pyx_PyInt_From_int(((int)(__pyx_v_val & 1))); if (unlikely(!_

Are there additional installation requirements (e.g. gcc/g++ version) that are not mentioned in the documentation? If not, then there is some error in the code for this version of QuSpin.

I need QuSpin for a major research project, so I would greatly appreciate any solutions that anyone might be able to provide.

**Comment by weinbe58** [comment]
Oh yes you need the Boost library. when you install Boost you need to make sure the headers are put into the `includes/` directory in your python installation.

**Comment by weinbe58** [comment]
could you run the following script:
```
from __future__ import print_function
from sysconfig import get_paths
print(get_paths()["data"])
```
and paste the output here?

**Comment by DarthMalloc** [comment]
Thank you very much for getting back to me.

The output that I got was just 
/usr

Is there as particular version of the Boost library that I need to install? Also, is there an automatic way to send the boost headers into the correct folder, or do they need to be moved manually?

**Comment by weinbe58** [comment]
actually one more thing could you run:
```
from __future__ import print_function
from numpy import get_include
from sysconfig import get_paths
print(get_paths()["data"],get_include())
```
I just need to see where numpy is storing its headers. 

I don't think the version matters it just needs to have the multiprecision headers included, however you don't need to install the pre-compiled binaries with boost you only need to install the "header only" version.
When you install it the installer should ask you to pick a directory to install the headers to. Install them to: `/usr/includes/` assuming that directory exists, if it doesn't you can create it and then install boost.

**Comment by weinbe58** [comment]
Sorry not `/usr/includes` it needs to be: `/usr/include/`

**Comment by weinbe58** [comment]
@DarthMalloc is this still an issue or can I close this?

**Comment by DarthMalloc** [comment]
Sorry about the delay. The installation issue has been resolved now.
