### ISSUE TITLE
User defined operators

### ISSUE THREAD

**Issue by jzhan039** [weinbe58/QuSpin#216]
Is it possible to define any operators, e.g. a single-element matrix |0><1|, and put them into Hamiltonian?

**Comment by mgbukov** [comment]
yes, one can do this. Recall first that basis states are represented as integers in quspin (see, eg `basis.states`). Suppose now the state |0> corresponds to the integer `s`, and the state |1>, to the integer `t`. You need to do the following:

0) construct a `basis` object.

1) find the indices of `s` and `t` in the `basis`.

```
ind_s = basis.index(s)
ind_t = basis.index(t)
```

2) construct a sparse matrix of size of dimension dim(H-space) x dim(H-space), and fill in the (ind_s,ind_t) matrix element with unity (or any other coupling for your operator)

```
custom_operator=scipy.linalg.sparse.csr_matrix( shape=(basis.Ns, basis.Ns), dtype=np.float64 )
custom_operator[ind_s,ind_t] = 1.0
```

3) create a `hamiltonian` from the matrix

```
static=[custom_operator]
quspin_operator = hamiltonian(static, [], dtype=np.float64, check_herm='False')
```

**Comment by jzhan039** [comment]
Thanks, mgbukov. It helps.
