### ISSUE TITLE
Restricting allowed basis states

### ISSUE THREAD

**Issue by dooleysh** [weinbe58/QuSpin#217]
Hi,

I am looking at a 1d spin system with an 'exclusion rule' that forbids certain basis states. In particular, states with consecutive 1's (e.g. |0110>) are excluded.

Can I just remove the states I would like to exclude from the list of basis states returned by calling spin_basis_1d, or is this likely to mess things up and give unreliable results?

Thanks,
Shane

**Comment by weinbe58** [comment]
Hello!

So you can remove states from the basis; however you have to make sure you change both the `basis._basis` attribute and the `basis._Ns` characteristics of your `basis` object. 

Also, you can manually install the code under branch `user_basis` which we are working on creating a basis which allows the user to define a customizable basis. 

here is a script which does a similar restricted Hilbert space such that a `0` has to have a `1` behind and in front of it:

```python
from __future__ import print_function,division
from quspin.basis.user import user_basis,check_state_nosymm_sig_32,op_sig_32,map_sig_32
from quspin.basis import spin_basis_1d
from quspin.operators import hamiltonian
from quspin.tools.misc import mean_level_spacing
from scipy.special import comb
import scipy.sparse as sp
from numba import carray,cfunc
from numba import uint32,int32
import numpy as np
import sys
try:
    import slepc_diag
    slepc=True
except ImportError:
    slepc=False
    pass

# costumized opstr function
@cfunc(op_sig_32,
    locals=dict(s=int32,b=uint32))
def op_func(resptr,op,ind,N):
    # using struct pointer to pass results 
    # back to C++ see numba Records
    res = carray(resptr,1)
    err = 0
    ind = N - ind - 1 # convention for QuSpin for mapping from bits to sites.
    s = (((res[0].state>>ind)&1)<<1)-1
    b = (1<<ind)

    if op==120: # "x" is integer value 120 (check with ord("x"))
        res[0].state ^= b
    elif op==121: # "y" is integer value 120 (check with ord("y"))
        res[0].state ^= b
        res[0].matrix_ele *= 1.0j*s
    elif op==122: # "z" is integer value 120 (check with ord("z"))
        res[0].matrix_ele *= s
    else:
        res[0].matrix_ele = 0
        err = -1

    return err

@cfunc(check_state_nosymm_sig_32,locals=dict(
    s_shift_left=uint32,s_shift_right=uint32))
def check_state_constraint(s,N,args):
    # require that a bit with 1 must be preceeded and followed by 0

    mask = (0xffffffff >> (32 - N))
    # cycle bits left by 1 periodically
    s_shift_left = (((s << 1) & mask) | ((s >> (N - 1)) & mask))

    # cycle bits right by 1 periodically
    s_shift_right = (((s >> 1) & mask) | ((s << (N - 1)) & mask))

    return (((s_shift_right|s_shift_left)&s))==0


# define full lattice size
N = 10
# full hilbert space is required
Ns_full = 2**N 

check_state_nosymm=(check_state_constraint,None)
# no symmetries to apply.
maps = dict()
# construct user defined basis
basis = user_basis(np.uint32,N,Ns_full,op_func,allowed_ops=set("xyz"),sps=2,
    check_state_nosymm=check_state_nosymm,Ns_block_est=300000,**maps)
# print basis
print(basis)


```

**Comment by dooleysh** [comment]
Thanks!

**Comment by dooleysh** [comment]
Hi again,

I tried your first suggestion but unfortunately I'm getting an error. Here is the example code given in the documentation, but with the one element removed from the basis.

`from quspin.operators import hamiltonian # Hamiltonians and operators
from quspin.basis import spin_basis_1d # Hilbert space spin basis
import numpy as np # generic math functions
#
##### define model parameters #####
L=4 # system size
J=1.0 # spin interaction
g=0.809 # transverse field
h=0.9045 # longitudinal field
##### define periodic drive #####
Omega=4.5 # drive frequency
def drive(t,Omega):
	return np.cos(Omega*t)
drive_args=[Omega]
#
##### construct basis in the 0-total momentum and +1-parity sector
basis=spin_basis_1d(L=L,a=1,kblock=0,pblock=1)
basis._basis = basis._basis[1:]     # <---------------------------
basis._Ns = basis._Ns - 1              # <---------------------------
print(basis)
# define PBC site-coupling lists for operators
x_field=[[g,i] for i in range(L)]
z_field=[[h,i] for i in range(L)]
J_nn=[[J,i,(i+1)%L] for i in range(L)] # PBC
# static and dynamic lists
static=[["zz",J_nn],["z",z_field]]
dynamic=[["x",x_field,drive,drive_args]]
###### construct Hamiltonian
H=hamiltonian(static,dynamic,dtype=np.float64,basis=basis)
print(H.toarray())`

This gives me the following error:

`Traceback (most recent call last):
  File "rough_work_1.py", line 30, in <module>
    H=hamiltonian(static,dynamic,dtype=np.float64,basis=basis)
  File "/Users/dooleysh/miniconda3/lib/python3.6/site-packages/quspin/operators/hamiltonian_core.py", line 319, in __init__
    self._static=make_static(self._basis,static_opstr_list,dtype)
  File "/Users/dooleysh/miniconda3/lib/python3.6/site-packages/quspin/operators/_make_hamiltonian.py", line 111, in make_static
    H=H+_sp.csr_matrix((ME,(row,col)),shape=(Ns,Ns),dtype=dtype) 
  File "/Users/dooleysh/miniconda3/lib/python3.6/site-packages/scipy/sparse/compressed.py", line 51, in __init__
    other = self.__class__(coo_matrix(arg1, shape=shape))
  File "/Users/dooleysh/miniconda3/lib/python3.6/site-packages/scipy/sparse/coo.py", line 184, in __init__
    self._check()
  File "/Users/dooleysh/miniconda3/lib/python3.6/site-packages/scipy/sparse/coo.py", line 230, in _check
    raise ValueError('row index exceeds matrix dimensions')
ValueError: row index exceeds matrix dimensions`

Thanks again for all your help,
Shane

**Comment by weinbe58** [comment]
Hi Shane,

Yes, unfortunately, it is a bit more complicated than I first thought, sorry its been a while since I've looked under the hood at the basis_1d code. I guess there is still the option of using the experimental branch, I've tried it, and it seems to work, I need to work out some issues with documentation and tests for the code but as far as I Can tell it seems to work for created the restricted Hilbert spaces.  

Another option would be to build the projection operator to the restricted Hilbert space and then apply it to the Hamiltonian you create.

**Comment by mgbukov** [comment]
@dooleysh we have just released the new version of quspin, which has the `user_basis` class. With its help you should be able to do what you want. Check out

http://weinbe58.github.io/QuSpin/user_basis.html

and also this example:

http://weinbe58.github.io/QuSpin/examples/example14.html#example14-label
