### ISSUE TITLE
Ground state of a time-dependent hamiltonian

### ISSUE THREAD

**Issue by Chapa1** [weinbe58/QuSpin#218]
Dear Quspin developers,
Could you please answer my question?
If I create a time-dependent hamiltonian H with static and dynamic parts
and write
```
E_GS,V_GS=H.eigsh(k=1, which='SA') 
psi= V_GS[:,0]
```
Does psi correspond to the ground state of H at initial time?
Thank you in advance.

**Comment by mgbukov** [comment]
Yes.

The hamiltonian.eigh() routine (as well as many others hamiltonian function
methods, see documentation) have the optional argument 'time', which allows
you to toggle the time you want to do the operation at. The default is
'time=0' so your intuition is correct.

Marin
