### ISSUE TITLE
how to add decoherence into the Hamiltonian?

### ISSUE THREAD

**Issue by richardvancouver** [weinbe58/QuSpin#219]
Is there any option to add decoherence into the Hamiltonian (or H.evolve)?

Best,
R.Yang

**Comment by mgbukov** [comment]
There is the 'quspin.tools.evolution.evolve()' function which allows you to
code in arbitrary EOM and use Hamiltonian objects in it.

You would have to define the lindblad operators yourself and pass them as
optional arguments to the function (see example on GPE which shows how to
use the evolve function).

**Comment by weinbe58** [comment]
Also check this article out which details a method that can model decoherence using stochastic evolution of pure states. https://arxiv.org/pdf/1608.01317.pdf

**Comment by mgbukov** [comment]
@richardvancouver I coded up the Lindblad dynamics in quspin using the `evolve` function. Here is an example how this works for the optical Bloch equations (a two-level system).

There are two functions which define the same Lindblad dynamics -- one which is easy to understand but slow, and a second one which is fast but slightly memory inefficient [although this will only affect large systems]. You can play with the code to see how they work (line 121 vs 123 in the script below). Any feedback is much appreciated! 

@weinbe58 take a look -- maybe we can include this as part of evolve at a later stage and maybe construct a lindbladian constructor, similar to hamiltonian. 

[example17.txt](https://github.com/weinbe58/QuSpin/files/3390493/example17.txt)

**Comment by richardvancouver** [comment]
Thank you very much for your information, Bukov! Could you give a similar example for the Bose-Hubbard model (http://weinbe58.github.io/QuSpin/examples/example7.html)?  

Thanks a lot,
R.Yang


> @richardvancouver I coded up the Lindblad dynamics in quspin using the `evolve` function. Here is an example how this works for the optical Bloch equations (a two-level system).
> 
> There are two functions which define the same Lindblad dynamics -- one which is easy to understand but slow, and a second one which is fast but slightly memory inefficient [although this will only affect large systems]. You can play with the code to see how they work (line 121 vs 123 in the script below). Any feedback is much appreciated!
> 
> @weinbe58 take a look -- maybe we can include this as part of evolve at a later stage and maybe construct a lindbladian constructor, similar to hamiltonian.
> 
> [example17.txt](https://github.com/weinbe58/QuSpin/files/3390493/example17.txt)

**Comment by mgbukov** [comment]
For a Bose Hubbard system, all you need to do is change the Hamiltonian and the Lindbladian operator. Note that both are defined using the `hamiltonian` class. As you pointed out, constructing a bosonic Hamiltonian is shown in Example 7. 

I am not an expert on dissipative quantum dynamics, so I can't suggest a specific bosonic model to look at (i.e. a specific Lindbladian). You can do a literature search to see what keeps people excited.
