### ISSUE TITLE
Add method .todense() to exp_op class

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#22]
it'd be nice to be able to have

```exp_op(H,a=-1j*delta_time).get_mat().todense()```

or maybe just 

```exp_op(H,a=-1j*delta_time).todense()```

return a dense np.ndarray, since this object is typically dense.

Currently, the python syntax necessary to do this seems quite involved:

```np.asarray( exp_op(H,a=-1j*delta_time).get_mat().todense() )```

**Comment by weinbe58** [comment]
should be fixed by https://github.com/weinbe58/QuSpin/pull/23
