### ISSUE TITLE
How to calculate projective measurements with obs_vs_time

### ISSUE THREAD

**Issue by DarthMalloc** [weinbe58/QuSpin#224]
I am trying to get projective measurements using obs_vs_time. Does obs_vs_time give the final result of projective measurements, or is an additional step needed?

**Comment by mgbukov** [comment]
yes, `obs_vs_time` computes the projective measurement

\langle \psi(t) | O(t) | \psi(t) \rangle

for every time t. 

If the operator and/or the state are time independent, then it computes either

\langle \psi | O(t) | \psi \rangle

or

\langle \psi(t) | O | \psi(t) \rangle

Does this answer your question?

**Comment by weinbe58** [comment]
`obs_vs_time` does not collapse the wavefunction after each measurement.

**Comment by mgbukov** [comment]
you could also check out [this example](http://weinbe58.github.io/QuSpin/generated/quspin.tools.measurements.obs_vs_time.html#quspin.tools.measurements.obs_vs_time), in which we used `obs_vs_time` to compute the expectation of the observables H1 and H2 in the time-dependent state psi1_t (in both cases, this is a projective measurement at every time step). 

Essentially, if you have an quspin observable `H`, and a set of states stored in the columns of `psi_t`, then `obs_vs_time()` will do something like
```
H_expt=np.zeros_like(psi_t)
for j, psi in enumerate(psi_t.T): # loop over the states, one at a time
    H_expt[j] = H.expt_value(psi)
```
Note that to be able to compute the expectation value, the length of each state `psi` should match the dimensions of the operator matrix `H`.
