### ISSUE TITLE
expm_multiply_parallel omp bug

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#226]
when used in combination with omp, `expm_multiply_parallel` returns wrong result. 

-- only happens for omp, when I request more than 2 threads (so it might be related to my mac's architecture); the effect is more pronounced if I request more cores. 
-- only happens in the dev_0.3.3 branch; seems to be fine in the use_basis branch
-- only happens for a symmetry-reduced basis
-- only happens starting from L=12 upwards

[bug_expm_omp.txt](https://github.com/weinbe58/QuSpin/files/3364728/bug_expm_omp.txt)

**Comment by weinbe58** [comment]
What should I be looking for as a correct result for the script?

**Comment by weinbe58** [comment]
Also, does the `expm_multiply_parallel_test.py` pass?

**Comment by mgbukov** [comment]
I did not check the test.

As to the correct value, u can get it by setting the omp threads to one.

If the omp threads is large (say 8 for my mac) then the final output is
unstable (in the dev_0.3.3 branch) meaning that it's different from run to
run and this is the bug.

Marin

**Comment by weinbe58** [comment]
Seems like the issue is with the function I created to calculate the 1-norm of A, I'll take a look at that function again.

**Comment by weinbe58** [comment]
I fixed the issue with the 1-Norm but there is still a bug, I've even encountered it when using 1 thread with omp. I'm currently making sure it is not something unstable with the expm_multiply algorithm itself compared by comparing it with ED.

**Comment by weinbe58** [comment]
I think I found the issue. For some reason, an omp function is returning a wrong value then what I was intending. the function: `omp_get_max_threads` is not returning the value of `OMP_NUM_THREADS` for some weird reason which is causing my parallel algorithm to get really messed up.

**Comment by weinbe58** [comment]
Nevermind, I forgot that you're setting the number of threads in the script which is overriding what I set it in the terminal OK.

**Comment by mgbukov** [comment]
let's see, so were you able to figure out what causes the bug? If not I can try to dig deeper. 

What surprised me is that I can only reproduce the bug in dev_0.3.3, but not in the user_basis branch. But u didn't do any changes to expm_multiply_parallel in the user_basis branch, did u?

**Comment by mgbukov** [comment]
This is fixed in `small_fixes`
