### ISSUE TITLE
Computational basis state conventions

### ISSUE THREAD

**Issue by jsvandyke86** [weinbe58/QuSpin#227]
I'm a bit confused on the definition of the computational basis states.  Namely, the first reply to issue #2 seems to indicate that the Pauli z is given by [ [-1 , 0], [0,1]].  But when I try 
```
basis = spin_basis_1d(L=1,a=1)
sigz = hamiltonian([["z",[[1.0,0],]],],[],basis=basis,dtype=np.float64)
print(sigz)
```
I get the opposite result, [ [1 , 0], [0,-1]].  Did the convention change since that issue was posted?

Also, the first reply to #2 says that the down state comes first.  After doing:

` print(basis)`

I get that:

reference states: 
     0.  |1>
     1.  |0>

implying that |1> is down.  But then

```
i0 = basis.index("1")
psi = np.zeros(basis.Ns,dtype=np.float64)
psi[i0] = 1.0 # construct the state
print(sigz.expt_value(psi))
```
yields +1.0, instead of the -1.0 that is expected for the down state.

Thanks for the help!

**Comment by weinbe58** [comment]
We fixed the convention such that "1" is up now. The matrices should match the standard Pauli Matrix convention.

**Comment by jsvandyke86** [comment]
Cool, thanks!
