### ISSUE TITLE
Error in getting eigenvectors for quantum_operator object

### ISSUE THREAD

**Issue by DarthMalloc** [weinbe58/QuSpin#228]
I am trying to get the eigenvectors for a quantum_operator object as follows:
`from __future__ import print_function, division`
`from quspin.operators import *`
`from quspin.basis import *`
`from quspin.tools.measurements import *`
`from quspin.tools.Floquet import *`
`import numpy as np`
`import matplotlib.pyplot as plt`
`import pickle as pk`
`from pprint import *`

`L_1d = 16`
`Lx, Ly = 4, 4`
`N_2d = Lx * Ly`
`Omega = 3.0`
`A = 2.0`
`s = np.arange(N_2d)`
`x = s % Lx`
`y = s // Lx`
`T_x = (x + 1)%Lx + Lx*y`
`T_y = x + Lx*((y + 1)%Ly)`
`P_x = x + Lx*(Ly-y-1)`
`P_y = (Lx-x-1) + Lx*y`
`Z = -(s+1)`
`total = 0`

`X_1D = [[1.0, i] for i in range(L_1d)]`
`X_1D_list = [["x", X_1D]]`
`X_1D_dict = dict(X=X_1D_list)`
`X_op_1D = quantum_operator(X_1D_dict, basis=basis_1d, check_symm=False)`
`E_x1, V_x1 = X_op_1D.eigh()`

When I run this code, I get the following error:

ValueError: unexpected couplings: {'Z'} 

This error occurs for for the call to X_op_1D.eigh().

I would greatly appreciate any information available regarding why this is happening and how to fix it.

**Comment by mgbukov** [comment]
Hi,

If you look up the documentation page for the quantum_operator, the eigh()
method requires a pars dict (dictionary with coupling strengths), see here:

http://weinbe58.github.io/QuSpin/generated/quspin.operators.quantum_operator.html#quspin.operators.quantum_operator.eigh

I'll have to look up additionally why exactly this error message is thrown
by python.

**Comment by mgbukov** [comment]
Interesting, so the attached code works for me (I just added the basis to your code and got rid of packages you don't use). So I can't reproduce the error you mention above. Can you see if it runs for you? 

If it still produces a bug, can you post your numpy and scipy versions? 

[qop_bug.txt](https://github.com/weinbe58/QuSpin/files/3390040/qop_bug.txt)

**Comment by weinbe58** [comment]
What OS are you running this on @DarthMalloc?
