### ISSUE TITLE
Controlling the number of states for spin_basis_general

### ISSUE THREAD

**Issue by DarthMalloc** [weinbe58/QuSpin#231]
I am trying to create a basis for a 4x4 2D lattice so that its states are valid computational basis states, i.e. 2^N state vectors of dimension 2^N for some integer N. When I try to create a Hamiltonian for 2^16 states, I get a memory error. I am therefore wondering what the formula is for determining the number of states in the basis from the kxblock, kyblock, pxblock, pyblock, and zblock. Thank you very much for your help.

**Comment by weinbe58** [comment]
Do you have a code sample which produces this result?
