### ISSUE TITLE
Graphene

### ISSUE THREAD

**Issue by zaminpayma** [weinbe58/QuSpin#234]
Dear quspin users

How can I define graphen lattice in quspin?

**Comment by mgbukov** [comment]
Hi,

quspin can do arbitrary graphs, in particular also a honeycomb lattice. However, there is (still) no pre-defined lattice transformations class, so you'd need to put the honeycomb lattice in yourself:

1) draw on a piece of paper the honeycomb lattice and label the sites 0,...,N-1. Note the sites that connect to each other. Extract the two lattice translation maps that allow you to generate the honeycomb lattice by repeated application. 

2) in the site-coupling lists when defining the operators in your hamiltonian, connect only those sites which correspond to the connectivity of the honeycomb lattice. 

3) use one of the *basis_general* classes (if you intend to use symmetries).

For instance, to program a square lattice the lattice connectivity is defined via the square lattice translation maps `T_x` and `T_y`, see [this example](http://weinbe58.github.io/QuSpin/generated/quspin.basis.spin_basis_general.html#quspin.basis.spin_basis_general), which are used in the site-coupling lists in `line 26` (and in the basis if you want to use symmetries). For the honeycomb lattice, you'd need to modify these accordingly. 

If you want, give it a try and let us know if you have further questions about how to proceed.

**Comment by zaminpayma** [comment]
I read this example, but Tx and Ty show connected in x and y directions. How can I use Tx and Ty for honeycomb lattice.

**Comment by weinbe58** [comment]
The Bravais Lattice for the Honeycomb lattice is the triangular lattice. Basically, the Honeycomb lattice is two inter-woven triangular sub-lattices that are connected to each other. These are usually called sublattices A and B.  

To generate all the possible connections all you have to do is a loop over sublattice A and connect to the nearest sights on sublattice B. 

As for the symmetries, as far as I can tell, the symmetries of the honeycomb lattice are the same as the triangular lattice, but also includes a transformation which flips sublattices A to B and vice-versa.

**Comment by anton-buyskikh** [comment]
As a work around for hexagonal lattices, as well as other more complicated scenarios I can suggest `networkx`, in particular [hexagonal_lattice_graph](https://networkx.github.io/documentation/networkx-2.0/reference/generated/networkx.generators.lattice.hexagonal_lattice_graph.html)

This package has a nice output of the graph connectivity matrix, that can be used for creating the Hamiltonian as @weinbe58 suggested.

**Comment by mgbukov** [comment]
great! Too bad `networkx` is not supported by anaconda so we can't make it part of quspin.

@anton-buyskikh: if you want, however, you can set up a very simple minimal example script using networkx to create a many-body Hamiltonian on the honeycomb lattice, and we'll add it to the set of examples online for the benefit of other users.
