### ISSUE TITLE
Installation on google collaboratory 

### ISSUE THREAD

**Issue by qi-zakaria** [weinbe58/QuSpin#241]
Hello

I'm trying to use QuSpin on google colab, after the installation I get the following error when I import the package.

![Screenshot_2019-09-03 Google Colaboratory](https://user-images.githubusercontent.com/36313185/64167706-d861e080-ce41-11e9-924e-73ae1a60185e.png)

Thank you for your help.

**Comment by weinbe58** [comment]
I’ve never used this platform before but I will look into it!

**Comment by weinbe58** [comment]
How do you install packages on the python distribution of google colab?

**Comment by qi-zakaria** [comment]
normally, to install a package in google colab you use _pip install nameofthepackage_, I tried it for QuSpin and I got the following error
![Screenshot_2019-09-03 Google Colaboratory(1)](https://user-images.githubusercontent.com/36313185/64173800-f33b5180-ce4f-11e9-9816-87cfaac9cc81.png)
Then I tried cloning  using _pip install git+https://github.com/weinbe58/QuSpin.git_ and the installation went successfully ( but it is so long )

**Comment by weinbe58** [comment]
yes, we haven't set up installation from pypi yet, however that is neat that you were able to install it that way. could you attached the output's pip gave after installing from github?

**Comment by qi-zakaria** [comment]
This is what i get 
![Screenshot_2019-09-03 Google Colaboratory(2)](https://user-images.githubusercontent.com/36313185/64191108-a8313680-ce6f-11e9-98fe-e3af0f239560.png)

**Comment by weinbe58** [comment]
Thanks, did you install the requirest packages before running this? 

you need: numpy, scipy, joblib, cython, six, dill, gmpy2, numba

**Comment by qi-zakaria** [comment]
Thank you for your help. Quspin worked after installing the suggested packages, but only in Python 2

**Comment by weinbe58** [comment]
so according to this issue: https://github.com/scikit-learn-contrib/hdbscan/issues/273

they claim you need to first install cython and then install the package. So, in this case, why don't you try starting from scratch (remove everything if you can):

1) install requirest packages
2) install quspin from github

Let's see if that works.

**Comment by qi-zakaria** [comment]
I tried it but it does not work for python 3 only for 2.7

**Comment by weinbe58** [comment]
What platform are you using, e.g. windows os-x or linux?

**Comment by qi-zakaria** [comment]
I'm on linux, but i think this does not matter since i'm using google collaboratory with google's ressources. On my machine using linux, Quspin is working perfectly fine, but I switched to colab because it offers more computational resources.

**Comment by weinbe58** [comment]
OK I'll need to research this more, thanks for the report.

**Comment by mgbukov** [comment]
this can potentially be fixed if we include a pip installation for quspin

**Comment by honamnguyen** [comment]
The following works for me when I installed `conda` on colab and then used that to install `quspin`. It should take a couple minutes.
```
%%bash

# install conda for python 3.7
MINICONDA_INSTALLER_SCRIPT=Miniconda3-4.5.12-Linux-x86_64.sh
MINICONDA_PREFIX=/usr/local
wget https://repo.continuum.io/miniconda/$MINICONDA_INSTALLER_SCRIPT
chmod +x $MINICONDA_INSTALLER_SCRIPT
./$MINICONDA_INSTALLER_SCRIPT -b -f -p $MINICONDA_PREFIX

# update conda
conda install --channel defaults conda python=3.7 --yes
conda update --channel defaults --all --yes

# install quspin
conda install -c weinbe58 quspin --yes
```

Before you can import `quspin`, you will need to add its location to `sys.path`.
```
import sys
sys.path.append("/usr/local/lib/python3.7/site-packages")
import quspin
quspin.__version__
```
If you would like to avoid installing `quspin` every new runtime, you can copy the following to a directory in your google drive.
```
# !cp -r /usr/local/lib/python3.7/site-packages/quspin <your-directory>
# !cp /usr/local/lib/python3.7/site-packages/gmpy2.cpython-37m-x86_64-linux-gnu.so <your-directory>
```
You will then need to add `<your-directory>` to `sys.path` just like above.

**Comment by mgbukov** [comment]
@honamnguyen thanks! Note that you can install the `omp` version of `quspin` as well which should offer some speedup. 

For convenience, I put your instructions in a Google Colab:

[https://colab.research.google.com/drive/1nKJYNtLdpeUO1KkbJoWGrSep4s4G5AII?usp=sharing](https://colab.research.google.com/drive/1nKJYNtLdpeUO1KkbJoWGrSep4s4G5AII?usp=sharing)

**Comment by VivekSah2001** [comment]
@honamnguyen, does the same code work fine for windows as well?

**Comment by mgbukov** [comment]
I'm attaching here an example notebook that works on Colab. As usual, remove the .txt extension from the file to retrieve the notebook itself before running it. 

[quspin_collab.ipynb.txt](https://github.com/QuSpin/QuSpin/files/12865955/quspin_collab.ipynb.txt)
