### ISSUE TITLE
general basis other symmetries such as eigenvalues of weighted number operator

### ISSUE THREAD

**Issue by JanVanDieBos** [weinbe58/QuSpin#249]
Is there a way to use spinless_fermion_basis_general to restrict to a particular eigenvalue of the weighted number operator 0 n_0 + 1 n_1 + ..... L n_L? 

 I realize that this can be accomplished by restricting to a kblock and then transforming to the momentum basis, but for various reasons this is not an option for me.

**Comment by weinbe58** [comment]
I can't think of any obvious way of doing this at this point, but hopefully, soon we will release a new version which gives you much more control over the basis functionality.

**Comment by mgbukov** [comment]
@JanVanDieBos check out the new user_basis which is available online; It's a bit of a steep learning curve but we provide 6 examples which can serve as a guideline. None of these examples does exactly what you need, but u can easily modify them. If you still have questions, don't hesitate to send us questions!

http://weinbe58.github.io/QuSpin/user_basis.html

**Comment by weinbe58** [comment]
An example function which you might use is something like this:

```python

@cfunc(pre_check_state_sig_32)
def check_sum(s,N,args):
    n_constraint = args[0]
    n_list = args+1 # args is a pointer.
    count = 0
    for i in range(N):
        count += n_list[N-i-1]*(s&1)
        s >>= 1

    return count==n_constraint
```

The reason for accessing `n_list` in reverse order is because of the QuSpin convention that the 0th bit corresponds to the last lattice site.
