### ISSUE TITLE
update code to catch up with numpy

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#254]
/Users/mgbukov/miniconda3/envs/quspin37/lib/python3.7/site-packages/quspin/basis/base.py:382: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.

**Comment by weinbe58** [comment]
see: https://github.com/weinbe58/QuSpin/blob/master/quspin/basis/lattice.py#L200
