### ISSUE TITLE
Update user_basis examples

### ISSUE THREAD

**Issue by weinbe58** [weinbe58/QuSpin#255]
@mgbukov I just found out something nice.

so you cannot call a `Cfunc` from inside another `Cfunc` as per this thread:  https://github.com/numba/numba/issues/2247

however you can call a `jit` function inside a `Cfunc` so maybe it would be good to update the notes to discuss this as it can same people a lot of hassle writing long codes inside the `CFunc`.

**Comment by weinbe58** [comment]
Apparently reason, why this works, is because numba effectively inlines the entire code from the `jit` function into the `Cfunc`.

**Comment by mgbukov** [comment]
this is done starting from dev_0.3.4
