### ISSUE TITLE
new warning message from obs_vs_time

### ISSUE THREAD

**Issue by jsvandyke86** [weinbe58/QuSpin#260]
Hello,

I updated from v 0.3.2 to v 0.0.3, and I'm getting a new warning message when I run obs_vs_time, which does not appear in the earlier version:

/home/jvandyke/anaconda3/envs/envquspin/lib/python3.7/site-packages/quspin/tools/measurements.py:782: ComplexWarning: Casting complex values to real discards the imaginary part
  Expt_time[key][m+1] = Obs.expt_value(psi,time=time,check=False)

It seems like it might be related to Issue #225 , but the hamiltonian I am trying to measure is Hermitian.  I noticed that for my code, obs_vs_time returns a dict with real entries, whereas for other simpler test cases I get complex values returned (again calculating the energy of a Hermitian Hamiltonian -- so the imaginary part here is close to zero).  I don't understand why I get real numbers in one case and complex in the other -- it seems to me I am doing fundamentally the same thing, just with different choices of hamiltonians and psi_t generators.

This is a bit vague - please let me know if you would like more information about something.

Thanks very much,
John

**Comment by mgbukov** [comment]
@jsvandyke86 can you post here a minimal python script that displays the warning? Thanks!

**Comment by weinbe58** [comment]
@mgbukov I think i know what the issue is, sometimes the first state in a time-evolution generator is real, so the code things that the expectation values will all be real based on what you have written, but when the code starts to evolve the state it becomes complex and so the expectation value then becomes complex.

I suggest that instead of pre-allocating the array we just use lists and then cast the lists to arrays before returning the results. This might be infinitesimally slower and use a bit more memory but I think that should be fine since most of the work is actually evolving the state.

**Comment by jsvandyke86** [comment]
Yeah, I think that's definitely what's going on.  It only seems to happen when I pass a generator to obs_vs_time.  Passing the states explicitly as an ndarray does not trip the warning, even if the values are real.  Here's an example:

```
from quspin.basis import spin_basis_1d
from quspin.operators import hamiltonian, exp_op
from quspin.tools.measurements import obs_vs_time
import numpy as np

def evolve(ham,tvals,psi0):
    yield psi0
    dt = tvals[1]-tvals[0]
    Ut = exp_op(ham,a=-1.0j*dt)
    for tv in tvals[1:]:
        psi0 = Ut.dot(psi0)
        yield psi0

L=4
J=1.0
times = [0.0,0.1]

basis = spin_basis_1d(L=L,a=1)
J_list = [ [J,i,i+1] for i in range(L-1)]
static = [["zz",J_list],]
Ham = hamiltonian(static,[],basis=basis,dtype=np.float64)

print("pass states directly")
psit = np.zeros(shape=(2**L,2),dtype=float)
psit[0,:] = 1.0
meas = obs_vs_time(psit,times,{"energy":Ham})

print("use generator")
psi1 = np.zeros(shape=(2**L,),dtype=float)
psi1[0] = 1.0
psit = evolve(Ham,times,psi1)
meas = obs_vs_time(psit,times,{"energy":Ham})
```

**Comment by weinbe58** [comment]
The problem is only if the first state has a different type then the next states which can only happen with a generator, if you pass a list of states into the function it will cast them all to the same dtype.

**Comment by jsvandyke86** [comment]
Ah, that makes sense, thanks!

**Comment by mgbukov** [comment]
But can it happen at all that the evolved state is real-valued? Should we
just set drype to complex by default? The question is then if we should use
complex64 vs complex128.

Marin

**Comment by weinbe58** [comment]
Yes, but I think the easiest way around this is to just use lists in the code, it won’t be that much more expensive computationally and it will handle these issues
