### ISSUE TITLE
Construct arbitrary product states

### ISSUE THREAD

**Issue by HumpyBlumpy** [weinbe58/QuSpin#272]
Hello,

Thanks a lot for this package! I think it is great. I hope it is the right place to ask questions.

I am trying to create different kind of product states as initial state for performing time evolution. I looked at the examples and documentation but didnt find how to do what I want.

For example, I would like to initialize my 1d spin chain to spins all in +y. 
Or, all spins in +y except the first, which is -y.

What is the easiest way of accomplishing this?

**Comment by mgbukov** [comment]
One way to do this is to first create the product state you want in the z-basis, i.e. the computational basis, and then apply a local on-site rotation $\exp(-i \theta_j \sigma^x)$. Such on-site rotations can be constructed by means of their generators, see the `exp_op` class. 

Another way of creating product states would be to define a Hamiltonian $H = \sum_j h_j \dot \sigma_j$ , and then find its GS which will point towards the direction of the site-dependent field h_j [i.e. you choose h_j based on the state you want]. 

A third cheap way out would be to keep your product state in the z-basis, but rotate the terms in your Hamiltonian with which you'd like to evolve. E.g. if you want to evolve a product state in the y-basis with the Hamiltonian sigma_x, then it's the same as evolving a product state in the z-basis with the Hamiltonian sigma_y, etc.

**Comment by HumpyBlumpy** [comment]
Thanks!
