### ISSUE TITLE
large integer support for tensor_basis

### ISSUE THREAD

**Issue by HumpyBlumpy** [weinbe58/QuSpin#275]
I am trying to construct a tensor basis with more than 64 sites but this gives error
`TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int8') with casting rule 'same_kind'`

The documentation mentions
> large integer support for general basis classes
a) custom large integer data types supported in general basis

but it is not clear to me how to use it.

**Comment by weinbe58** [comment]
Could you provide a simple example that gives this error?

**Comment by HumpyBlumpy** [comment]
Lb =32 works, but Lb=33 throws the error.
```
Lb = 33 #boson system size
Ls = 1 #spin system size
J = 0.3 # hopping strength
omega0 = 1 # interaction 
Delta = 1
g=0.3
spin_boson_coupling = 10

###### create the basis
bosons = boson_basis_1d(Lb,Nb=[0,1])
spin = spin_basis_1d(Ls)
basis = tensor_basis(spin,bosons)
#print(basis)

hop = [[-J,i,i+1] for i in range(Lb-1)] # hopping 
onsite_bosons = [[omega0,i] for i in range(Lb)] # onsite energy
onsite_spins = [[Delta/2,i] for i in range(Ls)] # onsite interaction
spin_boson_int = [[g,0,spin_boson_coupling]] 

# create static lists
static = [
          ["|+-", hop], # up hop left
          ["|-+", hop], # up hop right
          ["|n", onsite_bosons], # 
          ["z|", onsite_spins], # down hop right
          ["-|+", spin_boson_int], # onsite interaction
          ["+|-", spin_boson_int] # onsite interaction
         ]
###### setting up operators	
no_checks = dict(check_pcon=False,check_symm=False,check_herm=False)
H = hamiltonian(static,[],basis=basis,**no_checks)

```

**Comment by weinbe58** [comment]
Thanks,  I found the error, I don't think there is a workaround at the moment unfortunately but this will be fixed in the next release which should hopefully be sometime next week.
