### ISSUE TITLE
+ and - operators incorrectly defined for spin_basis_1d

### ISSUE THREAD

**Issue by HumpyBlumpy** [weinbe58/QuSpin#280]
Consider
```
Ls = 1 
J=1

basis = spin_basis_1d(Ls,pauli=True)

onsite_spins = [[J,i] for i in range(Ls)] 

static = [["-",onsite_spins]]

no_checks = dict(check_pcon=False,check_symm=False,check_herm=False)
H = hamiltonian(static,[],basis=basis,**no_checks)
print(np.matrix(H.toarray()))
```

This returns 
```
[[0.+0.j 0.+0.j]
 [2.+0.j 0.+0.j]]
```

**Comment by mgbukov** [comment]
This definition is OK; you have the choice to switch between other conventions for \sigma^{\pm} using the `pauli` argument, see 

http://weinbe58.github.io/QuSpin/generated/quspin.basis.spin_basis_1d.html#quspin.basis.spin_basis_1d

**Comment by HumpyBlumpy** [comment]
Ok I see.
Though I would personally make pauli=-1 the default at least, as that seem to me the more common convention.

**Comment by weinbe58** [comment]
@HumpyBlumpy we might consider that in the future, however we are keeping it the way it is for backward compatibility issues.
