### ISSUE TITLE
Renormalized hopping parameter

### ISSUE THREAD

**Issue by tarotene** [weinbe58/QuSpin#282]
I am a student doing my graduate research by using the QuSpin.

I am finding a way of implementing functions of any operator such as
\sum_{i, j} a^{\dagger}_{i} f(n_{i} - n_{j}) a_{j},
where f(x) is the function.

In other words, I want to modify the strength of interactions according to the value of several operators (in the above case, n_{i}).

This "renormalized" form of interaction emerges in, for example, the effective Hamiltonian of some periodically-driven quantum systems. I am very grateful if I could compare the results of the real-time dynamics of such driven systems and the effective one. Functions of the operator are needed for investigating the latter effective one.

Is there no other way to implement it than expanding the function into the series by hand?

**Comment by tarotene** [comment]
I will give a pull-request in parallel if I could implement such an extension and there is no way of doing this.

**Comment by mgbukov** [comment]
You should be able to do that by defining a custom operator string with the
user_basis class. However, passing the function f() to numba will be a bit
involved.

Have a look at the tutorial on the user_basis in the online quspin
documentation, as well as the examples how to use user_basis, to see how
that may work.

Marin

**Comment by tarotene** [comment]
Thanks so much!
I never expected to receive a reply from the expert...😨

I will try to use the user_basis class, but something series-expansion techniques seem to be needed.

**Comment by weinbe58** [comment]
My guess would be that the user_basis is the best way to go, modifying the current low-level code to make this work would be really involved and not optimal. 

Actually you could just write the function f() directly into the Op function in the user basis which will make the code very efficient. Of course, it is annoying that you have to change the code if f() changes, however, it should be a pretty easy modification.
