### ISSUE TITLE
Jordan-Wigner doubt

### ISSUE THREAD

**Issue by Stanley-Milgram** [weinbe58/QuSpin#287]
Hi,

I have a rather general issue which I am not entirely sure if it is code- or concept-related. I am currently studying MBL dynamics in Heisenberg-type chains, and I wanted to compare the results with a 'fermionized' version of my model (also to compare with some previous works that were done with fermionic models). Leaving the MBL part (random z-fields) aside, my model's backbone is given by the usual spin-1/2 XXZ hamiltonian for a 1d chain of L sites
![CodeCogsEqn (7)](https://user-images.githubusercontent.com/36376779/70809945-2a13f280-1dc3-11ea-99d8-55c4cb7c4788.png)
Please note that I am working in the 0 magnetization sector, i.e. half-filling in fermionic language.
Via Jordan-Wigner transformations (if my calculations are correct), it should be equivalent to the fermionic hamiltonian
![CodeCogsEqn (4)](https://user-images.githubusercontent.com/36376779/70809616-73b00d80-1dc2-11ea-9c89-8a2a5f6193b1.png)

In practice, my understanding is that in the language of QuSpin, the transformation simply amounts to define a new spinless fermion basis with the same symmetry properties and create a new static operator list to pass to hamiltonian() substituting 
- '+-' --> '+-' 
- 'zz' --> 'nn'

I used the following snippet of code to compare both the hamiltonian elements and the energy spectrum (kind of similar to what you guys do in your example on the TFI model). As you can see they are not matching. In particular, the diagonal elements of H_{XXZ} and H_{JW} are different. 

[XXZJW.txt](https://github.com/weinbe58/QuSpin/files/3961649/XXZJW.txt)

Even if I might have missed some factor of 2 or a minus here and there during the J-W calculations , I doubt it is just a parameter rescaling problem. Moreover, I was kind of surprised when I tried to calculate the *fermion* hamiltonian with 'zz' instead of 'nn' and not only it worked perfectly, but it actually gave the correct result. Probably, nothing I said sounds like a surprise or an issue to you and there is a simple explanation that I am missing. Also, in your Jordan-Wigner example, when you mapped the external z-field from the spin picture to the fermion picture, you used 'z' in both cases, which kind of confuses me: isn't the S^z ('z') operator mapping to the density operator n ('n')?

I apologise if something is not clear or if the answer is actually trivial.
Keep up with the great work

**Comment by mgbukov** [comment]
I think the problem is the relation: 'zz' --> 'nn' which is not quite true. 

According to the [Wikipedia article ](https://en.wikipedia.org/wiki/Jordan%E2%80%93Wigner_transformation) on Jordan-Wigner, the transformation for S^z is

S^z = 2 a^\dagger a - 1 (with a the fermion)

so if you want to use the "n" operator for fermions, you'd have to take into account the factors of 1/2, etc. Using the "z" opstr of the fermion basis is the easy way to keep track of these factors. 

Does this help?

**Comment by Stanley-Milgram** [comment]
Hi Marin, thanks for the reply. You're right, I did not notice that the 'z' operator in the fermion basis is conveniently defined as (c^\dagger c -1/2), which is the correct form of the J-W transformation. The model hamiltonians and spectrums are thus equivalent using 'zz' and not 'nn'. 

As a follow up, I know have some doubts about the inverse case, i.e. the J-W transform from a fermion hamiltonian to a spin one. Just for clarity, let's say I'd want to check the equivalence between the fermionic hamiltonian
![CodeCogsEqn (8)](https://user-images.githubusercontent.com/36376779/70835803-8c3e1900-1dfe-11ea-8b65-350f6c7373a1.png)
and the spin equivalent version, obtained inverting the J-W mapping. In that case the number operator n is given by n = c^\dagger_i c_i = 1/2 (\sigma_i^z +1), but the 'n' opstr is not defined in the spin basis. How could I take into account this additional 1/2 terms using the 'z' opstr in the spin basis? 

I guess there is an easy way to define customized operators of this type, but it could maybe be useful to have the opstr 'n' already implemented for the spin_basis module in the same way 'z' is already there for the fermion class?

**Comment by mgbukov** [comment]
There is no convenient shortcut for 'n' in the spin basis;

You'd have to add an extra term to the Hamiltonian to correct for it; note
that the identity operator has the opstr 'I'

Marin
