### ISSUE TITLE
symmetrical operator

### ISSUE THREAD

**Issue by Chapa1** [weinbe58/QuSpin#292]
Is it possible in QuSpin 
1) to construct the product of two operators?
2) to calculate the symmetric operator.
I consider the following problem:
Given two operators p and q, calculate the mean value of  :p^k q^{n-k}: for k=0,1..n.
Here ": :" stands for symmetric operator with respect to q and p.
For example, :qpp:=(qpp+ppq+pqp)/3

**Comment by weinbe58** [comment]
Hi @Chapa1 

yes quspin can construct products of operators so long as those operators are non-branching, so for your example if those are position and momentum operators you should express them as creation/annihilation operators instead. 

does that Answer your question?

Best,

Phil
