### ISSUE TITLE
Meaning of zA/zB symmetries

### ISSUE THREAD

**Issue by jaredjeya** [weinbe58/QuSpin#296]
Hi,

Thanks so much for developing this package, I just had a question about the zA/zB symmetries in spin_basis_1d.

The documentation for `**blocks` says:

> `zAblock` (int) - specifies spin inversion symmetry block for sublattice A.

> `zBblock` (int) - specifies spin inversion symmetry block for sublattice B

However, I can't find any definition for sublattices A & B in the documentation. I was wondering if they might be the even and odd sites, but they could just as well be the left and right halves of the chain or something else entirely, so I was hoping you could clarify this for me (and if possible stick a note in the documentation to make that clearer to others too!). I understand I could also use spin_basis_general to get the functionality I want, though.

Thanks for any help you can give!

**Comment by mgbukov** [comment]
The zA/zB symmetries refer to the even and odd sites of the 1d chain.

We put them long time ago in the code, before we had the general  basis
classes. The general basis classes allow you to define any arbitrary
discrete symmetry, ie to choose the sublattice yourself, which in turn
allows for different lattices/dimensionality.

We'll update the documentation with the new release.

Keep the feedback coming :), and let me know if you have any other
questions!

**Comment by mgbukov** [comment]
added a note about the definition of A/B sublattices in dev_0.3.4. Will appear with the next release.
