### ISSUE TITLE
SVD fails to converge

### ISSUE THREAD

**Issue by jsvandyke86** [weinbe58/QuSpin#297]
When calculating the entanglement entropy using the spin_basis_1d class, I've found that the SVD sometimes fails to converge:
    
  File "/home/jvandyke/anaconda3/envs/envquspin/lib/python3.7/site-packages/quspin/basis/base.py", line 382, in ent_entropy
    sparse=sparse,alpha=alpha,sparse_diag=sparse_diag,maxiter=maxiter)
  File "/home/jvandyke/anaconda3/envs/envquspin/lib/python3.7/site-packages/quspin/basis/lattice.py", line 319, in _ent_entropy
    p, rdm_A, rdm_B = self._p_pure(state,sub_sys_A,return_rdm=return_rdm)
  File "/home/jvandyke/anaconda3/envs/envquspin/lib/python3.7/site-packages/quspin/basis/lattice.py", line 432, in _p_pure
    U, lmbda, V = svd(v, full_matrices=False)
  File "<\_\_array_function\_\_ internals>", line 6, in svd
  File "/home/jvandyke/anaconda3/envs/envquspin/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 1636, in svd
    u, s, vh = gufunc(a, signature=signature, extobj=extobj)
  File "/home/jvandyke/anaconda3/envs/envquspin/lib/python3.7/site-packages/numpy/linalg/linalg.py", line 106, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")

Here's a simple example of a disordered-field Heisenberg model which exhibits the problem.  The SVD converges for some cases, but if you are doing lots of disorder realizations it is highly likely it will fail at some point in the calculation.

```
from quspin.basis import spin_basis_1d
from quspin.operators import hamiltonian
import numpy as np

N=10
J=1.0
delta = 10.5
basis = spin_basis_1d(L=N,a=1,pauli=0)

J_v = [ [J,i,i+1] for i in range(N-1)]
dB = 2.0*delta*np.random.random_sample(size=N)-delta
B_v = [ [dB[i],i] for i in range(N)]
static=[]
static.append(["xx",J_v])
static.append(["yy",J_v])
static.append(["zz",J_v])
static.append(["z",B_v])
ndisorder = 1000
for ndis in range(ndisorder):
    ham = hamiltonian(static,[],basis=basis,dtype=np.float_,check_herm=False,check_pcon=False,check_symm=False)
    eigvals, eigvecs =  ham.eigh()
    for i in range(2**N):
        basis.ent_entropy(eigvecs[:,i],sub_sys_A=tuple(range(N//2)),density=False,return_rdm='A',return_rdm_EVs=True)
    print("did disorder realization #",ndis)
    dB = 2.0*delta*np.random.random_sample(size=N)-delta
    B_v = [ [dB[i],i] for i in range(N)]
    static[-1] = ["z",B_v]
```

This is certainly an issue with numpy, which supplies the SVD function for lattice.py, as opposed to a bug in quspin.  However, I noticed that the scipy version of SVD is actually different than the numpy version.  In particular, the scipy version allows you to choose between two different algorithms for computing the svd, one of which is potentially more stable (but slower).  I was wondering if it might be useful to switch over to the scipy version, so that this other svd could be used in situations where the first algorithm fails.  Some further information about the two methods is discussed in the following github comment: https://github.com/numpy/numpy/issues/1588#issuecomment-9688409 .  Thanks for developing this great package!

**Comment by mgbukov** [comment]
It certainly makes sense to add the option for the user to choose whether
to use numpy or scipy SVD, If there are no issues with this.

One difference, if I remember correctly, is that numpy's svd allows for
parallelization (ie it accepts a 3d array) while scipy's doesn't. B

**Comment by mgbukov** [comment]
@jsvandyke86 I tried out the scipy.linalg.svd solver on your example and it failed too.

```
 p, rdm_A, rdm_B = self._p_pure(state,sub_sys_A,svd_solver,svd_kwargs,return_rdm=return_rdm)
  File "/Users/mgbukov/quspin/./Quspin_dev/quspin/basis/lattice.py", line 446, in _p_pure
    U, lmbda, V = svd_solver(v, **svd_kwargs) # full_matrices=False
  File "/Users/mgbukov/miniconda3/lib/python3.7/site-packages/scipy/linalg/decomp_svd.py", line 132, in svd
    raise LinAlgError("SVD did not converge")
numpy.linalg.linalg.LinAlgError: SVD did not converge
```

Scipy probably calls the same svd solver under the hood. Are you sure you didn't just get lucky when you tried this out?

**Comment by jsvandyke86** [comment]
@mgbukov I believe the default LAPACK driver for the svd is the same for both numpy and scipy, namely gesdd.  However, scipy lets you switch to an alternative driver, gesvd.  When I chose that one instead of the default, all my subsequent calculations have worked thus far.

`U, lmbda, V = scipysvd(v[0,:,:], full_matrices=False,lapack_driver='gesvd')`

Were you using the default scipy svd driver or gesvd?

**Comment by mgbukov** [comment]
@jsvandyke86 yes, I was using the default solver. Indeed, 'gesvd' works much nicer. 

I added this feature in a new branch, called s_ent_svd. The tests seem to pass, so if eerything is ok, this option will be available with the next quspin release.

**Comment by jsvandyke86** [comment]
Cool, thanks!
