### ISSUE TITLE
possibly a bug in quantum_LinearOperator

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#302]
currently, in `dev_0.3.4`, there are a few instances of `self.diagonal` in quantum_LinearOperator.py, cf. lines 309,210,776. 

@weinbe58 I think they have to be `self._diagonal`, i.e. an underscore is missing. If yes, let's fix it before the next release.

**Comment by weinbe58** [comment]
There is a property called `diagonal` that should be defined. I did have this bug awhile ago and I since have fixed it.
