### ISSUE TITLE
reduced density matrix for spin-up/down fermions

### ISSUE THREAD

**Issue by Chapa1** [weinbe58/QuSpin#304]
Hello, 
Could you please tell me the way to obtain the reduced density matrix of spin up/down fermions.
Below you can find the snippet, in which the wave function of the system 'psi' is constructed.

```
from quspin.operators import hamiltonian
from quspin.basis import spinful_fermion_basis_1d
import numpy as np

L=6 
J=1.0 

basis=spinful_fermion_basis_1d(L=L,Nf=(int(L/2-1),1)) 

H_pm=[[-J,i,(i+1)] for i in range(L-1)] 
H_mp=[[+J,i,(i+1)] for i in range(L-1)] 
static=[["+-|",H_pm],["-+|",H_mp]]
H = hamiltonian(static,[],dtype=np.float64,basis=basis)

#print(basis)
_,psi=H.eigsh(k=1, which='SA') 
```
The corresponding hilbert space dimensions are 15 and 6.
1. How one can obtain two density matrces 15x15 and 6x6?
2. why subsystems for spin-up and down fermions are constructed like that?
```
sub_sys_A_up=range(basis.L//2) # subsystem for spin-up fermions
sub_sys_A_down=range(basis.L//2+1) # subsystem for spin-down fermions

```
http://weinbe58.github.io/QuSpin/generated/quspin.basis.spinful_fermion_basis_1d.html?highlight=partial%20trace#quspin.basis.spinful_fermion_basis_1d.partial_trace

Thank you.

**Comment by weinbe58** [comment]
Are you trying to trace out just the up/down spins?

**Comment by Chapa1** [comment]
@weinbe58  yes, I want obtain the density matrices for only spin-up fermions and spin-down.

**Comment by weinbe58** [comment]
OK, in that case, the input argument sub_sys_A is split up into a tuple of lists. the sites for the up-electrons and the sites for the down electrons. If you do not wish to trace out any sites containing the up-electrons then that list should be empty and vice-versa for the down electrongs.

Note that the resulting density matrix will not be in the particle reduced basis, this is a feature we have thought about working on in the future.

One work around for this would be to do the following:

1. create a tensor_basis object with two spinless fermions to represent the up and down sectors.
2. using the spinful fermion basis, call getvec with particle conservation argument set to be true.
3. use the partial_trace method for the tensor basis to trace either the "left" or "right" basis which represents your "up" and "down" sectors respectively.

**Comment by Chapa1** [comment]
Thank you very much!
It seems it works. Below there is the snippet where I left out 2nd point (using spinful basis).
```
from quspin.operators import hamiltonian 
from quspin.basis import tensor_basis,spinless_fermion_basis_1d,spinful_fermion_basis_1d
import numpy as np

L = 6 
J = 1.0

basis_up = spinless_fermion_basis_1d(L,Nf=int(L/2-1)) 
basis_down = spinless_fermion_basis_1d(L,Nf=1)
basis_tensor = tensor_basis(basis_up,basis_down)

H_pm=[[-J,i,(i+1)] for i in range(L-1)] 
H_mp=[[+J,i,(i+1)] for i in range(L-1)] 
static=[["+-|",H_pm],["-+|",H_mp]]
H = hamiltonian(static,[],dtype=np.float64,basis=basis_tensor)

_,psi=H.eigsh(k=1, which='SA')

rho1,rho2=basis_tensor.partial_trace(psi,sub_sys_A='left',return_rdm='both')

print(len(rho1),len(rho2))
```
Is the 2nd point is necessery for large systems, i.e. computationally preferable that the way using spinfull basis to get psi?

I tried this one
```
basis_spinfull=spinful_fermion_basis_1d(L=L,Nf=(int(L/2-1),1)) 
H = hamiltonian(static,[],dtype=np.float64,basis=basis_spinfull)
_,psi=H.eigsh(k=1, which='SA')

psi_full=basis_spinfull.get_vec(psi,pcon=True)
```
it gives Error: 'NotImplementedError: Optional argument pcon will be implemented in a future version.' 
whereas 

```
psi_full=basis_spinfull.get_vec(psi)
rho1,rho2=basis_tensor.partial_trace(psi_full,sub_sys_A='left',return_rdm='both')
```
gives 'ValueError: state shape (4096, 1) not compatible with Ns=90'

**Comment by weinbe58** [comment]
oh I see the issue is you're using the 1d versions of the basis classes. I would suggest that you use the spinful_fermion_basis_general object instead.

**Comment by mgbukov** [comment]
@Chapa1 did this resolve the problem?
