### ISSUE TITLE
particle-hole symmetry:

### ISSUE THREAD

**Issue by aliemami94** [weinbe58/QuSpin#305]
How can I create a "spinless_fermion_basis_1d" with U(1) symmetry?

When I use this code :
basis=spinless_fermion_basis_1d(L=L,phblock)
make the Erorr:
ValueError: unexpected optional argument(s): phblock

thank you!

**Comment by weinbe58** [comment]
Hello,

The particle-hole symmetry is not implemented for the spinless_fermion_basis_1d but is possible to implement using the spinless_fermion_basis_general class. Read more about that [here].(http://weinbe58.github.io/QuSpin/generated/quspin.basis.spinless_fermion_basis_general.html#quspin.basis.spinless_fermion_basis_general)

**Comment by mgbukov** [comment]
@aliemami94  did this resolve the issue?

**Comment by aliemami94** [comment]
Dear Marin,
Thank you for your support.
Yes, my problem solved.
