### ISSUE TITLE
semi-momentum states: parity and translation in basis_1d

### ISSUE THREAD

**Issue by wenya-r** [weinbe58/QuSpin#311]
I think there’s a bug in the parity symmetry basis construction in the present of kblock symmetry when kblock != 0.  In the following example,

L = 12
k = 1
p = 1
basis = spin_basis_1d(L, pauli = False, S = '1', m=0, kblock = k, pblock = p)

of Heisenberg model with periodic boundary condition, I got exactly the same eigenvalues for both p = 1 and p = -1. This is not quite possible to have both parity generating the same energy spectrum. Moreover if I remove k and  and parity symmetry, i.e. with   

basis = spin_basis_1d(L, pauli = False, S = '1', m=0)

I don’t observe any degeneracies that are present in +1 and -1 parities. Therefore I suspect there's a bug in the construction of the basis with k and p symmetries. Please let me know if you need more information. Thank you.

**Comment by mgbukov** [comment]
@wenya-r can you post the complete code, also the construction of the model and the eigenvalues?

**Comment by weinbe58** [comment]
I don;t see any issues with the higher spin. Below I have an example that calculates the full spectrum with and without the use of symmetries and they match to machine precision. We even see this degeneracy between the parity sectors and we also observe the degeneracy in the full spectrum as well. 

Could you post an example of your code that reproduces your results?

```
from __future__ import print_function, division
import sys,os
from quspin.operators import hamiltonian # Hamiltonians and operators
from quspin.basis import spin_basis_1d # Hilbert space spin basis
import numpy as np # generic math functions

def get_spectrum(basis):
	Jxy=np.sqrt(2.0) # xy interaction
	Jzz_0=1.0 # zz interaction
	hz=1.0 # z external field
	L = basis.N


	J_zz = [[Jzz_0,i,(i+1)%L] for i in range(L)] # OBC
	J_xy = [[Jxy/2.0,i,(i+1)%L] for i in range(L)] # OBC

	static = [["+-",J_xy],["-+",J_xy],["zz",J_zz]]
	dynamic=[]

	H_XXZ = hamiltonian(static,dynamic,basis=basis,dtype=np.float64)
	return H_XXZ.eigvalsh()

S="1"
L=8 # system size

basis_full = spin_basis_1d(L,S=S,m=0.0)
E_full = get_spectrum(basis_full)

E = []
# calculate eigenvalues for each sector. semi-momentum states implies that you make 
# linear combinations of +/- k and so you do not need to do all values of momentum. 
for k in range(0,L//2+1):
	for p in [-1,1]:
		basis = spin_basis_1d(L,S=S,m=0.0,kblock=k,pblock=p)
		e = get_spectrum(basis)
		print(k,p,e)
		E.append(e)


# concatenate and sort by value. 
E = np.hstack(E)
E.sort()
print(E_full)
print(np.linalg.norm(E_full-E))
```

**Comment by wenya-r** [comment]
OK. I got it. I missed the semi-momentum part. I though I needed to iterate k from 0 to L-1. Thank you so much!

**Comment by mgbukov** [comment]
We will add later on an example to discuss semi-momentum states which will include:

1) single-particle example to show linear combination of \pm k modes, except k=0,\pi
2) show that the sum over k blocks should go to L//2
3) show that there is no reduction in the H-space size but there's a gain in memory from complex to real numbers in the Hamiltonian. 
4) mention that the general basis does not support semi-momentum states, and no error is thrown, only a warning
