### ISSUE TITLE
There's no (compiled) 0.34 build available for Windows

### ISSUE THREAD

**Issue by jaredjeya** [weinbe58/QuSpin#316]
I was trying to update QuSpin to version 0.34 (as some of the features look quite useful) and I've found that there doesn't seem to be a 0.34 version available for windows - but it is available for linux.

See: [win-64](https://conda.anaconda.org/weinbe58/win-64) vs [linux-64](https://conda.anaconda.org/weinbe58/linux-64) repositories. The 0.34 version is missing from the win-64 respository for some reason.

I'm working remotely right now, connecting to a Linux machine from a Windows laptop. So I'm writing the code on a Windows machine, testing it, then pushing it to the Linux machine to run it on something that can actually handle more substantial calculations. I'd already updated the Linux version when I discovered I couldn't update the Windows version for some reason, and would quite like to use some of the new features available. 

I'd rather not do a manual install+compile as I'd probably get it horribly wrong - do you know when a win-64 version will be available for install?

**Comment by weinbe58** [comment]
Thanks for pointing this out, it should be fixed now.
