### ISSUE TITLE
Possible bug in Particle-hole symmetry for general basis

### ISSUE THREAD

**Issue by weinbe58** [weinbe58/QuSpin#320]
There is possibly a bug in the *_fermion_basis_general classes when using the particle-hole symmetry. 

Consider the simple hamiltonian: c^\dagger_0 c_1 + c^\dagger_2 c_3 + h.c. 

This Hamiltonian clearly obeys particle-hole symmetry but QuSpin is returning a non-symmetric matrix for both the symmetric and anti-symmetric sectors of particle-hole symmetry:

```python
from quspin.basis import spinless_fermion_basis_general
from quspin.operators import hamiltonian
import numpy as np

nuc = 2 # number of unit cells
L = 2*nuc
Nf = nuc

i = np.arange(L)
h = -(i+1)


pm_list = [[+1.0,2*i,2*i+1] for i in range(nuc)]
mp_list = [[-1.0,2*i,2*i+1] for i in range(nuc)]

static = [["+-",pm_list],["-+",mp_list]]


basis_symm = spinless_fermion_basis_general(L,Nf=Nf,hblock=(h,0))
basis_asymm = spinless_fermion_basis_general(L,Nf=Nf,hblock=(h,1))

for basis in [basis_symm,basis_asymm]:
	H = hamiltonian(static,[],basis=basis,dtype=np.float64)
	print(H.toarray())
```
I am missing something here @mgbukov?

**Comment by mgbukov** [comment]
I think this is a bug indeed. I compared your code snippet to the `spinful_fermions_basis_general` with advanced functionality.

For the time being, the users can use `spinful_fermions_basis_general`. 

The bug seems to not occur fir odd number of units cells. Interestingly, for `nuc=3`, the matrices produced by the two bases classes differ in some signs, so if the sign convention is the same for both bases, the issue might be with the signs.

```
from quspin.basis import spinless_fermion_basis_general, spinful_fermion_basis_general
from quspin.operators import hamiltonian
import numpy as np

nuc = 2 # number of unit cells
L = 2*nuc
Nf = L//2 # nuc

i = np.arange(L)
h = -(i+1)


pm_list = [[+1.0,i,(i+1)%L] for i in range(L)]
mp_list = [[-1.0,i,(i+1)%L] for i in range(L)]

static = [["+-",pm_list],["-+",mp_list]]

basis_symm  = spinless_fermion_basis_general(L,Nf=Nf,hblock=(h,0))
basis_asymm = spinless_fermion_basis_general(L,Nf=Nf,hblock=(h,1))

for basis in [basis_symm,basis_asymm]:
	H = hamiltonian(static,[],basis=basis,dtype=np.float64)
	print(H.toarray())

	print( np.linalg.norm( (H-H.H).toarray() ))



####################


N_up = L//2
N_down = 0

s = np.arange(2 * L)

t_x = (s+1)%L 
S = -(s + 1)


pm_list = [[+1.0,i,t_x[i]] for i in range(2*L)]
mp_list = [[-1.0,i,t_x[i]] for i in range(2*L)]

static = [["+-",pm_list],["-+",mp_list]]


basis_symm = spinful_fermion_basis_general(L, simple_symm=False, Nf=(N_up, N_down), sblocks=(S, 0))
basis_asymm = spinful_fermion_basis_general(L, simple_symm=False, Nf=(N_up, N_down), sblocks=(S, 0))

for basis in [basis_symm,basis_asymm]:
	H = hamiltonian(static,[],basis=basis,dtype=np.float64)
	print(H.toarray())

	print( np.linalg.norm( (H-H.H).toarray() ))
```

**Comment by weinbe58** [comment]
That's odd that it works for spinful fermions because it uses the exact same code as spinless fermions. 

right now I am trying to work out the matrices by hand for this example with two unit cells.

**Comment by weinbe58** [comment]
The problem with your example is that the particle-hole symmetry transforms the vacuum of the down electrons and it seems to make the symmetry work, It seems when you transform only the up electrons the bug reappears again. 

The bug seems to act like we're missing operators that are required to make the Hamiltonian obey the symmetry.

**Comment by weinbe58** [comment]
Another interesting observation is that when `nuc` is odd, the bug goes away.

**Comment by mgbukov** [comment]
Interesting, so the problem must be with the signs. I guess for the spinful
fermions the second species introduces a second copy of the wrong sign so
it's ok again.

For free spinless fermions we can use Jordan Wigner to get spins, and there
we get a Hamiltonian which obeys z-symmetry. The basis states for the spins
and spinless fermions are the same, so maybe the Jordan Wigner on a small
system can help us figure out why the signs are wrong?

Marin

**Comment by weinbe58** [comment]
I think I figured out the issue. The issue is that we're assuming that the fock-states change sign under the PH transformation. The problem is that I don't think they do. The reason is the following: When you transform the fock-state the PH transformation does indeed change all the creation operators to annihilation operators, however, the PH transformation also transforms the vacuum state to be the fully occupied state. Now the given state is not in canonical form and I assert that when taking the state to canonical form the signs from the PH transformation cancels out because I have to commute all of those annihilation operators through the creation operators that are filling the new vacuum state. the sign that gives picked up in this operator exactly cancels the sign that is given by the PH transformation on the original creation operators. 

Does this make sense?

**Comment by weinbe58** [comment]
@mgbukov So I think I figured out something else. It is true that some of the signs cancel after doing the PH transformation as described above, however, there is an extra sign left over which is (-1)^{Np*(N-1)} where Np are the number of particle before the PH transformation and N is the number of sites. I think this might explain why spinful fermsions did not have this issue, in that case if we choose spin-up and spin-down to have the same density Np is always even and so the sign is positive for all fock states after the PH transformation, just like you pointed out in a previous comment. 

related to the example Np = nuc and N = 2*nuc so the phase is (-1)^{nuc*(2*nuc-1)}

**Comment by mgbukov** [comment]
Here's an example on 3 sites which supports your statement above: the Fock states do _not_ change sign under PH.

```
|110> = c^H_0 c^H_1 |000> --> c_0 (-c_1) |111> = - c_0 c_1 c^H_0 c^H_1 c^H_2 |000> = + c_0 c^H_0 * c_1 c^H_1 * c^H_2 |000> = +(1 - c^H_0 c_0) * (1 - c^H_1 c_1) * c^H_2 |000> = c^H_2 |000> = +|001>
```

Here's a four-site example

```
|1001> = c^H_0 c^H_3 |0000> --> c_0 (-c_3) |1111> = - c_0 c_3 c^H_0 c^H_1 c^H_2 c^H_3 |0000> = +  c_0 c^H_0 * c^H_1 c^H_2 * c_3 c^H_3 |0000> = (1 - c^H_0 c_0) * c^H_1 c^H_2 * (1 - c^H_3 c_3) |0000> = +|0110> 
```

and two more:

```
|1101> = c^H_0 c^H_1 c^H_3 |0000> --> c_0  (-c_1) (-c_3) |1111> = + c_0 c_1 c_3 c^H_0 c^H_1 c^H_2 c^H_3 |0000> = + c_0 c^H_0 * c_1 c^H_1 * c^H_2 * c_3 c^H_3 |0000> = +|0010>
```

```
|1111> = c^H_0 c^H_1  c^H_2 c^H_3 |0000> --> c_0  (-c_1) c_2 (-c_3) |1111> = + c_0 c_1 c_2 c_3 c^H_0 c^H_1 c^H_2 c^H_3 |0000> = - c_0 c^H_0 * c_1 c_2 c_3 c^H_1 c^H_2 c^H_3 |0000> = - c_0 c^H_0 * c_1 c^H_1 * c_2 c_3 c^H_2 c^H_3 |0000> = +c_0 c^H_0 * c_1 c^H_1 * c_2 c^H_2 * c_3 c^H_3 |0000> = + |0000>
```

I think the general proof is a matter of proper bookkeeping.

**Comment by weinbe58** [comment]
cool, let me try to change the code to reflect this fact and we can see if there is still a bug.

**Comment by weinbe58** [comment]
I ran the example in the original post after removing the sign change and now it looks like the problem is resolved!
