### ISSUE TITLE
Python not finding quspin after anaconda installation

### ISSUE THREAD

**Issue by Babyll** [weinbe58/QuSpin#321]
I ran the anaconda terminal and ran the line of code `conda install -c weinbe58 quspin`. When I check my packages on anaconda by running `conda list`, it shows quspin as being installed. However, when I go run python from that same conda terminal and run the line `help('modules')`, it doesn't show quspin in the list of modules. Further, when I run `from quspin.operators import hamiltonian `, it says `ModuleNotFoundError: No module named 'quspin'`. What am I doing incorrectly? I should mention, this is on Windows.

**Comment by weinbe58** [comment]
What version of python are you running?

**Comment by Babyll** [comment]
I'm running python 3.7.6 through the conda terminal.

**Comment by Babyll** [comment]
I should add that when I run pycharm through anaconda, I can see the packages available for the project I created. It lists quspin as one of the packages (when I check under settings -> Python Interpreter). However, running `from quspin.operators import hamiltonian ` still returns "module quspin not found"

**Comment by Babyll** [comment]
Has anyone had the chance to look at this?

**Comment by mgbukov** [comment]
Yes, we've been having trouble with Windows installations throughout. 

Have you tried installing quspin 0.3.3? I wonder if this issue was introduced with version 0.3.4.

**Comment by Babyll** [comment]
Hi, sorry for my ignorance, but is there an easy set of commands I can run to try and install 0.3.3 on windows? Or would I need to compile it from scratch?

**Comment by weinbe58** [comment]
I reproduced the bug on my machine. One thing to try is to install the openmp enabled version:

```
>conda install -c weinbe58 quspin omp
```
This works on my computer.

**Comment by weinbe58** [comment]
@mgbukov I believe something was messed up for the windows' build specifically with the python 3.7 non-omp version. I am going to rebuild all the versions and reupload them as build 1.

**Comment by mgbukov** [comment]
@weinbe58 if you think this may also affect the osx version, I can re-build them too.

**Comment by weinbe58** [comment]
No I think this is a windows issue, specifically if you look at the size of the python 3.7 version of quspin on anaconda cloud the file size if 5 kb not 15 MB.

**Comment by Babyll** [comment]
Oh great, the omp version works for me as well!

**Comment by weinbe58** [comment]
I have uploaded a new build so both should be working now.
