### ISSUE TITLE
Set up initial state for fermionic system

### ISSUE THREAD

**Issue by Chapa1** [weinbe58/QuSpin#326]
Dear QuSpin developers!

I consider a 1D spinless fermionic system which consists of two parts: L and R.
How is it possible to construct an initial state such that L is fully occupied and R is empty?

Thank you for you help!

**Comment by mgbukov** [comment]
check out the basis methods: `basis.index()`, `basis.int_to_state`, and `basis.state_to_int`.

**Comment by Chapa1** [comment]
Thank you for the answer. The state I am asked has index=0.

I would like to clarify some point:
The hamiltonian I consider has two drivings. Is it true that the following pattern is correct?  

```
hop1=[[1.0,L-1,L]] 
hop2=[[-1.0,L-1,L]] 
dynamic=[["+-",hop1,drive1,drive_args],["-+",hop2,drive2,drive_args]] 
```

**Comment by weinbe58** [comment]
Hi @Chapa1, 

that looks almost correct, however, I would worry that if your system size is `L` then the site index will fall outside of the system. If you want to drive the last two sites I would use `L-2` and `L-1` for the second to last and last sites respectively.

**Comment by Chapa1** [comment]
Hello @weinbe58,
thank you. 
the system size is 2*L.
