### ISSUE TITLE
importing quspin fails with 'ModuleNotFoundError: No module named 'numba.ccallback''

### ISSUE THREAD

**Issue by zoome0215** [weinbe58/QuSpin#327]
Dear developers,
I cannot import `quspin` it's saying that `No module named 'numba.ccallback'`

QuSpin version
Version that is installed with the command `conda install -c weinbe58 quspin` as of 26.05.2020.

Environment 
`conda 4.8.3`
`Python 3.7.7`
`numpy 1.18.1`
`numba 0.49.1`
`scipy 1.4.1

minimum code to recreate this issue:
On console
```
import quspin
```
The last line of the stack trace
```
    from .user_core import user_core_wrap
  File "quspin/basis/basis_general/_basis_general_core/user_core.pyx", line 6, in init quspin.basis.basis_general._basis_general_core.user_core
ModuleNotFoundError: No module named 'numba.ccallback'
```

**Comment by zoome0215** [comment]
Duplicate of #319

**Comment by zoome0215** [comment]
Install older version of numba (preferablly 0.48.0) by
`conda install numba=0.48.0`

**Comment by weinbe58** [comment]
I'm closing this duplicate issue.
