### ISSUE TITLE
Electron-Phonon Coupling with QuSpin

### ISSUE THREAD

**Issue by mbsilvaneto** [weinbe58/QuSpin#334]
Hi there, 

I am trying to make hopping, spinful electrons in 1D couple to phonons. My first attempt was to construct a TRIPLE basis 

basis = photon_basis(spinful_fermion_basis_1d,Nf=(L//2,L//2),L=L,Nph=Nph)

and it does create a nice TRIPLE up_spin x down_spin x phonon. For example, with L=2 and Nph=50 (a two-site toy model) with 50 phonons I get terms like |10>|01>|7> for one up_spin electron on site 1, one down_spin electron on site 2, together with 7 phonons.

Now, my problem is how to create a static list for the electron-phonon coupling Hamiltonian with a TRIPLE basis? Usually, with a DOUBLE basis one uses masks such as  '+|-' or 'n|n'. For my TRIPLE basis, if I try to use something like '+|-|n' I get the message "too many terms to unmask". 

Any suggestions as to how to construct a Hamiltonian that couples electrons to phonons?

I appreciate any help!!!
Cheers

**Comment by weinbe58** [comment]
Hi, so sorry for the delayed response.

Are you trying to couple fermions to a single phonon mode or dispersive phonons?

**Comment by mbsilvaneto** [comment]
Hi Steve, no problem.. I was kind in a hurry and ended up writing my own
code to build up the Hamiltonian, and then used numpy.linalg.eigh()

I wanted to couple eletrons to two kinds of localized, optical phonons (non
dispersive) and with QuSpin I could not figure out how.

By the way.. nice platform you guys have built.. congrats

Cheers
Marcello

Em seg, 27 de jul de 2020 12:55, Phillip Weinberg <notifications@github.com>
escreveu:

**Comment by weinbe58** [comment]
Sorry about that, but I wish you luck in your project! Thank you for trying out our code!
