### ISSUE TITLE
Expt_value treats up spin different from down spin

### ISSUE THREAD

**Issue by AbdallahAlShafey** [weinbe58/QuSpin#335]
I've tried to calculate the expectation value of non-Hermitian operators using the obs_vs_time function but then switched to expt_value after reading issue #225. I'm now facing a new glitch which is that the expectation value is slightly different for up spins versus down spins even though everything in the problem is symmetric in spin. Here is my Hamiltonian:
![ham](https://user-images.githubusercontent.com/50179743/87431193-4aec3280-c5b4-11ea-8b9b-d993a2ccee6e.PNG)
Here's a plot of left hopping expectation values for spin up versus for spin down:
![spin up vs spin down left hopping](https://user-images.githubusercontent.com/50179743/87430740-a2d66980-c5b3-11ea-8791-e1b0dc824ef7.png)

**Comment by mgbukov** [comment]
can you upload/post a minimal script which reproduces the issue? We'll try
to have a look when we get the chance.

**Comment by AbdallahAlShafey** [comment]
from quspin.operators import hamiltonian, exp_op, quantum_operator
from quspin.basis import spinful_fermion_basis_1d
from quspin.tools.measurements import obs_vs_time
import numpy as np
from scipy.sparse.linalg import eigsh
import matplotlib.pyplot as plt
L = 8
N_up = L // 2
N_down = L // 2
t0 = 0.52
factor = 1. / (t0 * 0.036749323)
a = (4 * 1.889726125) / factor
F0 = 10.* 1.944689151e-4 * (factor ** 2)
field = 32.9 * factor * 0.0001519828442
freq = field / (2. * 3.14159265359)

dynamic_args = []

def expiphi(current_time):
    phi = (a * F0 / field) * (np.sin(field * current_time / (2. * cycles)) ** 2.) * np.sin(
        field * current_time)
    return np.exp(1j * phi)

def expiphiconj(current_time):
    phi = (a * F0 / field) * (np.sin(field * current_time / (2. * cycles)) ** 2.) * np.sin(
        field * current_time)
    return np.exp(-1j * phi)

cycles = 10
n_steps = 2000
start = 0
stop = cycles / freq
times, delta = np.linspace(start, stop, num=n_steps, endpoint=True, retstep=True)

basis = spinful_fermion_basis_1d(L, Nf=(N_up, N_down))

static_Hamiltonian_list = []

hop_right = [[1, i, (i + 1) % L] for i in range(L)]  # hopping to the right, down spin OBC
hop_left = [[-1, i, (i + 1) % L] for i in range(L)]  # hopping to the left, up spin OBC
dynamic_Hamiltonian_list = [
            ["+-|", hop_left, expiphiconj, dynamic_args],  # up hop left
            ["-+|", hop_right, expiphi, dynamic_args],  # up hop right
            ["|+-", hop_left, expiphiconj, dynamic_args],  # down hop left
            ["|-+", hop_right, expiphi, dynamic_args],  # down hop right
        ]
ham = hamiltonian(static_Hamiltonian_list, dynamic_Hamiltonian_list, basis=basis, dtype=np.complex128)

operator_dict = dict(H=ham)

no_checks = dict(check_pcon=False, check_symm=False, check_herm=False)
operator_dict["lhopup"] = hamiltonian([], [["+-|", hop_left, expiphiconj, dynamic_args]], basis=basis, dtype=np.complex128, **no_checks)
operator_dict["lhopdown"] = hamiltonian([], [["|+-", hop_left, expiphiconj, dynamic_args]], basis=basis, dtype=np.complex128, **no_checks)
E, psi_0 = ham.eigsh(k=1, which='SA')
psi_t = ham.evolve(psi_0, 0.0, times)
psi_t = np.squeeze(psi_t)

expectationslu = operator_dict["lhopup"].expt_value(psi_t, time=times)
expectationsld = operator_dict["lhopdown"].expt_value(psi_t, time=times)

plt.plot(times, expectationslu.imag, times, expectationsld.imag)
plt.show()

**Comment by mgbukov** [comment]
Notice first that the mismatch occurs at time=0, so the time evolution
plays no role, so the problem is not caused by the dynamic part of the
Hamiltonian.

My guess is that because your system has a highly degenerate ground-state
manifold with some states corresponding to the spin-up and others to the
spin-down sector, the spin-up and spin-down sectors get mixed in the state
returned by the eigsh() solver. If this is correct, the issue is that the
state psi_0 does not obey the spin exchange symmetry, it's not caused by
the function expt_value().

**Comment by AbdallahAlShafey** [comment]
That makes a lot of sense, thanks! I should mention that this problem does not arise when L = 10.
