### ISSUE TITLE
Spinful fermion basis doubt 

### ISSUE THREAD

**Issue by shaktiimaan** [weinbe58/QuSpin#337]
Dear Code Developer 

I was implementing spinful fermion basis for my simple Hamiltonian. But it seems I am not getting correct matrix elements. 
I considered very simple L=2 site system  and H=(c †↑ c ↓ − c↑c †↓).
While running the code I am getting (0,3) matrix element to be negative one (-1). 
But I should get it to be +1.
Can you explain where I am making mistake or there is bug in basis, implementation.
If you don't understand my question, let me know
Below is my simple code.
Thanks

`import sys,os
quspin_path = os.path.join(os.getcwd(),"../../")
sys.path.insert(0,quspin_path)
##########################################################################
from quspin.basis import spinful_fermion_basis_general
import quspin.basis
from quspin.operators import hamiltonian
import numpy as np
###### define model parameters ######
L=2
###### setting up bases ######
basis_2d=spinful_fermion_basis_general(L,double_occupancy=False)
print(basis_2d)
###### setting up hamiltonian ######
a = [[1,i,i] for i in range(L)]
b = [[-1,i,i] for i in range(L)]
print(a,b)
static=[["+|-",a],["-|+",b]] # spin up hops to right
H=hamiltonian(static,[],basis=basis_2d,dtype=np.float64)
print(H)`

**Comment by weinbe58** [comment]
Hello,

I understand your question, why is it that you think (0,3) should be -1? As far as I can tell this is correct. To see why, you can treat the up and down spins as sites instead of species of fermion. In this picture, when I flip an up fermion to a down fermion is actually hopping a fermion from one site to another. That action in this case has the hopping fermion hop over another particle on the lattice resulting in a negative sign. Does this make sense?

**Comment by amancondmattheory** [comment]
Thank you for the response. Can you have a look at my small fermion algebra. There I am explaining the positive sign of matrix element.   Please clarify my mistake.
Thanks
[document.pdf](https://github.com/weinbe58/QuSpin/files/4982830/document.pdf)

**Comment by weinbe58** [comment]
You're Fock states do not make sense, you have to keep the ordering of the creation operators in the Fock basis consistent. In this document, state |3> does not have a consistent ordering. If you reorder the creation operators to be $c_1^\dagger c_2^\dagger$ you get the same result quspin gives.

**Comment by amancondmattheory** [comment]
Now I understand, Make me correct if wrong, your Fock space states are written in a certain ordering style such that all up spin creation operators are on left and and down spin creation operators are on right side. 

So to understand better for L=3 case
would  this state |0 0 1>|1 1 0>  be   $c_1_{up}^\dagger c_2_{down}^\dagger c_3_{down}^\dagger$

or  it would be  $c_1_{up}^\dagger  c_3_{down}^\dagger c_2_{down}^\dagger$

I feel fock space basis should be ordered in a site dependent, like  c_{N}^\dagger  c_{N-1} ^\dagger. ... c_1^\dagger.

Thanks

**Comment by weinbe58** [comment]
I do not remember which order we choose for the code, I know we choose it to make it easy to calculate the signs numerically. I know that the order of the states does not matter you will get the same results as long as you keep it consistent.

**Comment by amancondmattheory** [comment]
It was just to confirm my matrix elements are correct or not.  In addition, I might need these basis information while evaluating expectation values or some other quantity from eigenvectors , separately without using quspin.

Thanks

**Comment by amancondmattheory** [comment]
Is there a way to print all the basis states. Meaning while printing the basis states it prints only first few and last with dot dot in middle.
Otherwise can I get to know the bit representation of a state by providing the index in spin full fermion basis.

Thanks
