### ISSUE TITLE
spinful fermion entanglement entropy error 

### ISSUE THREAD

**Issue by shaktiimaan** [weinbe58/QuSpin#338]
Dear Code Developers 

I am trying to compute entanglement entropy for subsystem in a spinful sermonic system, considering number of sites to be L=8. I am getting an unusual error saying 

"" File "/anaconda3/envs/quspin/lib/python3.7/site-packages/quspin/basis/lattice.py", line 282, in _ent_entropy
    raise ValueError("sub_sys_A must iterable of integers with values in {0,...,N-1}")
ValueError: sub_sys_A must iterable of integers with values in {0,...,N-1}  "" 

Here is small code where I am using en_entropy subroutine.

`sub_sys_A_up=[0,1,2] # subsystem for spin-up fermions
sub_sys_A_down=[0,1,2] # subsystem for spin-down fermions
subsys_A=(sub_sys_A_up,sub_sys_A_down)
Sent=basis_2d.ent_entropy(ww,sub_sys_A=subsys_A)
print(Sent)`

Thanks

**Comment by weinbe58** [comment]
are you using the option: `simple_symm=False` when making your basis?

**Comment by shaktiimaan** [comment]
No, I am not using this option simple_symm.
N_2d=10
basis_2d=spinful_fermion_basis_general(N_2d,Nf=(3,3),double_occupancy=False)

where my particle density is just 6 and 10 sites. 

thanks

**Comment by shaktiimaan** [comment]
I have another question, 
Can I construct basis using QuSpin with particles density less than N(which is number of site), with double occupancy, without conserving N_up and N_down. 
For example 
N=10
and n=\sum_i(􏰀c†i↑ci↑ + c†i↓ci↓)=6,    without double occupancy.
And also I don't want to use conservation of spin up and down symmetry (like Nf=(N_up=3,N_down=3))
 
Thanks

**Comment by shaktiimaan** [comment]
If you did not understood my question, please let me know?

Thanks

**Comment by weinbe58** [comment]
Yes, the Nf accepts a list of values `[(Nup1,Ndn1),(Nup2,Ndn2),...]`. 

Could you post your full code here so I can see check it on my end?

**Comment by shaktiimaan** [comment]
Here is the minimal code to see the error. 

`from quspin.operators import hamiltonian # operators
from quspin.basis import spinful_fermion_basis_general # spin basis constructor
import numpy as np # general math functions
#
###### define model parameters ######
L=12
basis_2d=spinful_fermion_basis_general(L,double_occupancy=False,Nf=(6,6))
#print(basis_2d)
###### setting up hamiltonian ######
p=[[1,1,1]]
q=[[-1,1,1]]
static0=[["+-|",p],["|+-",q]]
H=hamiltonian(static0,[],basis=basis_2d,dtype=np.float64)
# diagonalise H
E,ww=H.eigsh(k=10,which="SA",return_eigenvectors=True)
print(E)
sub_sys_A_up=range(L//2) # subsystem for spin-up fermions
sub_sys_A_down=range(L//2) # subsystem for spin-down fermions
subsys_A=(sub_sys_A_up,sub_sys_A_down)
Sent=basis_2d.ent_entropy(ww[:,0],sub_sys_A=subsys_A,return_rdm="A",enforce_pure=False,return_rdm_EVs=False,
                            sparse=False,alpha=1.0,sparse_diag=True,subsys_ordering=True)
print(Sent)`

Thanks

**Comment by weinbe58** [comment]
which version of python are you using?

**Comment by weinbe58** [comment]
I think the issue is the following: the input in subsys_A has to be a tuple of lists, in python 3 range is an iterator.

to fix it use: 
```python
sub_sys_A_up=list(range(L//2)) # subsystem for spin-up fermions
sub_sys_A_down=list(range(L//2)) # subsystem for spin-down fermions
```

**Comment by shaktiimaan** [comment]
still it gives the same error.
I am using the latest version of python.

**Comment by weinbe58** [comment]
OK, this is a bug in the underlying code. Unfortunately, the fix will have to come in the next release. In the meantime you can use the simple_symm=False option. When you do you, this will convert the basis to spinless fermions where spin up orbitals are sites 0 to N-1 and spin down orbitals are N to 2N-1.
