### ISSUE TITLE
cannot import name 'spin_basis_general'

### ISSUE THREAD

**Issue by nukoyluoglu** [weinbe58/QuSpin#339]
Hello, I have installed QuSpin manually on a compute cluster, as conda was not available. However, when importing from QuSpin on a script, I get this error:

Traceback (most recent call last):
  File "quantum_algorithms.py", line 5, in <module>
    from quspin.basis import spin_basis_general
ImportError: cannot import name 'spin_basis_general'

I would appreciate any help, thank you!

**Comment by mgbukov** [comment]
This probably means the installation wasn't successful.

If there is no conda in your cluster, I recommend installing miniconda in
your home directory on the cluster, and then using miniconda to install
quspin (works in the exact same way).
