### ISSUE TITLE
Periodic Boundary Conditions for spinless_fermion_basis_1d

### ISSUE THREAD

**Issue by jsvandyke86** [weinbe58/QuSpin#344]
I'm having an issue for which I'm not quite sure if it is physics-based or related to how I'm using quspin.  A minimal example for reproducing the issue is to check the Jordan-Wigner mapping between the XY spin Hamiltonian and non-interacting spinless fermions, for L=3.  I would expect these to have the same energy spectrum, but they seem to be different.

```
from quspin.basis import spin_basis_1d, spinless_fermion_basis_1d
from quspin.operators import hamiltonian

L=3
Jxy=1.0

basis_spins = spin_basis_1d(L=L,pauli=0)
J_v = [ [Jxy,i,(i+1)%L] for i in range(L)]
xymodel = hamiltonian([["xx",J_v],["yy",J_v]],[],basis=basis_spins)
eigvals_xy = xymodel.eigvalsh()
print(eigvals_xy)

t = -Jxy/2.0
basis_fermions = spinless_fermion_basis_1d(L=L)
t_nn_left  = [[-t,i,(i+1)%L] for i in range(L)]
t_nn_right = [[-t,(i+1)%L,i] for i in range(L)]
fermion_model = hamiltonian([["+-",t_nn_left+t_nn_right],],[],basis=basis_fermions)
eigvals_fermions = fermion_model.eigvalsh()
print(eigvals_fermions)
```

If you print the corresponding Hamiltonian matrices, there are negative values appearing in the spinless fermion case when there are two particles present and one hops via the periodic boundary conditions.  The XY Hamiltonian has all positive matrix elements -- hence the difference in the eigenvalue spectrum.  But physically I would expect the set of energies to be identical under the JW transformation.

**Comment by mgbukov** [comment]
In some cases JW requires anti-periodic boundary conditions. Did you have a look at the JW example on the quspin documentation website?

**Comment by jsvandyke86** [comment]
I did take a look at the example in the documentation, but I mistakenly thought it was special to the transverse Ising/p-wave superconductor case.  Now I see that it applies more broadly -- thanks for the help!
