### ISSUE TITLE
Testing Op_shift_sector in spinful fermion basis 

### ISSUE THREAD

**Issue by kaushman1996** [weinbe58/QuSpin#347]
Hello
I made a simple test using this subroutine, but I am not getting consistent result from this:
Here I made a simple test :
using Op_shift_sector routine I evaluated state psi=c_0^\dagger |state>
So If I evaluate <psi|psi> must equal to  <state|c_0 c_0^\dagger|state>.
But I am not getting consistent result. Or I am understanding something wrong.
Here is the very minimal code:
[shift_op_ex.txt](https://github.com/weinbe58/QuSpin/files/5128038/shift_op_ex.txt)

Thanks

**Comment by shaktiimaan** [comment]
Is there something I am missing while understanding the subroutine argument?

**Comment by weinbe58** [comment]
The norm of `psi` is 0, can you please double check to make sure `basis_1` is connected to `basis` by the creation operator?

**Comment by shaktiimaan** [comment]
I am also not sure it connects or not due double occupancy false. But if I operate creation operator at site 2, then I guess it should connect. 
But still calculation in both side does not match.
[shift_op_ex.txt](https://github.com/weinbe58/QuSpin/files/5131412/shift_op_ex.txt)

**Comment by weinbe58** [comment]
There is nothing wrong with the code: here is an example where I do the calculation exactly by projecting to the full H-space (no particle conservation and with double occupancy)

```python
from __future__ import print_function, division
from quspin.basis import spinful_fermion_basis_general
from quspin.operators import hamiltonian
import numpy as np

L=10    #number of sites
#basis with 4 particles
basis=spinful_fermion_basis_general(L,double_occupancy=False,Nf=[(2,2),(1,3),(3,1),(4,0),(0,4)])
P = basis.get_proj(np.float32)
#basis with 5 particles
basis_1=spinful_fermion_basis_general(L,double_occupancy=False,Nf=[(4,1),(1,4),(3,2),(2,3),(5,0),(0,5)])
P_1 = basis_1.get_proj(np.float32)

basis_full = spinful_fermion_basis_general(L)


static=[["+-|",[[1,0,0]]],["|+-",[[-1,0,0]]]]
H=hamiltonian(static,[],basis=basis,dtype=np.float64,check_pcon=False)
E,ww=H.eigsh(k=5,which='SA',maxiter=1E10,return_eigenvectors=True)
static_0=[["+|",[2],1.0]]

#........Here I am operating creation up operator at site 0 on state ww[,0] which belongs to particle  number n=4 in basis, and wants to convert it to a state with basis n+1 =5 particles .......# 
psi = basis_1.Op_shift_sector(basis,static_0,ww[:,0])
#calculating <psi|psi>=expectation value of c_0 c_0\{dagger}  in state (|ww[:,0]>)

a=np.dot(psi,psi,out=None)
print(a)

# doing calculation exactly
# project to full H-space
psi_full = P.dot(ww[:,0]) 
# act with operator 
psi_full = basis_full.inplace_Op(psi_full,static_0,np.float64)
# project to basis_1 particle space
psi_1 = P_1.H.dot(psi_full)
# calculate overlap
print(np.dot(psi_1,psi_1))
# calculating difference between two methods
print(np.linalg.norm(psi_1-psi))
```
Why does what you have not work? Well the problem is that when you calculate the exptation value of the "-+" operator, that contains contributions from hilbert spaces that `allows` double occupancy. To see this replace line 12 with:

```python
basis_1=spinful_fermion_basis_general(L,double_occupancy=True,Nf=Nf)
```
Now in `basis_1` I allow for double occupancy, now the matrix elements match.

**Comment by shaktiimaan** [comment]
I understand that, I thought my operation of evaluating expectation value of the operator "-+" does not contain contribution of doubly occupied sites.
So how to use QuSpin routine to evaluate expectation value of such operators demanding no double occupancy, while operating the operator on a state.  
So basically how to modify this:
`static2=[["-+|",[[1.0,2,2]]]]`
`H2=hamiltonian(static2,[],basis=basis,dtype=np.float64,check_pcon=False,check_herm=False)`
`mat_el1=H2.matrix_ele(ww[:,0],ww[:,0])`
such that it does not allow operations of double occupancy on a state?

**Comment by weinbe58** [comment]
So what are you doing to do? let's define D as the projector to the space that does not allow doubly occupied sites:

Clearly $Dc c^\dagger D$ is not the same as $D c D D c^dagger D$ correct?

**Comment by shaktiimaan** [comment]
How to define D operator mathematically that restricts double occupancy in the intermediate states?

**Comment by weinbe58** [comment]
You do that by doing the `Op_shift_sector` to a basis that has the restriction. You are doing this in your code you sent here, this is why the matrix elements do not match they are two different things.

**Comment by weinbe58** [comment]
I'm not sure why you want to put this restriction in intermediate states, what model are you doing to simulate? The t-J model does not have the projectors in the middle of the operators in the kinetic term.

**Comment by shaktiimaan** [comment]
**NOTE: One has to make sure that the operator moves the state between the two sectors this function will not give the correct results otherwise.**
But you guys have made above warning while using `Op_shift_sector`. But operators like "-+" does not move state between two sector.

**Comment by weinbe58** [comment]
This is for sectors like momentum,parity, spin-inversion, etc. For particle conservation this function gives the correct results.

**Comment by shaktiimaan** [comment]
Is there a good reference to read about diagonalizing numerically spinful system?
