### ISSUE TITLE
MemoryError: Unable to allocate;  while creating basis states in spinful basis 

### ISSUE THREAD

**Issue by kaushman1996** [weinbe58/QuSpin#350]
`from quspin.basis import spinful_fermion_basis_general`
`L=20   #number of sites`
`basis=spinful_fermion_basis_general(L,double_occupancy=False,Nf=[(10,10),(9,11),(11,9),(12,8),(8,12),(13,7),(7,13),(14,6),(6,14),(15,5),(5,15),(16,4),(4,16),(17,3),(3,17),(18,2),(2,18),(19,1),(1,19),(20,0),(0,20)])`
`print(basis)`
I am getting this memory error. However my basis space is not that big it is just 2^20.
`MemoryError: Unable to allocate 4.01 TiB for an array with shape (551386115280,) and data type uint64`

This works fine If my basis would have been
`L=10`
`basis=spinful_fermion_basis_general(L)`
Here also basis 4^10=2^20 and QusPin creates the basis easily.
Can you let me know why it is showing memory allocation error in earlier case.

**Comment by kaushman1996** [comment]
Or Is it due to full basis dimension comes out to be 4^20 and I am considering only subspace whose dim is 2^20.

Thanks

**Comment by weinbe58** [comment]
can you try using: `Ns_block_est=...` to put in an estimate for the H-space size?

**Comment by kaushman1996** [comment]
Yes it works fine. Do we have to tell the exact H-space size or over estimate will work fine.  
Can you also refer me some good reference to learn how to construct basis and do numerics in spinful system, if there is any ?

**Comment by weinbe58** [comment]
Q1. No you don't have to give it the exact size, it will only allocate enough memory to store that amount you indicate and truncate the results if you go over or throw an error saying there is not enough space if you underestimate the result. 

Q2. If you're talking about references to using QuSpin, you can checkout the list of examples http://weinbe58.github.io/QuSpin/Examples.html and look for Fermi-Hubbard examples.

**Comment by kaushman1996** [comment]
No If I would be interested in writing my own code for constructing basis and constructing hamiltonian matrix in basic language, not using QuSpin.

**Comment by weinbe58** [comment]
A good reference to start with is this review Article by Anders Sandvik: https://arxiv.org/abs/1101.3281

**Comment by weinbe58** [comment]
For the discussion of symmetries I would look at this article and the section on ED https://arxiv.org/abs/1101.3281 The issue is it only discusses spin-1/2 systems but the general principles still apply to fersmions you just have to worry about the sign 

This article (https://ijpr.iut.ac.ir/article_721_ef2ea3c1f9f4b1931b5c5cd3d9732d58.pdf) gives more details on the hubbard model which should be helpful.

**Comment by kaushman1996** [comment]
Thanks a lot for second reference.  I knew about Sandvik's one, but he did considered spin full system, where sign issue occurs.
