### ISSUE TITLE
Matrix elements between different symmetry sectors

### ISSUE THREAD

**Issue by JanVanDieBos** [weinbe58/QuSpin#355]
Consider the case where I have a fermionic Hamiltonian which conserves particle number. With quspin I can find the eigenvectors in the different symmetry sectors. Is there a way to calculate the matrix elements  
<a href="https://www.codecogs.com/eqnedit.php?latex=\langle&space;\phi_n,&space;N-1&space;\vert&space;c_i&space;\vert&space;\phi_m,&space;N&space;\rangle" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\langle&space;\phi_n,&space;N-1&space;\vert&space;c_i&space;\vert&space;\phi_m,&space;N&space;\rangle" title="\langle \phi_n, N-1 \vert c_i \vert \phi_m, N \rangle" /></a>
using these symmetry blocks in quspin? Here I am considering the bra to live in the N-1 particle restricted space and the ket to live in the N particle restricted space and c_i is the destruction operator of the i'th mode.

**Comment by weinbe58** [comment]
There is a function to do this, see [Op_shift_sector](http://weinbe58.github.io/QuSpin/generated/quspin.basis.spin_basis_general.html#quspin.basis.spin_basis_general.Op_shift_sector)

There is currently an issue with this function, you can only transform from basis which have the same conserved quantum numbers, e.g. if one basis is using a symmetry not used by the other basis the results will not work. The only exception to this is particle conservation symmetry.
