### ISSUE TITLE
issue with .H attribute for dynamic Hamiltonian

### ISSUE THREAD

**Issue by mgbukov** [weinbe58/QuSpin#36]
for cpx-valued dynamic Hamiltonians

H_lat.toarray(time=2).H  

not equal to

H_lat.H.toarray(time=2)

because functions are not being conjugated.

**Comment by mgbukov** [comment]
The bug also exists in static-only Hamiltonians, if they are not hermitian, then

`np.linalg.norm(H.toarray() - H.toarray().T.conj())`

is different from

`np.linalg.norm( (H- H.H).toarray() )`

[can happen if the code accepts a non-existent symmetry by mistake and creates the Hamiltonian so the resulting matrix is non-hermitian]

**Comment by weinbe58** [comment]
Is there a simple example of where this happens?

**Comment by weinbe58** [comment]
fixed in [#53](https://github.com/weinbe58/QuSpin/pull/53)
