### ISSUE TITLE
Memory Leakage issue while time evolving a state vector using Lanczos module

### ISSUE THREAD

**Issue by Anirban1994-Phy** [weinbe58/QuSpin#360]
Hi, 

I have come across an issue of memory leakage while I implemented the following code:
[script.txt](https://github.com/weinbe58/QuSpin/files/5427874/script.txt)

My first observation to track this memory leakage issue was to run the 'TOP' command in terminal and I saw the memory usage is increasing with time. But to quantify this leakage properly I took the help of memory profiler module in Python (https://pypi.org/project/memory-profiler/). 

After installing the module, I ran the code using the memory profiler by simply writing this two lines in the terminal

**_mprof run {executable} (e:g mprof run name.py ; This would run the "name.py" code and simply track the memory usage after every 0.1 second)_**

And then to plot the memory profile I would use,

**_mprof plot_**

I have memory profiled "lanczos_full+expm_lanczos" and "lanczos_iter_expm_lanczos" and "expm_multiply" functions. And I have found out the first two function have memory leakage, where the last one does not have memory leakage issue. The following picture would show this. 

![minimal_script](https://user-images.githubusercontent.com/52740464/96969242-cce2e480-152f-11eb-8ab8-947568dd5749.png)

Thanking you,
Anirban

**Comment by Anirban1994-Phy** [comment]
"mprof plot" would plot the last data of memory profiling. One can rename the memory profiling file in the local directory and plot multiple profiles at once by writing

mprof plot {file1.dat} {file2.dat} ....

**Comment by weinbe58** [comment]
This is weird, the lanczos code is pure python so the memnry leak might be happening in some other package but I will take a look!

**Comment by mgbukov** [comment]
I was able to reproduce this actually; it behaves really weird indeed.

Marin

**Comment by mgbukov** [comment]
[minimal_script.txt](https://github.com/weinbe58/QuSpin/files/5710676/minimal_script.txt)
[mprof.txt](https://github.com/weinbe58/QuSpin/files/5710677/mprof.txt)

**Comment by weinbe58** [comment]
I think I might have found the source of the memory leak, it appears to be the use of the blas functionality that is causing the issues. I think I will simply replace the blas functions with a custom numba function that does the same thing. I don't think performance will suffer from this change.
