### ISSUE TITLE
additional quantum number conservation?

### ISSUE THREAD

**Issue by nikita-astronaut** [weinbe58/QuSpin#364]
Dear QuSpin developers,

I have a question. I am considering the fermion system with two sublattices. The number of particles on each sublattice is conserved! So I want to impose this quantum number explicitly and construct respective basis.

Could you please tell how one imposes additional conservation laws such as this? Thanks a lot!

Best wishes,
Nikita

**Comment by mgbukov** [comment]
did you check out this example:

[https://weinbe58.github.io/QuSpin/examples/example15.html](https://weinbe58.github.io/QuSpin/examples/example15.html#example15-label)
