### ISSUE TITLE
offline installation of QUSPIN through anaconda

### ISSUE THREAD

**Issue by magnon00** [weinbe58/QuSpin#368]
I installed the quspin offfline through "conda install quspin-0.2.6-py27hcef22cd_0.tar.bz2 " after downloading it from https://conda.anaconda.org/weinbe58/linux-64. 

Though the package "quspin" appears in "conda list", but fails to run a sample example: "python example0.py" by saying 
"ModuleNotFoundError: No module named 'quspin'
"

**Comment by mgbukov** [comment]
it's hard to say what could've gone wrong here. 

Try installing from source, if you can't use `conda install` (see instructions on doc website).

**Comment by sachin00-github** [comment]
Manual Installation also fails: 
It says following

  /home/lus03/sachinv/anaconda3/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it with " \
  ^
In file included from /home/lus03/sachinv/Chumbak/quspin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/hcb_core.cpp:663:0:
/home/lus03/sachinv/Chumbak/quspin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/source/make_general_basis.h:21:32: fatal error: boost/sort/sort.hpp: No such file or directory
  #include <boost/sort/sort.hpp>
                                ^
compilation terminated.
error: Command "g++ -pthread -B /home/lus03/sachinv/anaconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/lus03/sachinv/anaconda3/lib/python3.8/site-packages/numpy/core/include -I/home/lus03/sachinv/Chumbak/quspin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/source -I/home/lus03/sachinv/anaconda3/include -I/home/lus03/sachinv/anaconda3/lib/python3.8/site-packages/numpy/core/include -I/home/lus03/sachinv/anaconda3/include/python3.8 -c /home/lus03/sachinv/Chumbak/quspin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/hcb_core.cpp -o build/temp.linux-x86_64-3.8/home/lus03/sachinv/Chumbak/quspin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/hcb_core.o -MMD -MF build/temp.linux-x86_64-3.8/home/lus03/sachinv/Chumbak/quspin/QuSpin-master/quspin/basis/basis_general/_basis_general_core/hcb_core.o.d -fno-strict-aliasing -Wno-unused-variable -Wno-unknown-pragmas -std=c++11" failed with exit status 1
(base) [sachinv@atulya335 QuSpin-master]$  #warning "Using deprecated NumPy API, disable it with " ^C
(base) [sachinv@atulya335 QuSpin-master]$ conda install gxx_linux-64
Collecting package metadata (current_repodata.json): failed

**Comment by mgbukov** [comment]
Try python 37 or lower

Marin

**Comment by mgbukov** [comment]
Is this issue still there, or should we close it?

**Comment by sachin00-github** [comment]
Pl don't close it now.

I will get back to this post. 

Regards
Sachin
