### ISSUE TITLE
Time evolution with logarithmic time grid 

### ISSUE THREAD

**Issue by jerrylvx** [weinbe58/QuSpin#380]
Happy new year QuSpin developers,

I am trying to plot the logarithmic growth of entanglement of an MBL system. In order to get a nice curve, I wish to perform time evolution on a logarithmic time grid. However, it seems that exp_op does not support this, as it only allows equidistant times. Am I missing some relevant feature?

Thanks!

**Comment by mgbukov** [comment]
Indeed, a log-grid is currently not available in `exp_op`. 

If you are doing time-evolution with a (piece-wise) constant in time Hamiltonian (e.g., fixed disorder realization), you may want to try out the [expm_multiply_parallel](https://weinbe58.github.io/QuSpin/generated/quspin.tools.evolution.expm_multiply_parallel.html#quspin.tools.evolution.expm_multiply_parallel) routine. The idea is to create an `expm_multiply_parallel` object, and use its [`dot`](https://weinbe58.github.io/QuSpin/generated/quspin.tools.evolution.expm_multiply_parallel.html#quspin.tools.evolution.expm_multiply_parallel.dot) method to apply it to the wavefunction. Here, you'd have to loop over time yourself and apply the matrix exponential at each time step; you can use this to set the time spacing. This should also be faster than the `exp_op` class. Finally, note that `expm_multiply_parallel` never actually computes the matrix exponential, but only its action on a vector.

**Comment by jerrylvx** [comment]
Thanks a lot, Marin. Let me give it a try.

**Comment by jerrylvx** [comment]
Thanks again, it worked like a charm. One thing that confuses me is the page value mentioned in the example code for expm_multiply_parallel. What is this "page-corrected entanglement value"?

**Comment by mgbukov** [comment]
where exactly is the Page correction mentioned? Can you provide a link?

The Page correction to the maximal entanglement value takes into account finite-size effects, see the [original paper](https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.71.1291); we used it recently with quspin -- see [Fig 2 in this peprint](https://arxiv.org/pdf/2012.10405.pdf).

**Comment by jerrylvx** [comment]
This is the link: http://weinbe58.github.io/QuSpin/examples/example22.html#example22-label

**Comment by mgbukov** [comment]
thanks, I'll add the reference to the PRL paper there. 

If you're all set, you can go ahead and close this issue.
