### ISSUE TITLE
int_to_state, representative in basis give possibly misleading answers

### ISSUE THREAD

**Issue by jaredjeya** [weinbe58/QuSpin#386]
Hi,

I've noticed that  `spin_basis_general.int_to_state` returns what seems to me to be a misleading result, in that more or less returns the binary (or n-ary) representation of the integer without taking account of symmetries -- that is, the input represents the index in the symmetry-free basis, not the basis being used. `representative` has similar behaviour. Correspondingly `state_to_int `also gives the index in the full symmetry-free basis. This is perhaps intended behaviour but it's not documented clearly. I assume the same behaviour exists in various other basis classes, but I haven't checked.

As an example, if I run the following code:

```
import numpy as np
from quspin.basis import spin_basis_general

# Create two bases - one symmetry-reduced, one full, for a spin-1/2 chain of length 8
# The symmetry used is site inversion symmetry - mapping site i to site (L-1) - i
L = 8

i = np.arange(L, dtype=int)        # List of sites
P = (L - 1) - i                    # Site inversion symmetry
blocks = dict(pblock = (P, (-1 + 1) // 2))

basis_reduced = spin_basis_general(L, S="1/2", **blocks)
basis_full = spin_basis_general(L, S="1/2")

# Pick a random state in the reduced basis and compare it to its projection into the full basis.
idx = 33
print("In reduced basis:")
print(f"1.0 {basis_reduced.int_to_state(33)} ({idx:d}")

state = np.zeros(basis_reduced.Ns)
state[idx] = 1
projstate = basis_reduced.project_from(state, sparse=False)
print("\nIn full basis:")
for i, a in enumerate(projstate):
	if abs(a) < 1e-16:
		continue
	print(f"{a:.3f} {basis_full.int_to_state(i)} ({i:d})")
```
it produces the output:

```
In reduced basis:
1.0 |0 0 1 0 0 0 0 1> (33)

In full basis:
0.707 |0 0 1 0 0 0 1 1> (35)
0.707 |1 1 0 0 0 1 0 0> (196)
```

These don't match - I'd expect here that the call to `int_to_state `for the reduced basis would return the representative state |1 1 0 0 0 1 0 0>. In fact, it returns a completely different state, with no relation to the physical state. If this is intended behaviour, I think it needs to be documented clearly that these functions are expecting an input with reference to the symmetry-free basis. I also think there needs to be a function that is the inverse of `index`, that tells you the representative of a given index in the reduced basis.

**Comment by mgbukov** [comment]
I guess there is some sort of confusion here. There are three related methods in the `basis` class:

a) basis.int_to_state(): transform state from integer representation to string
b) basis.state_to_int(): transform state from string to integer representation
c) basis.index(): transforms state in integer representation to its array index.

These notions are best seen if one prints the basis:

```
reference states: 
array index   /   Fock state   /   integer repr. 
      0.         |1 1 1 1>           15  
      1.         |1 1 1 0>           14  
      2.         |1 1 0 1>           13  
      3.         |1 1 0 0>           12  
      4.         |1 0 1 0>           10  
      5.         |1 0 0 1>            9  
      6.         |1 0 0 0>            8  
      7.         |0 1 1 0>            6  
      8.         |0 1 0 0>            4  
      9.         |0 0 0 0>            0  
The states printed do NOT correspond to the physical states: see review arXiv:1101.3281 for more details about reference states for symmetry-reduced blocks.
```

* `basis.index` returns the array index, i.e. the first column. This is needed in order, say, to know how to read-off matrix elements between quantum states. E.g., the matrix element  `<1 1 0 1| H | |0 1 1 0>` is `H[2,7]`. 

* `basis.int_to_state` returns the Fock state string (second col in printed basis); This is need if one wants to visualize a state defined in its integer representation. The state needs to be in the basis. 

*  `basis.int_to_state` returns the interr representation (third col in printed basis). This is required if one wants to compute the integer representation of a state. The state needs to be in the basis. 

Additionally, all basis states in their integer representation (i.e. the main content of the `basis` object) is stored in `basis.states`; `basis.states` correspond to the third col when the basis is printed. 

Now, let's get to your example:

Let's define two basis:

```
import numpy as np
from quspin.basis import spin_basis_general

# Create two bases - one symmetry-reduced, one full, for a spin-1/2 chain of length 8
# The symmetry used is site inversion symmetry - mapping site i to site (L-1) - i
L = 4

i = np.arange(L, dtype=int)        # List of sites
P = (L - 1) - i                    # Site inversion symmetry
blocks = dict(pblock = (P, (-1 + 1) // 2))

basis_reduced = spin_basis_general(L, S="1/2", **blocks)
basis_full = spin_basis_general(L, S="1/2")


print(basis_reduced)
print()

print(basis_full)
print()
```

This gives:

```
(base) [mgbukov@mgbukovs-MacBook-Pro quspin]$ python int_to_state.py 
reference states: 
array index   /   Fock state   /   integer repr. 
      0.         |1 1 1 1>           15  
      1.         |1 1 1 0>           14  
      2.         |1 1 0 1>           13  
      3.         |1 1 0 0>           12  
      4.         |1 0 1 0>           10  
      5.         |1 0 0 1>            9  
      6.         |1 0 0 0>            8  
      7.         |0 1 1 0>            6  
      8.         |0 1 0 0>            4  
      9.         |0 0 0 0>            0  
The states printed do NOT correspond to the physical states: see review arXiv:1101.3281 for more details about reference states for symmetry-reduced blocks.


reference states: 
array index   /   Fock state   /   integer repr. 
      0.         |1 1 1 1>           15  
      1.         |1 1 1 0>           14  
      2.         |1 1 0 1>           13  
      3.         |1 1 0 0>           12  
      4.         |1 0 1 1>           11  
      5.         |1 0 1 0>           10  
      6.         |1 0 0 1>            9  
      7.         |1 0 0 0>            8  
      8.         |0 1 1 1>            7  
      9.         |0 1 1 0>            6  
     10.         |0 1 0 1>            5  
     11.         |0 1 0 0>            4  
     12.         |0 0 1 1>            3  
     13.         |0 0 1 0>            2  
     14.         |0 0 0 1>            1  
     15.         |0 0 0 0>            0  
```

Suppose now that we want to create the quantum state in the reduced basis, corresponding to `|1 0 1 0>`. We do this using:

```
idx = 4
print("In reduced basis: (Flock state, int-rep)")
print(f"{basis_reduced.int_to_state(basis_reduced.states[idx])}, {basis_reduced.states[idx]} ")

state = np.zeros(basis_reduced.Ns)
state[idx] = 1
```

Then, we can check which states this corresponds to in the full basis:

```
projstate = basis_reduced.project_from(state, sparse=False)

print("\nIn full basis: (Flock state, int-rep)")
for i, a in enumerate(projstate):
	if abs(a) < 1e-16:
		continue
	print(f"{a:.3f}, {basis_full.int_to_state(basis_full.states[i])}, {basis_full.states[i]} ") 
```

As we see, these are precisely the two states related by parity. 

Let me know how you think the documentation should be updated to avoid other users to get confused in the future.

**Comment by jaredjeya** [comment]
Thanks -that's cleared it up for me fully. 

So I think there is this confusion between what you call the "integer representation" - which corresponds to the reference state - and index in the basis. It's not really made *that* clear in the documentation that these are two separate things: you'd have to run print(basis) and then read the paper on the arXiv. If you know that, it makes sense. But even though I had some familarity with the idea, I was still confused. Particularly it didn't really make sense to me that if I'm working with some symmetry-reduced basis, and I supply the index of some basis state to int_to_state, why I don't get that basis state's representative but some random other state (the binary representation of the index). I'd also thought that in the symmetry-free basis, that the index and the representation coincide, which they clearly don't.

To improve the documentation, perhaps in the functions etc. that reference the "integer representation" - it should be made clear it's *not* the same as an index in the basis, and perhaps a one or two line summary of the idea of representative states at the start of the documentation page. It could also say "you may be looking for `index()`" in the documentation for `int_to_state()` and vice-versa.

I think what could really help prevent confusion is to define a very simple function like,

```
def reverse_index(self, idx: int):
	return self.int_to_state(self.states[idx])
```

and then also on `int_to_state`, say "you may be looking for `reverse_index`"and vice-versa. That would've made it clear that int_to_state *doesn't* do what I initially thought it would - because there's another function that does.

**Comment by mgbukov** [comment]
@jaredjeya check out the [new example](https://github.com/weinbe58/QuSpin/blob/dev_0.3.5/examples/scripts/example00.py) on properly using quspin's basis objects. 

Let me know if you have any comments; we plan to make the example available to the users with the next release.
