### ISSUE TITLE
Error with quspin user_basis and uint64 datatype

### ISSUE THREAD

**Issue by sunpradh** [weinbe58/QuSpin#387]
I was trying to use the quspin `user_basis` class for some exact diagonalization of some lattice gauge theories. I noticed that there is always a warning when trying to use the uint64 datatype for these constrained systems.
I followed the example [here](https://weinbe58.github.io/QuSpin/examples/example16.html#example16-label), where I generate the array of states separately and and then feed it to the `next_state` function.
The problem arises when I use the datatype `uint64` for my states. I get the warning
```
TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Exception ignored in: 'quspin.basis.basis_general._basis_general_core.user_core.python_to_basis_int'
TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```
when the first state of the array is a non-zero integer. In fact when I check the array `basis.states` I see that the first state get defaulted to zero.

I was able to replicate the the error with a simple script
```
import numpy as np
import numba as nb
import quspin.basis.user as qbu

states = np.arange(10, 4096, dtype=np.uint64)

def get_s0(N, Np):
    return states[0]

def get_Ns(N, Np):
    return states.size

@nb.cfunc(qbu.next_state_sig_64)
def next_state(s, counter, N, args):
    return args[counter+1]

pcon_dict = dict(
    Np = (),
    next_state=next_state,
    next_state_args=states,
    get_s0_pcon=get_s0,
    get_Ns_pcon=get_Ns
)

@nb.cfunc(qbu.op_sig_64)
def z2_op(op_struct_ptr, op_str, ind, nlinks, args):
    op_struct = nb.carray(op_struct_ptr, 1)[0]
    err = 0
    ind = nlinks - ind - 1
    s = 2 * (op_struct.state & (1 << ind)) - 1
    b = (1 << ind)
    if op_str == 85:  # U
        op_struct.state ^= b
    elif op_str == 86:  # V
        op_struct.matrix_ele *= s
    else:
        op_struct.matrix_ele = 0
        err = -1
    return err

op_dict = dict(op=z2_op, op_args=np.array([], dtype=np.uint64))
basis = qbu.user_basis(N=20, basis_dtype=np.uint64, op_dict=op_dict, allowed_ops="UV", sps=2, pcon_dict=pcon_dict)

print("Input states:", states)
print("Output states:", basis.states)
print("Where they differ:", np.argwhere(states != np.flip(basis.states)))
```

The output of this script is:
```
TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Exception ignored in: 'quspin.basis.basis_general._basis_general_core.user_core.python_to_basis_int'
TypeError: ufunc 'bitwise_and' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
Input states: [  10   11   12 ... 4093 4094 4095]
Output states: [4095 4094 4093 ...   12   11    0]
Where they differ: [[0]]
```

We can see that the state `10` disappears.
If I change all the datatype to 32bit the errors disappears and and the basis is constructed correctly.
I use quspin version `0.3.4` and python `3.7.9`

Thank you for your time

**Comment by weinbe58** [comment]
Thank you for the report, 

this should not be an issue, the problem is that the function is mixing unint64 and int32 types and so it is complaining that it can't cast do the casting according to the rules that numpy does integer casts. I will add a fix that should remove that warning in the next release.

**Comment by weinbe58** [comment]
Thanks for the report, I don't think this should be an issue but we will update the code to fix the warning.

TODO: fix the casting [here](https://github.com/weinbe58/QuSpin/blob/master/quspin/basis/basis_general/_basis_general_core/source/general_basis_core.pyx#L173)

**Comment by sunpradh** [comment]
Thanks for the response. I'll be waiting for the fix then
