### ISSUE TITLE
[Bug] reduce_output Option of *_basis_general method Op_bra_ket() does not behave as expected

### ISSUE THREAD

**Issue by temporalcookie** [weinbe58/QuSpin#388]
Hi,
first of all thank you very much for this useful package! I am currently trying to use it for calculating local energies for some Variational Ansatz. I am using the latest version of QuSpin (0.3.4).

The first minor point is that I think the docstring for the `reduce_output` option does not correspond to the intended actual behaviour. I think `True` and `False` are exactly reversed here, as I would expect setting `reduce_output=True` would yield a reduced (i.e. shorter) output.
https://github.com/weinbe58/QuSpin/blob/c239d01e6ce76253b03440cda3c8819a9f63e288/quspin/basis/basis_general/base_general.py#L865-L866

It appears to me that this is also what the code is doing:
https://github.com/weinbe58/QuSpin/blob/c239d01e6ce76253b03440cda3c8819a9f63e288/quspin/basis/basis_general/base_general.py#L909-L917

Now, my main trouble is that for the model I am looking at, setting `reduce_output` to False or True does not make a difference and the output is always reduced. In order to properly collect the matrix elements for the local energies however, it would be very convenient to get non-reduced output.

First, this example code works as expected and is basically taken from [Monte Carlo Sampling Expectation Values of Obsevables](http://weinbe58.github.io/QuSpin/examples/example11.html):
```
from quspin.basis import spin_basis_general
from quspin.operators._make_hamiltonian import _consolidate_static
import numpy as np
###### define model parameters ######
J1=1.0 # nn interaction
J2=0.5 # nnn interaction
Lx, Ly = 4, 4 # linear dimension of 2d lattice
N_2d = Lx*Ly # number of sites
#
###### setting up user-defined symmetry transformations for 2d lattice ######
sites = np.arange(N_2d) # site labels [0,1,2,....]
x = sites%Lx # x positions for sites
y = sites//Lx # y positions for sites
#
T_x = (x+1)%Lx + Lx*y # translation along x-direction
T_y = x +Lx*((y+1)%Ly) # translation along y-direction
#
T_a = (x+1)%Lx + Lx*((y+1)%Ly) # translation along anti-diagonal
T_d = (x-1)%Lx + Lx*((y+1)%Ly) # translation along diagonal
#
P_x = x + Lx*(Ly-y-1) # reflection about x-axis
P_y = (Lx-x-1) + Lx*y # reflection about y-axis
P_d = y + Lx*x # reflection about diagonal
#
Z   = -(sites+1) # spin inversion
#
###### setting up operator string for Hamiltonian matrix elements H_{ss'} ######
# setting up site-coupling lists for the J1-J2 model on a 2d square lattice
J1_list=[[J1,i,T_x[i]] for i in range(N_2d)] + [[J1,i,T_y[i]] for i in range(N_2d)]
J2_list=[[J2,i,T_d[i]] for i in range(N_2d)] + [[J2,i,T_a[i]] for i in range(N_2d)]
# setting up opstr list
static=[["xx",J1_list],["yy",J1_list],["zz",J1_list],  ["xx",J2_list],["yy",J2_list],["zz",J2_list]]
# convert static list to format which is easy to use with the basis_general.Op and basis_general.Op_bra_ket methods. 
static_formatted = _consolidate_static(static)

basis = spin_basis_general(N_2d, pauli=0, make_basis=False, 
            Nup=N_2d//2, 
            kxblock=(T_x,0), kyblock=(T_y,0),
            pxblock=(P_x,0), pyblock=(P_y,0), pdblock=(P_d,0),
            zblock=(Z,0),
            block_order=['zblock','pdblock','pyblock','pxblock','kyblock','kxblock'] # momentum symmetry comes last for speed
                          )
states = []
for i in range(20):
    s=[0 for _ in range(N_2d//2)] + [1 for _ in range(N_2d//2)]
    np.random.shuffle(s)
    s = np.array(s)
    s=''.join([str(j) for j in s])
    # transform state in bit representation
    s=int(s,2)
    states.append(s)
states = basis.representative(states)

for opstr,indx,J in static_formatted:
        # for every state `s`, compute the state it connects to `s'`, and the corresponding matrix element `ME`
        ME,bras,kets = basis.Op_bra_ket(opstr,indx,J,np.float64,states,reduce_output=False)
        print(len(ME))
```

This gives the output:
```
20
20
20
20
20
...
```

While using
```
for opstr,indx,J in static_formatted:
        # for every state `s`, compute the state it connects to `s'`, and the corresponding matrix element `ME`
        ME,bras,kets = basis.Op_bra_ket(opstr,indx,J,np.float64,states,reduce_output=True)
        print(len(ME))
```
gives the desired reduced lengths:
```
0
0
10
10
7
13
...
```

However, for the model I want to look at (the bilinear-biquadratic spin-1 chain) I get the following behaviour:
```
from quspin.basis import spin_basis_general
from quspin.operators._make_hamiltonian import _consolidate_static
import numpy as np

L=6
basis=spin_basis_general(L,pauli = 0, S = '1',make_basis=False)

theta = 0.1*np.pi
J = 1
D = 0.2
# Bilinear terms
bilinear_half = [[0.5*J*np.cos(theta),i,(i+1)] for i in range(L-1)]
bilinear_s_z = [[1,i,(i+1)] for i in range(L-1)]
# Biquadratic terms
biquadratic_quarter = [[0.25*J*np.sin(theta),i,i,(i+1),(i+1)] for i in range(L-1)]
biquadratic_half = [[0.5*J*np.sin(theta),i,i,(i+1),(i+1)] for i in range(L-1)]
biquadratic_s_z = [[1,i,i,(i+1),(i+1)] for i in range(L-1)]

static_bl = [["+-",bilinear_half],["-+",bilinear_half], ["zz",bilinear_s_z]]
static_bq = [["++--",biquadratic_quarter],["--++",biquadratic_quarter],["+--+",biquadratic_quarter], ["-++-",biquadratic_quarter],
            ["z+z-",biquadratic_half],["z-z+",biquadratic_half],["+z-z",biquadratic_half],["-z+z",biquadratic_half],
            ["zzzz",biquadratic_s_z]]
static = static_bl + static_bq
static_formatted = _consolidate_static(static)

# Randomly generated states
states = basis.representative([514, 498, 728, 201, 510, 165])
for opstr,indx,J in static_formatted:
        # for every state `s`, compute the state it connects to `s'`, and the corresponding matrix element `ME`
        ME,bras,kets = basis.Op_bra_ket(opstr,indx,J,np.float64,states,reduce_output=False)
        print(len(ME))
```

Giving me the output
```
1
4
2
0
1
4
1
0
0
0
1
2
```

From the code snippet of the `Op_bra_ket()` method I can only guess that in my case, some of the matrix elements computed by `self._core.op_bra_ket(ket_states,bra,ME,opstr,indx,J,self._Np)` turn out as `NaN`, but I do not understand why. 

Is there something I can do with my code in order to fix this or would you need to change the QuSpin code?

**Comment by mgbukov** [comment]
this is a bug in the code; thanks for spotting it!

Luckily, I think the fix is trivial: just replace [line 373 of spin.py](https://github.com/weinbe58/QuSpin/blob/master/quspin/basis/basis_general/spin.py#L373) by
```
return higher_spin_basis_general.Op_bra_ket(self,opstr,indx,J,dtype,ket_states,reduce_output=reduce_output)
```
and it should work. 

You see how the flag is present for the spin-1/2 basis, but I guess we simply forgot to add it for spin-1. 

@weinbe58 is there any deeper reason why this flag was omitted for spin-1? I just checked that adding it produces the desired output, as it should. So if there's nothing wrong with adding it, let me know and I'll push that trivial change so it shows up in quspin 0.3.5. I also fixed the docstring for `reduce_output`.

**Comment by temporalcookie** [comment]
Thanks a lot for the very quick response! Then I’ll wait for the next release to be published. :-)

**Comment by mgbukov** [comment]
luckily, the next release should be out early next week [unless we encounter further problems] :)

**Comment by mgbukov** [comment]
New release is out.
