### ISSUE TITLE
handling the sign change in fermion operators

### ISSUE THREAD

**Issue by tracyabc** [weinbe58/QuSpin#394]
Dear developer,

I have started using Quspin recently and find it very convenient. Thank you for developing this nice package.
I want to calculate the spatial correlation between site r and the site 0, i.e <c_r^{\dagger}c_0>, of the SSH model. I would like to know if the sign change in exchanging the fermion operators will be automatically handled in this case for an arbitrary r. If not, I think I shall scan through each basis and count the number of (spinless) fermions to determine the sign change. Are there any intrinsic functions can be used to simplify the procedure? 

Your help would be much appreciated. Thank you.

**Comment by weinbe58** [comment]
Hello! For a single particle problems the sign actually does not matter but yes the code takes care of the sign if you use fermion basis classes

**Comment by tracyabc** [comment]
Thanks for clarifying.
