### ISSUE TITLE
Regarding four fermion terms in SYK model

### ISSUE THREAD

**Issue by Sourav-physics** [weinbe58/QuSpin#395]

**Comment by Sourav-physics** [comment]
Dear Developers,
      
         I have trying to simulate the SYK Hamiltonian using QuSpin. To create the four fermion term given as $ J \sum _{i, j ,k, l} c_{i}^{dagger} c^{\dagger}c_{k} c_{l}$, I have been using the following little code.

from quspin.operators import hamiltonian
from quspin.basis import spinless_fermion_basis_1d


Jnn = []
basis =  spinless_fermion_basis_1d (L=L)
for i in range (L):
    for j in range (L):
        for k in range (L):
            for l in range (L):
                Jnn.append ([J,i,j,k,l])            # This term creates the coupling # 
static =[["++--", Jnn]]                              # creates the static operator string #
Ham = hamiltonian (static, [], dtype = np.float64, basis=basis)

However, the above code yields a null Hamiltonian. I do not understand where the problem lies. 
It would be very kind if you could point out.

**Comment by Sourav-physics** [comment]
I would just like to point out that I have written the operator string following the spirit as discussed in the QuSpin docu page..(as shown below.
![quspin](https://user-images.githubusercontent.com/63020821/106801759-222ea600-6688-11eb-9c36-e4848af89b1f.png)
)

**Comment by weinbe58** [comment]
could you copy and paste the code as text?

**Comment by Sourav-physics** [comment]
Thanks for the response. However, I realized that it was rather a physics related issue why I was getting all the off diagonal elements zero (the coupling corresponding to the four fermions terms need to be a four index anti-symmetric tensor since otherwise the four fermion term simply gets cancelled out after sum over all indices are taken). So, it is really not issue with QuSpin which gives nice results after the aforementioned correction is taken into account.

**Comment by mgbukov** [comment]
ok, keep an eye on the new release (coming up next week) -- there we will introduce the Majorana operators to the fermion bases; there will be an SYK example in the Majorana representation too.

**Comment by Sourav-physics** [comment]
Ok..that sounds great ! Thanks.

**Comment by mgbukov** [comment]
The new release (featuring the Majorana operators and the SYK example) is available to install using anaconda. 

Closing this issue.
