### ISSUE TITLE
Regarding installation of new version QuSpin 0.3.5

### ISSUE THREAD

**Issue by Sourav-physics** [weinbe58/QuSpin#397]
Hi, I had earlier installed QuSpin via anaconda. To update the version, it is suggested in the github page that "all one has to do is run the installation command again." In spite of doing it (command used: conda install -c weinbe58 quspin), when I check the version of QuSpin in jupyter notebook using the command " ! pip show QuSpin", I get the following results which show that the version is 0.3.4 which not the latest one I was looking for.

Name: quspin
Version: 0.3.4
Summary: UNKNOWN
Home-page: UNKNOWN
Author: Phillip Weinberg, Marin Bukov
Author-email: weinbe58@bu.edu,mgbukov@berkeley.edu
License: BSD
Location: /home/sourav/anaconda3/lib/python3.7/site-packages
Requires: 
Required-by: 

Could you kindly point out where I am getting wrong?

**Comment by mgbukov** [comment]
Make sure that the kernel you use in Jupyter has the new version of quspin. 

Start by restarting the kernel. If it doesn't work, you can create a new conda environment, install quspin, and mount it as a kernel in Jupyter using:

```
conda install ipykernel
```
and then
```
python -m ipykernel install --user --name kernel_name --display-name "kernel_name"
```
Restart jupyter and you should see your custom conda environment as a kernel to select from the list.
