### ISSUE TITLE
Support for parallelizing the quspin code due to insufficient memory space 

### ISSUE THREAD

**Issue by adithi16** [weinbe58/QuSpin#399]
Hello, 
I am trying to write a code for a Hamiltonian with general_spin_basis with 6*6= 36 sites on a triangular lattice. The aim is to look at the correlation functions in this systems as a function of different parameters in the Hamiltonian. 
Since we are have only about 256GB RAM per node available in our cluster, even after using symmetries, it will not be sufficient. We would need approximately 512 GB RAM. 
Is there a way to parallelize the quspin code (like MPI)? If yes, any references as to how to do it would be very helpful. 
As I understand, Open MP support by using multi threading, enhances the speed of computation within the shared memory. 
We require to use different nodes to have enough space to allocate memory for our computation. How to do it in quspin?

**Comment by weinbe58** [comment]
Unfortunately, there is no support for MPI, however, if you are calculating low-energy eigenstates you can use the `quantum_LinearOperator` class. This class does not explicitly calculate the matrix element so it is much more memory efficient.
