### ISSUE TITLE
Regarding installation without using anaconda.

### ISSUE THREAD

**Issue by bkhoutom** [weinbe58/QuSpin#400]
Hi! FIrst time ask a question on Github. I was just wondering what is the best way to install Quspin without anaconda. I'm trying to run my code on the cluster, which not allows installing anaconda (only pip is allowed). I tried to install manually but failed. Is there another way I can install it on the cluster. Thank you very much for your help!!

**Comment by mgbukov** [comment]
If manual install didn't work, your best shot is to install miniconda in
your home directory on the cluster; miniconda comes with 'conda install' so
you can use this to install quspin.

Marin

**Comment by bkhoutom** [comment]
Thanks for your advice. The miniconda is forbidden on the cluster...I guess I'll figure out a way to install manually again.

**Comment by mgbukov** [comment]
In that case I would contact the cluster administration and kindly ask them
to install QuSpin.

Marin
