### ISSUE TITLE
Restricted allowed tensor space

### ISSUE THREAD

**Issue by bkhoutom** [weinbe58/QuSpin#401]
Hi! I'm thinking about constraining the combined Hilbert space H_A tensor H_B to certain bases. For example, for two 16-dim spaces, if a particle in H_A is located at the first state, particles in space B can only occupy the same position or the nearest neighbour. e.g.
|1,0,0,0>|1,0,0,0> or |1,0,0,0>|0,1,0,0> or |1,0,0,0>|1,1,0,0>are allowed, but |1,0,0,0>|0,0,0,0> or |1,0,0,0>|0,0,1,0>...are not considered . I know there is a similar example in user_basis class, but does the same idea apply to the tensor basis?
Thank you very much

**Comment by mgbukov** [comment]
[this example](https://weinbe58.github.io/QuSpin/examples/example10.html#example10-label) shows how to use the tensor basis. Note that you won't be able to use symmetries with the `tensor_basis` class. 

And [here](https://weinbe58.github.io/QuSpin/user_basis.html) is a tutorial on using the `user_basis`. 

Hope that helps!

**Comment by bkhoutom** [comment]
I'll take a look. Thanks a lot!
