### ISSUE TITLE
bug in fermionic partial trace for non-contiguous subsystems in v 0.3.5

### ISSUE THREAD

**Issue by javierfaba** [weinbe58/QuSpin#403]
Dear developers,

I'm working with fermionic systems, and quspin is being so useful, thank you very much. However, I think that the way in which quspin computes the partial trace of a fermionic state is incorrect.

When dealing with fermionic density matrices, in order to compute the partial trace, one must conmute the fermionic creation operators towards the vacuum state projector before beeing removed. This is explained, for example, here:

https://iopscience.iop.org/article/10.1088/1367-2630/18/3/033014

Concretely, in section 3, page 3. The minus signs due to the anticonmutation relations of the fermionic operators may modify the value of the off-diagonal elements of the reduced density matrix. For example, in the reference given above (concretely in the Appendix), a general fermionic mixed state of 4 sites is analyzed, and the off-diagonal elements of all the possible 2 sites reductions are computed. You can see that their values could be drastically different due to the minus signs.

However, I think that quspin computes the reduced density matrices of fermionic states without taking into account this issue.

Thank you.

**Comment by mgbukov** [comment]
Hi @javierfaba,

thanks for reporting this issue. 

It would be very helpful if you could upload a minimal python script here [in .txt format, otherwise github won't let you upload it] which: 
(i) computes the partial trace for a fermionic state using quspin v0.3.5 functinality, and 
(ii) using the alternative method of the reference you cite. 

E.g., this can be a state from the Appendix of the reference you cite above. 

This way we should be able to trace back the problem and try to fix it.

**Comment by javierfaba** [comment]
Hi @mgbukov ,

Here is an example of this issue.

[fermionic_partial_trace_example.txt](https://github.com/weinbe58/QuSpin/files/6258210/fermionic_partial_trace_example.txt)

**Comment by weinbe58** [comment]
Thanks for pointing this out. An easier way to see this inconsistency is to simply compare the expectation value of a local operator in the reduced DM produced by the partial trace function. It becomes clear that the results do not match the results from the full state.

**Comment by weinbe58** [comment]
@javierfaba 
 
One question I have is: for contiguous partitions (contiguous with respect to the fermionic creation/annihilation operator ordering) is it possible to map the qubit and fermion partial traces? 

The idea being that for contiguous partitions you do not need to commute any operators to calculate the trace and so the reasoning in the paper does not apply.

**Comment by javierfaba** [comment]
For contiguous partitions you may have to commute creation/annihilation operators. However, if the parity superselection rule apply, the minus signs will always cancel each other. 

Nevertheless, when we say that we cannot map fermion states to qubit states, we refer to a ‘full state’ map such that all fermionic reduced states are equivalent to their corresponding reduced qubit states. For a particular fermionic reduced state (with a not necessarily contiguous partition, in general), you can always map that state onto a reduced qubit state since you are free to map each fermionic basis state to a qubit basis state up to an arbitrary phase. However, if you try to map the full fermionic state onto a full qubit state such that all fermionic reduced states match with the reduced qubit ones, there is no phase choice possible. This is better explained in the Appendix of reference above (https://iopscience.iop.org/article/10.1088/1367-2630/18/3/033014).

**Comment by weinbe58** [comment]
I see, so just to clarify: What you are saying is that for a contiguous partition you can simply map the fermionic Fock state to qubit states just using the local standard Fock basis representation and get the physically meaningful partial trace operation that preserves expectation values? I see this in numerical experiments but this proof is not obvious to me.

**Comment by javierfaba** [comment]
This is correct. You can think it this way:

Following LaTeX notation, you can write an element of the Fock basis as a product of fermionic creation operators acting on the vacuum state. For example 
|1100> = a_1^\dagger a_2^\dagger|vac.>

In a density matrix state, you will have ket-bra combinations of those states, for example

|1100><1010| = a_1^\dagger a_2^\dagger|vac.><vac.|a_3 a_1

The creation operators will be always in ascending (kets) or descending (bras) order. In this way, if the partition is contiguous, then the operators you want to trace out in the ket will be in the same position that in the bra, unless the particle number is different. However, if the parity superselection rule (PSSR) is fulfilled, the difference between the number of operators in the ket and bra will be even, so the minus signs will compensate. As an example, lets suppose that I have this element

a_1^\dagger a_2^\dagger|vac.><vac.|a_4 a_3 a_2 a_1

and I want to trace out the mode labelled by 1. Then, I have to commute the a_1^\dagger and a_1 operators towards the vacuum projector. From the ket I will get a -1, but from the bra I will get other -1, which compensate. If PSSR is not fulfilled, then elements of the form 

a_1^\dagger a_2^\dagger|vac.><vac.|a_4 a_2 a_1

would be possible, and I would take a minus sign since the difference between the quantity of fermionic operators in the bra and ket sides would be odd. Fortunately, PSSR must be fulfilled in all fermionic states.

However, this discussion is valid when the partition is contiguous. The difference between fermions and qubits arise when the partition is not contiguous.

**Comment by javierfaba** [comment]
Hi,
I’ve working on a little homemade script in order to perform fermionic partial traces for my purposes, and I think sharing it might help. The idea is to perform a sign correction of the state before taking the partial trace as usual (i.e with the current quspin method). Here is the example given above with some functions defined in order to perform the sign correction in line 147 (before taking the current quspin partial trace).

[fermionic_partial_trace_example.txt](https://github.com/weinbe58/QuSpin/files/6285353/fermionic_partial_trace_example.txt)

I hope it helps!

**Comment by mgbukov** [comment]
Many thanks, @javierfaba ! 

We've been actively discussing the problem over the last few days and yesterday we fixed the bug in the [`sent_fermion` branch](https://github.com/weinbe58/QuSpin/tree/sent_fermion). We tested the fix with a [new test](https://github.com/weinbe58/QuSpin/blob/sent_fermion/tests/partial_trace_fermion_test.py) including random 2-site partitions (both contiguous and non-contiguous) on an L=4 site chain for both spinless and spinful fermions. 

There is one more issue to settle down before we can make the new release official thru anaconda, but in the meantime, you can pull the `sent_fermion` branch and install quspin manually in case you need the functionality.

**Comment by mgbukov** [comment]
This is now fixed in dev_0.3.6. 

Later this week, we will release quspin 0.3.6 and we will close this issue.
