### ISSUE TITLE
Faster way of computing reduced density matrix spectrum

### ISSUE THREAD

**Issue by niklasmueller1988** [weinbe58/QuSpin#406]
Hi folks,
I am wondering if there is a faster way of computing part of the spectrum of a reduced density matrix, and what actually takes the most time.

I have the following situation: Based on some Hamiltonian, I can compute the ground state for a fairly large system quite quickly. Then, I want to compute the reduced density matrix and find its eigenvalues. I am however perfectly fine with just
obtaining a few eigenvalues that are close to one. (the low energy part of the entanglement spectrum).

Below, I am attaching a code snippet using the 'standard' way that can be found in quspin's documentation.

I wonder if there is a shortcut here, i.e. converting the reduced DM (or the state or the log of the reduced DM) directly into some "Hamiltonian" and then using sparse techniques to get only the k lowest eigenvalues?

```
ent_entropy=spin_basis2D.ent_entropy(psi_i,sub_sys_A=subsystemA,\
return_rdm="A",density=True,enforce_pure=False,return_rdm_EVs=True,\
sparse=True,alpha=1.0,sparse_diag=True,subsys_ordering=True)
entropy=ent_entropy['Sent_A']       # von Neumann Entropy
rho_A=ent_entropy['rdm_A']          # reduced density matrix
p_A=ent_entropy['p_A']              # spectrum of reduced density matrix ("singular values")
```

**Comment by mgbukov** [comment]
have you tried using `basis.partial_trace()` to compute the reduced density matrix, and then using the sparse diagonalization routines in `scipy`?

**Comment by niklasmueller1988** [comment]
That is a great idea. Thanks, I will try it out and report.

**Comment by weinbe58** [comment]
Its also worth checking to see if your reduced density matrix is sparse, in which case you can set the option: sparse=True which will probably speed up the sparse diagonalization routine

**Comment by niklasmueller1988** [comment]
I think we can consider this closed. Thanks a lot. Using `basis.partial_trace()` and then sparse diagonalization routines of `scipy' made this lightning fast. I am using `sparse=True' and will also check out interpolate matrix decomposition to see if it helps even more.
