### ISSUE TITLE
Building a mixed spin Hamiltonian

### ISSUE THREAD

**Issue by qi-zakaria** [weinbe58/QuSpin#408]
Hello,

I am trying to simulate a 1D spin chain of alternating spins (1/2,1). When i try to compute the reduced density matrix, say \rho_{12}. the dimension of the outcome is (4,4) although it should be (6,6). It is as if the code treats the Hamiltonian as two blocks A and B, where A contains all the spin 1/2 and B contains all the spin 1, although my aim in an alternating (1/2,1).  I'm also suspecting the static lists I'm defining, I'm not sure whether I'm missing some terms.

![hamiltonian](https://user-images.githubusercontent.com/36313185/115270037-71cf2a80-a12b-11eb-8289-d44e28800e63.png)

Thanks in advance,

Here's the code I'm using : 

from quspin.operators import hamiltonian
from quspin.basis import tensor_basis, spin_basis_1d 
import numpy as n
def ham(N,J,h):
    
    basis_1= spin_basis_1d(L=N,S="1/2") 
    basis_2= spin_basis_1d(L=N,S="1")
    basis = tensor_basis(basis_1,basis_2)
    
    z_1=[[h,i] for i in range(N)]
    J_1=[[J,i,(i+1)%N] for i in range(N)]
    
    static=[["+|-",J_1],["-|+",J_1],["z|z",J_1],["|z",z_1],["z|",z_1]]
    dynamic=[]
    
    no_checks = dict(check_pcon=False,check_symm=False,check_herm=False)
    H=hamiltonian(static,dynamic,dtype=np.float64,basis=basis,**no_checks)
    E,V=H.eigsh(k=1,which='SA')
    return basis.ent_entropy(V)["Sent_A"]

**Comment by mgbukov** [comment]
I think you're defining your Hamiltonian correctly (apart from possibly some prefactors when expressing +/- operators interms of \sigma and S). 

However, you are correct that `tensor_basis` just stacks the Hilbert spaces together like two blocks, A=left (for spin-1/2) and B=right (for spin-1). You have to also use the `sub_sys_A` argument to specify the subsysem (or else quspin uses the default value). 

Unfortunately, using `tensor_basis` you can currently only trace out one entire species with the built-in functionality, i.e. you can trace out either the spin-1/2 or the spin-1 particle entirely, but not a subset of these. 

To do what you describe, you'd have to write your own `partial_trace` function: just keep in mind that a state in the full H-space `psi = [psi_left, psi_right]` where left/right correspond to the left/right argument of `tensor_basis`. You can reshape `psi_left = reshape((2,)*N)` [2 being the local H_left dimension for spin-1/2] and `psi_right = reshape((3,)*N)`, and then transpose according to your sub system of choice, and do the partial trace. 

It might also be possible to do this using the `user_basis`, but I'm not sure what's easier.

**Comment by weinbe58** [comment]
Marin is correct that currently there is no functionality that supports partial tracing of a mixed representation however the code required for this is not that difficult. This function below should hopefully do what you want. You I have checked that the resulting reduced density matrix is normalized but you should check to make sure that the reduced density matrix gives the same expectation value as the original pure state.

```python
import numpy as np

def partial_trace(psi,
                N_L,sps_L,sub_sys_A_L,
                N_R,sps_R,sub_sys_A_R,
                sort_sub_sys_A=True):
    """
    Parameters
    ----------
    
    psi: ndarray, 
        the pure state to partial trace
    N_L: int, 
        number of sites in left system
    sps_L: int, 
        number of states per site in left system
    sub_sys_A_L: array_like, 
        sub_sys_A for left sites
    N_R: int, 
        number of sites in right system
    sps_R: int, 
        number of states per site in right system
    sub_sys_A_R: array_like, 
        sub_sys_A for right sites
    sort_sub_sys_A: bool, optional
        sort the sites in sub_sys_A_L and sub_sys_A_R. Default is True.
        
    """
    sub_sys_A_L = list(sub_sys_A_L)
    sub_sys_B_L = list(set(range(N_L)) - set(sub_sys_A_L))

    sub_sys_A_R = list(sub_sys_A_R)
    sub_sys_B_R = list(set(range(N_R)) - set(sub_sys_A_R))
    
    if sort_sub_sys_A:
        sub_sys_A_L.sort()
        sub_sys_A_R.sort()
    
    sub_sys_A_L = tuple(sub_sys_A_L)
    sub_sys_B_L = tuple(sub_sys_B_L)
    sub_sys_A_R = tuple(sub_sys_A_R)
    sub_sys_B_R = tuple(sub_sys_B_R)
   
    # get H-space size of each segments
    Ns_L = sps_L**N_L
    Ns_R = sps_R**N_R
    Ns_A_L = sps_L**len(sub_sys_A_L)
    Ns_B_L = sps_L**len(sub_sys_B_L)
    Ns_A_R = sps_R**len(sub_sys_A_R)
    Ns_B_R = sps_R**len(sub_sys_B_L)
    
    # |psi> = sum_ij psi_ij |i>|j>
    psi = psi.reshape((Ns_L,Ns_R))
    
    # transpose left side
    R_tup = tuple(N_L*[sps_L]) + (sps_R**N_R,)
    T_tup = sub_sys_A_L+sub_sys_B_L
    T_tup = T_tup + (N_L,)
    psi = psi.reshape(R_tup)
    psi = psi.transpose(T_tup)
    psi = psi.reshape((Ns_A_L,Ns_B_L,Ns_R))
    
    # transpose right side
    R_tup = (Ns_A_L,Ns_B_L) + tuple(N_R*[sps_R])
    T_tup = sub_sys_A_R+sub_sys_B_R
    T_tup = (0,1)+tuple([2+s for s in T_tup])
    
    psi = psi.reshape(R_tup)
    psi = psi.transpose(T_tup)
    psi = psi.reshape((Ns_A_L, Ns_B_L, Ns_A_R, Ns_B_R))

    # move sub_sys_A to left index and sub_sys_B to right index
    psi = psi.transpose((0,2,1,3))
    # collapse to 1d index for sub_sys_A and B
    psi = psi.reshape((Ns_A_L*Ns_A_R, Ns_B_L*Ns_B_R))
    
    # trace out sub_sys_B
    # you can also use svd here to get eigenvalues of rho_A
    return np.matmul(psi,psi.T.conj())
```
