### ISSUE TITLE
ImportError: cannot import name get_matvec_function

### ISSUE THREAD

**Issue by liuyang0424** [weinbe58/QuSpin#411]
I'm totally new in learning QuSpin. I met the titled problem when i ran the example 17 (http://weinbe58.github.io/QuSpin/generated/quspin.tools.misc.matvec.html) and the example in the link http://weinbe58.github.io/QuSpin/generated/quspin.tools.misc.get_matvec_function.html?highlight=get_matvec_function#quspin.tools.misc.get_matvec_function, following installing the QuSpin via Anaconda on my Windows 10 PC.  

The console show:
runfile('D:/1_Trapped_Ion/Non-Hermitian/Lindblad equation/example17.py', wdir='D:/1_Trapped_Ion/Non-Hermitian/Lindblad equation')
Traceback (most recent call last):

  File "<ipython-input-6-aa100fcdd4af>", line 1, in <module>
    runfile('D:/1_Trapped_Ion/Non-Hermitian/Lindblad equation/example17.py', wdir='D:/1_Trapped_Ion/Non-Hermitian/Lindblad equation')

  File "C:\Users\Dell\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\Dell\Anaconda2\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 95, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "D:/1_Trapped_Ion/Non-Hermitian/Lindblad equation/example17.py", line 19, in <module>
    from quspin.tools.misc import get_matvec_function

ImportError: cannot import name get_matvec_function

I don't know how to fix this issue, and it would be really appreciated if anyone could give a help.

**Comment by weinbe58** [comment]
are you running the code through spyder?

**Comment by mgbukov** [comment]
has this issue been resolved?
