### ISSUE TITLE
Density matrix operator with QuSpin

### ISSUE THREAD

**Issue by GlebFedorovich** [weinbe58/QuSpin#413]
Hello, guys!

I have just started to work with QuSpin on 1D bosonic chain. So, I wonder, how I can calculate density matrix element (attached file as an example) if I have already found the ground state in Fock representation?

Thank you in advance
![Снимок экрана 2021-04-23 в 10 50 26](https://user-images.githubusercontent.com/36506433/115838072-f7035980-a421-11eb-932f-98fa4706e0a6.png)

**Comment by mgbukov** [comment]
Hi, you have to define the operator rho_ij = a^\dagger_i a_j using the [`hamiltonian`](https://weinbe58.github.io/QuSpin/generated/quspin.operators.hamiltonian.html#quspin.operators.hamiltonian) constructor setting the flag `check_herm=False`. This is done in the same way you would define the hopping term (just without the hermitian conjugate). You'd have to define one operator for every pair of sites (i,j). 

This will make `rho_ij` a `hamiltonian` object; then all you need to do is [`rho_ij.expt_value(psi)`](https://weinbe58.github.io/QuSpin/generated/quspin.operators.hamiltonian.html#quspin.operators.hamiltonian.expt_value) to compute the expectation.
 
Does this help?

**Comment by mgbukov** [comment]
I assume this has been resolved

**Comment by GlebFedorovich** [comment]
> Hi, you have to define the operator rho_ij = a^\dagger_i a_j using the [`hamiltonian`](https://weinbe58.github.io/QuSpin/generated/quspin.operators.hamiltonian.html#quspin.operators.hamiltonian) constructor setting the flag `check_herm=False`. This is done in the same way you would define the hopping term (just without the hermitian conjugate). You'd have to define one operator for every pair of sites (i,j).
> 
> This will make `rho_ij` a `hamiltonian` object; then all you need to do is [`rho_ij.expt_value(psi)`](https://weinbe58.github.io/QuSpin/generated/quspin.operators.hamiltonian.html#quspin.operators.hamiltonian.expt_value) to compute the expectation.
> 
> Does this help?

Yes, this method definitely help, thanks you a lot!
