### ISSUE TITLE
Expectation value of spins in AFM configuration

### ISSUE THREAD

**Issue by abhinsuresh** [weinbe58/QuSpin#415]
**Describe the Physics background**
1. I was computing the expectation value of spin-z operators at each site of the ground state eigen vector
of the spin Hamiltonian, where I came across this inconsistency.
When I use lanczos scheme(eigsh) to compute few eigenstates, the expectation value of spin operators
is not giving the right value (Hamiltonian with `J_xy=0` and `J_zz=0.1`, (regular scheme(eigh) gives (1,-1,1...))). The value in lanczos even changes each time I run it. Note that, eigen values are consistent, its just for the expectation values of spin at each site which gives wrong answers.

2. Also what is suggested way to generate spin operators in fock states (ie in spinful_fermion_basis), since in this basis as I know, currently support only `Cup^\dagger Cdn` type operators ? should I go on to generate
individual operator sets and then add them together, and in the case if I need product of four operators, I should multiply them with `*` ?

3. The spinful_basis_1d/general is not picking up one expected state, is that a bug or am I missing something
```python
basis_1d=spinful_fermion_basis_1d(N_2d,Nf=(4,0),a=1,kblock=0)
````
array index   /   Fock state   /   integer repr.
     0.         |1 1 1 1>|0 0 0 0>           240
This expected output is not generated while using kblock=0.
This is not the case for spin_basis.
**To Reproduce**
case 1
```python
from quspin.operators import hamiltonian 
from quspin.basis import spin_basis_1d
L = 4; J_xy=0; J_zz=0.1
basis=spin_basis_1d(L=L)
J_zz=[[Jz,i,(i+1)%L] for i in range(L)] # PBC
J_xy=[[J,i,(i+1)%L] for i in range(L)] # PBC
static=[["xx",J_xy],["yy",J_xy],["zz",J_zz]]
dynamic = []
H=hamiltonian(static,dynamic,dtype=np.float64,basis=basis)
#expectation value for each site
s = [['z', [[1.0, 0]]]]
sz0 = hamiltonian(s,dynamic,dtype=np.float64,basis=basis, check_symm=False)
s = [['z', [[1.0, 1]]]]
sz1 = hamiltonian(s,dynamic,dtype=np.float64,basis=basis, check_symm=False)
E,V = H.eigsh(0, k = 3, which='SA')
print(sz0.expt_value(V[:,0]))
print(sz1.expt_value(V[:,0]))
```

**Expected behavior**
case 1: returned values like -0.68, 0.68 and changed in each run
expected: -1, 1

**Desktop (please complete the following information):**
 - OS: windows, miniconda, jupyter notebook

**Comment by mgbukov** [comment]
1. It looks to me that your H has a degenerate GS. If that's the case, how do you guarantee that the eigenstates `V` are not some linear combination of the two antiferromagnetic ground states? If you supplement `eigsh()` with a different initial state for the Lanczos iterator you may also get other numbers in the interval [-1,1] for the expectation values because the solver may get stuck in a different superposition in the GS manifold.
2. There is no direct way to create spin operators for fermions: You can 
     (i) either use quartic operators as in this [test](https://github.com/weinbe58/QuSpin/blob/master/tests/sq_lat_Heis_double_occupancy_test.py), or 
     (ii) created your own operator strings using the `user_basis`, see for instance this [example for Gell-Mann operators](https://weinbe58.github.io/QuSpin/examples/example23.html#example23-label) and the [`user_basis` tutorial ](https://weinbe58.github.io/QuSpin/user_basis.html#user-basis-label). In fact, if you code (ii) up and you'd like to share your code with the community, we'd be happy to post it on the documentation website as a useful example :) 
3. for fermions the state |1111>|0000> does not obey the translation symmetry due to the fermion signs which arise when permuting fermions. It falls into another symmetry sector (try the other k-blocks and you'll find it there). In the spin basis, there are no signs so you find the state as you expect.

**Comment by abhinsuresh** [comment]
Thank you for the prompt reply, am trying to do light hitting on tj Hamiltonian. I will get back to you if I have further questions, thank you.
for spinful_fermion basis with spin operators I see that I need to give all the list of possible half filling states to create the basis like for `L = 4, Nf=((4,0), (0,4), (3,1)....).` I initially wrote my own code to do create basis and operators of the form `'+|-'` which would act on same site.
