### ISSUE TITLE
64 vs. 32 in user basis while forcing parallelization of pre-check state.

### ISSUE THREAD

**Issue by niklasmueller1988** [weinbe58/QuSpin#416]
This may entirely be due to me doing something stupid. So far I have used 'user_basis' with np.uint32 as data type
using the 'usual' trick to trigger parallelization when there are no symmetries.

```
@cfunc(map_sig_32) # or map_sig_64 for 64-bit integer
def ident_mapping(s,a,b,c):
    return s
ident_args=np.array([],dtype=np.uint32)
maps = dict(id_block=(ident_mapping,1,0,ident_args), )
basis = user_basis(np.uint32,N,op_dict,allowed_ops=set(allowed_ops_set),sps=Ns,pre_check_state=pre_check_state,Ns_block_est=Ns_physical_estimate,**maps)
```
However, when  try the same thing changing everything to 64bit
```
@cfunc(map_sig_64) 
def ident_mapping(s,a,b,c):
    return s
ident_args=np.array([],dtype=np.uint64)
maps = dict(id_block=(ident_mapping,1,0,ident_args), )
basis = user_basis(np.uint64,N,op_dict,allowed_ops=set(allowed_ops_set),sps=Ns,pre_check_state=pre_check_state,Ns_block_est=Ns_physical_estimate,**maps)
```
I get an error 
```
 @cfunc(map_sig_64) 
NameError: name 'map_sig_64' is not defined
```
This is weird, because looking at http://weinbe58.github.io/QuSpin/modules/quspin/basis/basis_general/base_user.html both map_sig_64 and map_sig_32 should be there. Do I need to change other things too? (I haven't changed pre_check_state and ops at all so far). Am I using an old version?

PS: a funny thing I encountered is that quspin actually didn't warn me that unit32 was too small for all the states in the basis. This may have been because the actual number of states surviving pre-check-state was much smaller. The result was that pre-check-states was checking the same states again when it had exhausted unit32 with the consequence that the identical state was admitted multiple times to the basis.

**Comment by niklasmueller1988** [comment]
And of course, I am doing something stupid! The 64 bit userbasis components must be included explicitly!
`from quspin.basis.user import user_basis,pre_check_state_sig_64,op_sig_64,map_sig_64`

**Comment by JiahaoYao** [comment]
Yes, you have to include the type import there. And I agree the `Ns_block_est` is int type.

**Comment by mgbukov** [comment]
> PS: a funny thing I encountered is that quspin actually didn't warn me that unit32 was too small for all the states in the basis. This may have been because the actual number of states surviving pre-check-state was much smaller. The result was that pre-check-states was checking the same states again when it had exhausted unit32 with the consequence that the identical state was admitted multiple times to the basis.

@niklasmueller1988: the `user_basis` is the most advanced functionality of quspin; in this case, we do not want to babysit the users and add extra checks on the datatypes of the integers, etc. Instead, we expect that the users understand the relevant concepts (see also the tutorial on the `user_basis` where we discuss various pitfalls). 

@niklasmueller1988: should we consider this isue resolved and close it?

**Comment by Niklas-Mueller1988** [comment]
Indeed. Issue resolved, please close. Thanks.
