### ISSUE TITLE
Merge of multiple  basis class 

### ISSUE THREAD

**Issue by mahaveer-thalor** [weinbe58/QuSpin#417]
I have multiple basis and would like to construct a single basis class of Hilbert space by merging these multiple basis. Please help me out how can i implement it in quspin.

**Comment by mgbukov** [comment]
Check out the [`tensor_basis`](https://weinbe58.github.io/QuSpin/generated/quspin.basis.tensor_basis.html#quspin.basis.tensor_basis) class.

If you need symmetries in between the bases, you can also try out the [`user_basis`](https://weinbe58.github.io/QuSpin/generated/quspin.basis.user_basis.html#quspin.basis.user_basis) class.

**Comment by mgbukov** [comment]
I assume this has been resolved.
