### ISSUE TITLE
Reagrding using tensor basis.

### ISSUE THREAD

**Issue by Sourav-physics** [weinbe58/QuSpin#430]
Hi,
I am trying to construct the Hamiltonian hosting both spinless fermions  and spin-1/2 DOFs given by 

$ H = -t \sum_{j} (c_{j}^{\dagger}c_{j+1}+ c_{j+1}^{\dagger}c_{j}) +
g \sum_{j} n_{j} S_{j}^{x}+
\omega \sum_{i} S_{j}^{z}+
J \sum_{j} S_{j}^{x} S_{j+1}^{x} + S_{j}^{y} S_{j+1}^{y} $

where S's are spin operators and c's are spinless fermions.

I am using the following code snippet:

from quspin.basis import spinless_fermion_basis_1d
from quspin.basis import spin_basis_1d, tensor_basis
from quspin.operators import hamiltonian

L, t, g, omega, J  = 8, 1.0, 2.0, 0.5, 1.5

basis1 = spinless_fermion_basis_1d (L, Nf = 1)
basis2 = spin_basis_1d (L, pauli=0)
basis = tensor_basis (basis1, basis2)
 
#---------couplings----------------#
fermion_hop = [[-t,i,i+1] for i in range (L-1)]              #OBC#
fermion_spin_both = [[g,i] for i in range (L)]
only_spin = [[omega,i] for i in range (L)]
spin_spin = [[J,i,i+1] for i in range (L-1)] #OBC#

static = [["+-|",fermion_hop],["-+|",fermion_hop],["|xx",spin_spin], ["|yy",spin_spin], ["|z", only_spin]\
, ["n|x", fermion_spin_both] ]
no_checks = dict(check_pcon=False,check_symm=False,check_herm=False)
Ham = hamiltonian (static,[],basis=basis,**no_checks)

With the above stuff I get the error message -'not enough indices for opstr in: n|x, (0,)'.  Could you please point out where I am going wrong in writing the fermion-spin coupled term and also point out how to correctly write such term.

**Comment by JiahaoYao** [comment]
First, for the `tensor_basis`, you can refer to http://weinbe58.github.io/QuSpin/generated/quspin.basis.tensor_basis.html. 

Second, you might need to change 
```python
fermion_spin_both = [[g,i] for i in range (L)]
```
to 
```python
fermion_spin_both = [[g,i,i] for i in range (L)]
```

**Comment by Sourav-physics** [comment]
Thanks

**Comment by JiahaoYao** [comment]
Thanks @Sourav-physics, if that works for you, would you please close this issue?
