### ISSUE TITLE
Unable to run quspin without GLIBC_2.17

### ISSUE THREAD

**Issue by GaneshChandra** [weinbe58/QuSpin#438]
I have installed quspin in my institute cluster, to which I don't have administrator privileges. I have created a virtual environment in the conda and installed quspin in it. Once I try to run "python example0.py" I am getting this error. 

```
python: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by python)
python: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by python)
python: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by python)
```

I tried to install GLIBC-2.18 in my local directory and added it to LD_LIBRARY_PATH. After that ls, ssh, and many such basic functions are giving

 `Segmentation fault (core dumped). `

I understood that GCC and this version of GLIBC are clashing. I have found this answer, [https://stackoverflow.com/a/44710599](url)which suggested to use,  patchelf, I tried installing using the steps in the, [https://github.com/NixOS/patchelf](url) which gave build-id.sh failed error in the "make check" stage. 

I want to know while compiling CPP code or C code, one can use, `-Wl, --rpath="/local/lib"`, is there a way to do the same with python. Please help with what to do to run the quspin code. 

 - OS:
 Distributor ID:	CentOS
Description:	CentOS release 6.7 (Final)
Release:	6.7
Codename:	Final

**Additional context**

**Comment by mgbukov** [comment]
This looks weird; are you sure it's not an issue with your python/conda
installation?

Have you tried installing miniconda from scratch in your local cluster home
directory?

The conda version of quspin uses precompiled CPP libraries so I guess any
issues with glib are related to your local conda/python installation or
environment.

Maybe it's worthwhile to contact the cluster administrator?

**Comment by GaneshChandra** [comment]
Thank you so much for the reply.

 I did a clean install of anaconda in my local home and it worked. I installed it with `conda install -c weinbe58 omp quspin` and once I ran it, it gave an error, 
`python: symbol lookup error: /local/anaconda3/lib/python3.8/site-packages/mkl/../../../libmkl_intel_thread.so.1: undefined symbol: omp_get_num_procs`

I had to do, `conda install --channel conda-forge llvm-openmp` to fix that and everything is working.

**Comment by mgbukov** [comment]
I am re-opening this so we can double-check the library dependencies for `llvm-openmp` before the next update.

**Comment by JiahaoYao** [comment]
Hi @GaneshChandra, this seems to be also mentioned [here](https://github.com/ContinuumIO/anaconda-issues/issues/10195).

**Comment by mgbukov** [comment]
new release is out; I'm closing this issue.
