### ISSUE TITLE
Example 17 not parallelized

### ISSUE THREAD

**Issue by j1ver** [weinbe58/QuSpin#491]
**Describe the bug**
The matvec function does not work with openmp in example 17. 

**Expected behavior**
Would expect a parallelized version as it is mentioned in the comments in this example.

**Additional context**
The example uses dense matrices. Does this only work with sparse ones?

**Comment by mgbukov** [comment]
Can you attach a minimal script (only the lines of code necessary to reproduce the bug)?

> The example uses dense matrices. Does this only work with sparse ones?

I think `matvec` should have am omp-speedup also for dense matrices.

**Comment by j1ver** [comment]
from __future__ import print_function, Division
import sys,os
os.environ['KMP_DUPLICATE_LIB_OK']='True' # uncomment this line if omp error occurs on OSX for python 3
os.environ['OMP_NUM_THREADS']='4' # set number of OpenMP threads to run in parallel
os.environ['MKL_NUM_THREADS']='4' # set number of MKL threads to run in parallel

from quspin.operators import hamiltonian, commutator, anti_commutator
from quspin.basis import spin_basis_1d # Hilbert space spin basis_1d
from quspin.tools.evolution import evolve
from quspin.tools.misc import get_matvec_function
import numpy as np
from six import iteritems # loop over elements of dictionary
import matplotlib.pyplot as plt # plotting library

L=1 # one qubit
delta=1.0 # detuning
Omega_0=np.sqrt(2) # bare Rabi frequency
basis=spin_basis_1d(L,pauli=-1) # uses convention "+" = [[0,1],[0,0]]

hx_list=[[Omega_0,i] for i in range(L)]
hz_list=[[delta,i] for i in range(L)]
static_H=[['x',hx_list],['z',hz_list]]

H=hamiltonian(static_H,[],basis=basis,dtype=np.float64)

matvec=get_matvec_function(H.static)

def Lindblad_EOM_v3(time,rho,rho_out):
	rho = rho.reshape((H.Ns,H.Ns)) # reshape vector from ODE solver input
	### Hamiltonian part
	# commutator term (unitary
	# rho_out = H.static.dot(rho))
	matvec(H.static  ,rho  ,out=rho_out  ,a=+1.0,overwrite_out=True)
	# rho_out -= (H.static.T.dot(rho.T)).T // RHS~rho.dot(H) 
	matvec(H.static.T,rho.T,out=rho_out.T,a=-1.0,overwrite_out=False)
	rho_out *= -1.0j
	return rho_out.ravel() # ODE solver accepts vectors only


EOM_args=(np.zeros((H.Ns,H.Ns),dtype=np.complex128,order="C"), ) # auxiliary variable rho_aux

t_max=6000.0
time=np.linspace(0.0,t_max,100001)
rho0=np.array([[0.5,0.5j],[-0.5j,0.5]],dtype=np.complex128)

rho_t = evolve(rho0,time[0],time,Lindblad_EOM_v3,f_params=EOM_args,iterate=True,atol=1E-12,rtol=1E-12) 









# 

I just made the time this long to be able to see via htop how many processes are running. I just get one.

**Comment by JiahaoYao** [comment]
I also confirm to have the same issue, it seems only one thread used. 

Note that I also check whether the version with OpenMP support has been installed , [link](https://weinbe58.github.io/QuSpin/Installation.html)

```
conda install -c weinbe58 omp quspin
```

**Comment by JiahaoYao** [comment]
By the way, the example is [here](http://weinbe58.github.io/QuSpin/generated/quspin.tools.misc.matvec.html) .

**Comment by j1ver** [comment]
This example cannot even work with csc/csr matrices, because the evolve function used ravel() that these types of matrices dont support, so it is not possible to check whether this would work then. In the evolve function one could just replace the ravel() by reshape(-1).

**Comment by mgbukov** [comment]
@j1ver we looked into this; indeed there is no omp speedup expected on this example, thanks for pointing it out! We'll fix this in the title of the example with the upcoming release. 

For the time being, you can check out [this example](https://weinbe58.github.io/QuSpin/examples/example22.html#example22-label) for an omp speedup.

**Comment by j1ver** [comment]
Okay, thank you @mgbukov .
The problem was that all other examples used wavefunctions. My problem requieres a density matrix, I need the entanglement. I solved it by used dot_product_mkl (at this time only could to real entries, so one needs to be careful) from [here](https://github.com/flatironinstitute/sparse_dot)  and wrote my own Runge Kutte 4 with a fixed step size. 

This is not the most robust way of doing it, especially with a fixed step size, but if you think it would help anyone else, I can do a minimal example.

**Comment by mgbukov** [comment]
If we can show in the example that we gain a (small) speedup compared to the naive implementation with dot and rdot on a laptop computer (say with 4-5 threads), then sure, we'd be happy to add it as an example to the list. We've already had one [contributed example](https://weinbe58.github.io/QuSpin/examples/example18.html#example18-label), so it'd be good to add a second one. 

For this purpose, can u prepare the code in a similar way to the scripts we have in the examples and send me a short txt file with the description that will appear online (you can use Latex there if you need to)? Thanks!

**Comment by j1ver** [comment]
Yes, I can do that! Where should I send the two files?

**Comment by mgbukov** [comment]
just upload them here (you need to give them both a .txt extension since github doesn't accept the .py extension).

**Comment by j1ver** [comment]
[description.txt](https://github.com/weinbe58/QuSpin/files/8397835/description.txt)
[quspin_runge.txt](https://github.com/weinbe58/QuSpin/files/8397836/quspin_runge.txt)

**Comment by mgbukov** [comment]
@j1ver I modified a little your code to make it use some quspin functionality for the initial state. 

I also did a comparison against pure scipy and it looks like pure scipy is faster than `dot_product_mkl` though. 

Code attached:

[quspin_runge.txt](https://github.com/weinbe58/QuSpin/files/8418656/quspin_runge.txt)

**Comment by mgbukov** [comment]
it might be possible to define such a basis using the `user_basis` class (see tutorial on quspin's website), but this requires extra work; from there the code for creating the initial rdm should be the same.

**Comment by j1ver** [comment]
Okay, I will look at it.
Regarding the speed, for a 2x2 lattice scipy is also faster for me, but for 2x3 or 3x3 and larger the mkl is faster for me.

**Comment by mgbukov** [comment]
@j1ver we briefly discussed your problem and realized that if you run the dynamics and measure the sparsity (# of nonzero entries divided by # of all entries) of the density matrix as a function of time, then it approaches a constant which is far from unity. This means that, for the given initial state, a large chunk of the Hilbert space remains inaccessible over time. It might be possible to reach much larger system sizes by figuring out how to get rid of these irrelevant dimensions ahead of time.

**Comment by j1ver** [comment]
Yes, I totally agree with that! 
Unfourtunately, I dont know a priori how to do check what parts are accessible and what are not. Do you have any idea?

**Comment by weinbe58** [comment]
Your Hamiltonian conserves both particle and total Sz, your initial state does not but you can project your initial density matrix into sectors defined by those quantum numbers and they should evolve independently.

**Comment by j1ver** [comment]
Oh yes, thank you! I will think about that.
