### ISSUE TITLE
Superfermion basis

### ISSUE THREAD

**Issue by 19danielw96** [weinbe58/QuSpin#498]
I am currently trying to create a superfermion basis, and to restrict its Hilbert space i.e. I have states of the form |n_1, n_2, ..., n_p> |k_1, k_2, ..., k_o>, where I want the difference of particles in the normal (first) and tilde (second) state to be equal (separately for spin up and down).
First I wanted to test if I can add states of different bases together, since I found this https://github.com/weinbe58/QuSpin/issues/217, where it is said that "So you can remove states from the basis; however you have to make sure you change both the basis._basis attribute and the basis._Ns characteristics of your basis object.", therefore I assumed this should also work for adding states, but it did not.

`from quspin.operators import hamiltonian,exp_op,quantum_operator # operators
from quspin.basis import tensor_basis,spinful_fermion_basis_1d
from quspin.tools.measurements import obs_vs_time # calculating dynamics
import numpy as np # general math functions
from numpy.random import uniform,choice # tools for doing random sampling
from time import time # tool for calculating computation time

L = 4

J = 0.5

U = 2.0

start, stop, num = 0.0, 35, 101

t = np.linspace(start,stop,num=num,endpoint=True)

basis = spinful_fermion_basis_1d(L, Nf = (0,0))

print(basis.blocks)

for i in range(5):
    for j in range(5):
        if i == 0 and j == 0:
            continue
        basis._basis = np.concatenate((spinful_fermion_basis_1d(L, Nf = (i,j))._basis, basis._basis))
        basis._Ns = basis._Ns + spinful_fermion_basis_1d(L, Nf = (i,j))._Ns

print(basis.blocks)

hop_right = [[-J,i,i+1] for i in range(L-1)] # hopping to the right OBC
hop_left = [[J,i,i+1] for i in range(L-1)] # hopping to the left OBC
int_list = [[U,i,i] for i in range(L)] # onsite interaction

static_fermion = [
    ["+-|", hop_left], # up hop left
    ["-+|", hop_right], # up hop right
    ["|+-", hop_left], # down hop left
    ["|-+", hop_right], # down hop right
    ["n|n", int_list], # onsite interaction
]

dynamic_fermion = []

H_fermion=hamiltonian(static_fermion,dynamic_fermion,basis=basis)
E_fermion=H_fermion.eigvalsh()
print(min(E_fermion))`

Thats my code where I try to recreate the full basis, but it just gives me an array of zeros for E_fermion.
I am currently reading into the user basis, but just thought maybe there's an easier way to fix this.

Any help would be much appreciated :)

**Comment by mgbukov** [comment]
great! I'm closing this issue then.
