### ISSUE TITLE
Floquet class returns UF corresponding to H.transpose() and not H

### ISSUE THREAD

**Issue by sRb-root** [weinbe58/QuSpin#513]
Hi,

I was not getting proper results while using the Floquet class. On checking in detail, it appears to me that the Floquet operator that is being returned corresponds to the transpose of the initial Hamiltonian, i.e, if the input Hamiltonian is H, it returns the Floquet operator corresponding to transpose(H).

For real Hamiltonians, this does not cause any issue but for complex Hamiltonians, the results are getting messed up. Here is my code (with XXZ chain):

CODE:
************************************************************************************************************************
`
from quspin.basis import spin_basis_1d
from quspin.operators import hamiltonian
from quspin.tools.Floquet import Floquet
from scipy.linalg import expm
import numpy as np

L = 8
Jxy=np.sqrt(2.0) # xy interaction
Jzz_0=1.0 # zz interaction
hz=1.0/np.sqrt(3.0) # z external field

mag_Jxy = -0.25
mag_Jz_nn = 1.0

basis = spin_basis_1d(L, pauli=False, kblock=1, zblock=1, Nup=L // 2)

Jxy = [[mag_Jxy, i, (i + 1) % L] for i in range(L)]
Jz_nn = [[mag_Jz_nn, i, (i + 1) % L] for i in range(L)]

static = [["+-", Jxy], ["-+", Jxy], ["zz", Jz_nn]]
dynamic=[]

H = hamiltonian(static,dynamic,basis=basis,dtype=np.complex64, check_symm=False, check_herm=False, check_pcon=False)

T = 0.01

Floq1 = Floquet({'H': H, 'T': T}, UF=True)
Floq2 = Floquet({'H': H.transpose(), 'T': T}, UF=True)

UF_with_H = Floq1.UF  #Floquet operator with H as input
UF_with_Htrans = Floq2.UF  #Floquet operator with transpose(H) as input

UF_exact = expm(-1j*H.todense()*T)  #Exact floquet operator

print("Difference with exact operator with H as input\n",np.round(UF_exact-UF_with_H, 3))
print("Difference with exact operator with transpose(H) as input\n", np.round(UF_exact-UF_with_Htrans, 3))
`
*********************************************************************************************************************************

OUTPUT:

Difference with exact operator with H as input
 [[ 0. +0.j     -0.004+0.j      0.-0.j]
 [ 0.004-0.j    -0 -0.j     0.004+0.j]
 [ 0. -0.j      -0.004-0.j     -0. +0.j]]

Difference with exact operator with transpose(H) as input
 [[ 0.-0.j  -0.-0.j  0.-0.j]
 [ 0.+0.j  -0.-0.j  0.+0.j]
 [ 0.-0.j   -0.-0.j -0.+0.j]]

***************************************************************************************************************************

As you can see, when the input to the Floquet class is just 'H', the output does not match with explicit calculations. But it matches perfectly when input is 'H.transpose()'

Please let me know if I am doing anything wrong. My OS is Ubuntu 20.04.

Best regards,
Sourav Bhattacharjee

**Comment by mgbukov** [comment]
Thanks, this is indeed a bug with stacking the basis vectors together into the Floquet unitary. It will be fixed in the new release.

**Comment by mgbukov** [comment]
this is fixed in quspin 0.3.7
