### ISSUE TITLE
Parallelization while creating Lindblad operator

### ISSUE THREAD

**Issue by 19danielw96** [weinbe58/QuSpin#522]
I installed the version of quspin that supports opm, and i want to create the Lindbladian using the hamiltonian class.
This works, and it also shows me that during creating there is 100% CPU usage, however, it still takes as long to create the respective sparse matrix as it would using just a single core.
I am running this:
hamiltonian(static, dynamic, basis = basis, dtype = np.complex128)
and before importing quspin I wrote:
os.environ['KMP_DUPLICATE_LIB_OK']='True'
os.environ['OMP_NUM_THREADS']='12'
os.environ['MKL_NUM_THREADS']='12'

I dont understand what I am doing wrong here. Would really appreciate advice/help.

**Comment by mgbukov** [comment]
How big is your Hilbert space/basis size? If the matrix size is too small, no omp parallelization can be used because the usual dense matrix multiplication is more efficient. Can you post your code?

Note that the omp parallelization is mostly used for creating the basis and for using the hamiltonian matrix in matrix-vector products, etc. 

@weinbe58 do we have omp speedup when computing the matrix elements?

**Comment by 19danielw96** [comment]
Well the setup where it becomes relevant is ~40000 or larger.
Yeah sure, but probably better to share the files.
https://cloud.tugraz.at/index.php/s/9cN35jaGZ2KTLAT
https://cloud.tugraz.at/index.php/s/omG2Fk4edtmyz4X
Ok I see, I kinda thought so after reading through the documentation in that regard, but since it also uses 100% CPU when creating the matrix I assumed it should also help there, what else would it use all the CPU for?
I found a sort of work around though -> I use joblib to split up my operators in equal parts and then (using the "threading" option, because otherwise it has pickling issues) let each thread work on a chunk. This sped up the process. Also it seemed to me that for this it was advantageous to use the single threaded version of quspin.
Oh and thank you for the fast response!

**Comment by weinbe58** [comment]
> @weinbe58 do we have omp speedup when computing the matrix elements?

@mgbukov yes, but if there are a bunch of operators strings the code can be slow due to the large number of operators you have to create.

**Comment by 19danielw96** [comment]
Yes there's actually a huge amount of operators, so I guess then that's the reason!
Thank you for letting me know.

**Comment by mgbukov** [comment]
@19danielw96 did this issue get resolved?

**Comment by 19danielw96** [comment]
Yes kinda, as mentioned before i used joblib, and if anyone has a similar problem i recommend a splitting of operators into more pieces then u have threads, (if whosoever also has huge amount of operators) I used 5*number of threads which sped up the process a lot so not just compared to no multithreading but also to just splitting into number of threads pieces.
