### ISSUE TITLE
Magnetization conservation violation and energy decaying to ground state energy.

### ISSUE THREAD

**Issue by juanjq** [weinbe58/QuSpin#531]
**Describe the bug**
Evolving an state violates magnetization conservation. With the XX Hamiltonian + transverse field, that is a Hamiltonian that commutes with the magnetization operator, [H,M]=0, when time evolving a state it doesn't conserve magnetization. Looking at the energies if we time evolve a eigenstate for example, no matter which excited level is, the energy of the evolved state will decay to the ground state energy
**To Reproduce**

We set the parameters and the Hamiltonian, (tested the parameters in a wide range and have the same behavior),
```
import matplotlib.pyplot as plt
import numpy             as np
from quspin.operators import hamiltonian  
from quspin.basis     import spin_basis_1d   

#PARAMETERS
N  = 6
j0 = 1
h0 = 1
v0 = 0.1
dt = 0.01

def ramp(t):    #evolution function
    return v0*t

times = [dt*i for i in range(4000)] #times vector

#XX + transverse field Hamiltonian
basis = spin_basis_1d(N,pauli=False) 

J1 = [[j0,i,i+1] for i in range(N-1)]
hz = [[h0,i]     for i in range(N)  ]

static  = [["+-",J1],["-+",J1]]
dynamic = [["z",hz,ramp,[]]]

HXX_tr = hamiltonian(static,dynamic,basis=basis,dtype=np.float64,check_symm=False)
    
#magnetization matrix
m = [[1,i] for i in range(N)]
staticM = [["z",m]]
M = hamiltonian(staticM,[],basis=basis,dtype=np.float64,check_symm=False)
```
Now we do the calculus,
```
#initial state as a only one basis component
E,init = HXX_tr.eigsh(time=0,k=1,which="SA",maxiter=1E4)
init   = init.reshape(-1)

#evolved vector for each time
evolved = np.transpose(HXX_tr.evolve(init,0,times,imag_time=True))

MAG_evolved = []
MAG_ground  = []
EN_evolved = []
EN_ground  = []

#calculus for each time
for i in range(len(times)):
    
    E,v = HXX_tr.eigsh(time=times[i],k=1,which="SA",maxiter=1E4) #exact Hamiltonian solve
    v = v.reshape(-1)
    
    MAG_evolved.append(np.dot(np.dot(np.conj(evolved[i]),M.toarray()),evolved[i]))
    MAG_ground.append(np.dot(np.dot(np.conj(v),M.toarray()),v)) #exact ground magnetization

    EN_evolved.append(np.dot(np.dot(np.conj(evolved[i]),HXX_tr.toarray(time=times[i])),evolved[i])[0,0])
    EN_ground.append(E[0]) #exact ground energy

```
And we can plot the results,
```
#magnetization plot
plt.plot(times,MAG_evolved,label='Evolved state mag')
plt.plot(times,MAG_ground,label='Ground state mag')
plt.title('Magnetization evolution')
plt.legend()
plt.xlabel('t')
plt.ylabel('M')
plt.show()

#energy plot
plt.plot(times,EN_evolved,label='Evolved state E')
plt.plot(times,EN_ground,label='Ground state E')
plt.title('Energy evolution')
plt.legend()
plt.xlabel('t')
plt.ylabel('E')
plt.show()
```

**Expected behavior**
We expect to first of all the conservation of the magnetization of the evolved state. We can also expect small errors due to numerical calculus, but with this big jump that we see in magnetization the error could come from other source. Also if we look at the energy, for some reason with a high jump is going to the ground state, and this happens for any eigenstate of the Hamiltonian, and what should happen is that the energy of the eigenstate remains similar to the initial.

**Screenshots**
The plots of the evolved state and ground state magnetizations, where we can see that is not conserved,
</p>
<p align="center">
    <img align="center" src="https://github.com/juanjq/matrixes/blob/main/data/Mag.png?raw=true">
</p>
And the same for the energy, where we can see the decay,
</p>
<p align="center">
    <img align="center" src="https://github.com/juanjq/matrixes/blob/main/data/En.png?raw=true">
</p>

**Desktop (please complete the following information):**
Tested in linux using jupyter notebook and also tested using only conda, as a python script

**Additional context**
The problem seems to be related to the evolve function. So if I'm not doing anything wrong and you don't know if this is actually an error. Is in some place explained how the evolve function works theoretically? Or the method used in the time evolution?

**Comment by juanjq** [comment]
I used the 'bug' label but actually it possibly can be seen more as a physics bug... So If do you want you can change the label, because I think I can't.

**Comment by weinbe58** [comment]
My guess is there is probably some non-zero amplitude on the wave function in the other magnetization sectors due to rounding errors when you solve for the initial state. As you evolve in imaginary time those amplitudes grow and because the evolve function normalizes the state, the prop ability shifts away from M=0 to the other sectors. 

I’m gonna double check this later but I am almost certain that is what is happening.

**Comment by juanjq** [comment]
Okay I see, so as I have understand in this case will be better to use `imag_time=False`, and check the normalization after evolving. And if normalization has not preserved re-normalize the vectors after the process.

I will check the behavior with more detail and after that I will say something here.

Thanks!!

**Comment by mgbukov** [comment]
Did this issue get resolved in the meantime?

**Comment by juanjq** [comment]
Sorry for the delay,

Yes if you don't use imaginary time the other magnetization sectors have no influence in the state, I tested and is consistent with the things we expect theoretically. So in the case the normalization was not well conserved you can simply after the time evolution normalize manually the vectors.

Thanks for the help!,Very thankful!
