### ISSUE TITLE
support of the sparse matrix

### ISSUE THREAD

**Issue by JiahaoYao** [weinbe58/QuSpin#532]
it seems that [project_to](https://github.com/weinbe58/QuSpin/blob/master/quspin/basis/basis_general/base_general.py#L561-L563) does not support the sparse vector, and it seems that the simplest solution is to convert the sparse vector to dense vectors, like `to_dense` or `to_array`. I wonder whether the current version does not support it because we do not know the dimension of the vector a-prior?

**Comment by JiahaoYao** [comment]
Another thought for the projection of the quantum state: the state after the projection is not normalized? Maybe it would be good to add the normalization argument?

**Comment by JiahaoYao** [comment]
One more thought: we might not always want to project to full basis, usually from `basisA` to `basisB` with different symmetric. I am writing the following helper function: 

```python
    def from_basisA_to_basisB(basisA, basisB, psi): 
        psi1 = basisA.project_from(psi,sparse=False)
        psi2 = basisB.project_to(psi1,sparse=False)
        return psi2
```

@mgbukov do you think the usecase of this want be larger? is this a good feature to support in `quspin`?

**Comment by weinbe58** [comment]
There should be a straight forward way of implementing the sparse version of up to the full basis but projecting down is more tricky.

As for the projector between two symmetry sectors, it's mostly used when breaking a symmetry with an operator. Again this is a long term goal I have had in mind but it's a bit tricky to implement given it involves two basis objects at the same time but not impossible.

**Comment by JiahaoYao** [comment]
i see, thanks @weinbe58
