### ISSUE TITLE
Wrong sign with spinful_fermion_basis_1d tunneling matrix elements

### ISSUE THREAD

**Issue by Davtax** [weinbe58/QuSpin#537]
**Describe the Physics background**
I am working with a Fermi-Hubbard model. To reproduce the sign problem with the tunneling matrix elements we will keep the system as small as possible (only two sites), and neglect the Coulomb interaction. The Hamiltonian reads

![](https://latex.codecogs.com/svg.image?H=-t\sum_\sigma&space;(c_{1\sigma}^\dagger&space;c_{2\sigma}&space;&plus;&space;c_{2\sigma}^\dagger&space;c_{1\sigma}))

Since the Hamiltonian preserves the total spin, when working with two particles, we will restrict ourselves to the spin=0 projection manifold. The phases for the tunneling matrix elements seem to be right when working with just one particle. However, moving to a two-particle system, the Hamiltonian is wrong.

In the next section, we will compute "by hand" some matrix elements, for which we will be used the anticommutation relations of fermions, given by
![](https://latex.codecogs.com/svg.image?%5Cleft%5C%7B%20c_%7Bi%7D,%20c_%7Bj%7D%20%5Cright%5C%7D%20=%20%5C%7B%20c_%7Bi%7D%5E%5Cdagger,%20c_%7Bj%7D%5E%5Cdagger%20%5C%7D%20=%200)
![](https://latex.codecogs.com/svg.image?%5C%7B%20c_%7Bi%7D%5E%5Cdagger,%20c_%7Bj%7D%20%5C%7D%20=%20%5Cdelta_%7Bij%7D)

We also need to use the states in second quantization, e.g.,
![](https://latex.codecogs.com/svg.image?|\uparrow,&space;\downarrow&space;\rangle&space;=&space;c_{1\uparrow}^\dagger&space;c_{2\downarrow}^\dagger&space;|\o&space;\rangle)
where |ø> represents the vacuum state, with no particles.

**To Reproduce**

The following code is common for both cases (one particle and two particles).
```
import numpy as np
from quspin.basis import spinful_fermion_basis_1d
from quspin.operators import hamiltonian

L = 2
t = 1

t_left = [[-t, i + 1, i] for i in range(L - 1)]
t_right = [[-t, i, i + 1] for i in range(L - 1)]

static = [["+-|", t_left],  # spin up, left
          ["|+-", t_left],  # spin down, left
          ["+-|", t_right],  # spin up, right
          ["|+-", t_right],  # spin down, right
         ]
````

The basis order of the one-particle case is {|↑, 0>, |0, ↑>, |↓, 0>, |0, ↓>}
```
# One particle
basis = spinful_fermion_basis_1d(L=L, Nf=[(1, 0), (0, 1)])
H1 = hamiltonian(static, [], basis=basis, check_symm=False)
print(H1.toarray().real)
```
The output of the above code is 
[[ 0. -1. -1.  0.]
 [-1.  0.  0. -1.]
 [-1.  0.  0. -1.]
 [ 0. -1. -1.  0.]]

For two particles, the basis in the spin 0 manifold is written as {|↑↓, 0>, |↑, ↓>, |↓, ↑>, |0, ↑↓>}
```
# Two particles
basis = spinful_fermion_basis_1d(L=L, Nf=[(1, 1)])
H2 = hamiltonian(static, [], basis=basis, check_symm=False)
print(H2.toarray().real)
```
[[ 0. -1. -1.  0.]
 [-1.  0.  0. -1.]
 [-1.  0.  0. -1.]
 [ 0. -1. -1.  0.]]

**Expected behavior**
The Hamiltonian for the single-particle case is correct. However, some of the matrix elements for two particles miss a minus sign. Here I show the explicit derivation of the matrix elements form |↑↓, 0>. Other elements can be obtained by imposing hermiticity of the Hamitlonian.

![](https://latex.codecogs.com/svg.image?\langle&space;\uparrow&space;\downarrow,&space;0|H|\uparrow,&space;\downarrow\rangle&space;=&space;\langle&space;\o&space;|c_{1\downarrow}c_{1\uparrow}(-tc_{1\downarrow}^\dagger&space;c_{2\downarrow})c_{1\uparrow}^\dagger&space;c_{2\downarrow}^\dagger&space;|\o&space;\rangle&space;=&space;-t)

![](https://latex.codecogs.com/svg.image?\langle&space;\uparrow&space;\downarrow,&space;0|H|\downarrow,&space;\uparrow\rangle&space;=&space;\langle&space;\o&space;|c_{1\downarrow}c_{1\uparrow}(-tc_{1\uparrow}^\dagger&space;c_{2\uparrow})c_{1\downarrow}^\dagger&space;c_{2\uparrow}^\dagger&space;|\o&space;\rangle&space;=&space;t)

Completing the Hamiltonian, in its matrix from it should looks like
[[ 0. -1. 1.  0.]
 [-1.  0.  0. -1.]
 [ 1.  0.  0.  1.]
 [ 0. -1. 1.  0.]]

**Desktop**
 - OS: Windows10

**Comment by weinbe58** [comment]
This is probably not a bug, we are using a different convention for the ordering of the fermion operators. 

We treat the spinful fermion with N sites as spinless fermions with 2N sites. The first/last N sites correspond to the up/down fermions. We order the states in descending order with respect to the spinless fermion sites.

**Comment by Davtax** [comment]
Hi @weinbe58, thanks for your reply.
The ordering of the fermionic operators should not play any role when computing the hamiltonian matrix elements. As long as the convention is consistent during all the calculations, the same results should yield independent of the chosen convention.

**Comment by weinbe58** [comment]
Indeed the order is arbitrary but it does in fact change the matrix elements because the change of order is a unitary transformation. If you check the spectrum of these two matrices they match hence the physics is the same.

**Comment by Davtax** [comment]
Ok, I think that now I understand the problem. Under our respective conventions, there is a minus sign in the $|\downarrow, \uparrow\rangle$ state.  The change of basis matrix relating both Hamiltonians as $H'=VHV^{-1}$ should read $V=\mathrm{diag}(1, 1, -1, 1)$. 

However, I find the convention followed in QuSpin a little bit counterintuitive. For example, take the basis ordering given by 
```
from quspin.basis import spinful_fermion_basis_1d
basis = spinful_fermion_basis_1d(L=2, Nf=[(1, 1)])
print(basis)

# Output
reference states: 
array index   /   Fock state   /   integer repr. 
     0.         |1 0>|1 0>           10  
     1.         |1 0>|0 1>            9  
     2.         |0 1>|1 0>            6  
     3.         |0 1>|0 1>            5 
```
To shorten the notation I will be using $|i\rangle$ for the state given by the $i$ array index. If we want to work with the molecular basis, instead of the atomic basis, we write $|T_0\rangle = (|1\rangle - |2\rangle)/\sqrt{2}$ and $|S\rangle = (|1\rangle + |2\rangle)/\sqrt{2}$. Even if this way of writing the molecular basis is correct, it differs from the usual way of defining the basis change (see [Triplet_state](https://en.wikipedia.org/wiki/Triplet_state)).

In any case, this is just a convention and not a bug, so I will close the issue. Thanks for our help @weinbe58.
