### ISSUE TITLE
entanglement entropy density definition

### ISSUE THREAD

**Issue by JiahaoYao** [weinbe58/QuSpin#538]
This is a nice-to-have enhancement, and it might be unnecessary or just for my information. (**Aside**: just try to see the support of math in github.)

------

It would be nice to add in the [docs](http://weinbe58.github.io/QuSpin/generated/quspin.basis.spin_basis_1d.html#quspin.basis.spin_basis_1d.ent_entropy) the Renyi entanglement entropy approaches the Von Neumann entanglement entropy if $\alpha=1$.

$$S\_\\mathrm{ent}(\\alpha)=\\frac{1}{N}\\frac{1}{1-\\alpha}\\log \\mathrm{tr}\_{A} \\left( \\mathrm{tr}\_{A^c} \\vert\\psi\\rangle\\langle\\psi\\vert \\right)^\\alpha$$

when $\alpha=1$, 

$$S\_\\mathrm{ent}(\\alpha=1)=-\\frac{1}{N}\operatorname{tr}\_{A}\rho\_A\log\left(\rho\_A\right), \qquad \rho_A = \operatorname{tr}\_{A^{c}}|\psi\rangle\langle\psi|$$

**Comment by mgbukov** [comment]
just added this to the doc; it should show up with the next release.

**Comment by JiahaoYao** [comment]
awesome, thanks!
