### ISSUE TITLE
`to_hamiltonian` for time dependent hamiltonian

### ISSUE THREAD

**Issue by JiahaoYao** [weinbe58/QuSpin#542]
https://github.com/weinbe58/QuSpin/blob/master/quspin/operators/hamiltonian_core.py#L1522-L1558 shows the methods like `to_csc()`, `to_array()` with the option of `time=t`. One might be also interested in `to_hamiltonian(time=t)`, which returns a `hamiltonian` class at some specific time point. 

This would be easy to implement, by evaluating the dynamic list at the specific points and adding them to the static list, and building a hamiltonian class. I can create a PR to this issue.

**Comment by weinbe58** [comment]
This already exists. You can call the Hamiltonian like a function and it will return a matrix which is the sum of all the pieces.

**Comment by JiahaoYao** [comment]
AMAZING, THIS IS SO COOL! thanks @weinbe58!

**Comment by JiahaoYao** [comment]
For other people's reference, the implement is [here](https://github.com/weinbe58/QuSpin/blob/master/quspin/operators/hamiltonian_core.py#L2060-L2077)
