### ISSUE TITLE
JQ hamiltonian not working

### ISSUE THREAD

**Issue by tkhouw** [weinbe58/QuSpin#58]
`from quspin.basis.transformations import square_lattice_trans
from quspin.basis import spin_basis_general
from quspin.operators import hamiltonian
import numpy as np

J = 1
Q = 0

Lx=4
Ly=4
N = Lx*Ly
tr = square_lattice_trans(Lx,Ly)

Z = [-(i+1) for i in range(N)]

basis = spin_basis_general(Lx*Ly,Nup=N//2,pauli=True,kx=(tr.T_x,0),ky=(tr.T_y,0),py=(tr.P_y,0),px=(tr.P_x,0),zb=(Z,0))
#basis_full = spin_basis_general(Lx*Ly,Nup=N//2,pauli=True)

print(basis.Ns)
#print(basis_full.Ns)

for i in range(N):
    print("T_x[",i,"] = ",tr.T_x[i])
    print("T_y[",i,"] = ",tr.T_y[i])

Jay = [[J-Q/2,i,tr.T_x[i]] for i in range(N)]#int(i/Lx)*Lx + (i+1)%Lx] for i in range(N)]
Jay.extend([J-Q/2,i,tr.T_y[i]] for i in range(N))#(i+Lx)%N] for i in range(N))

Cue11 = [[Q,i,tr.T_y[i],tr.T_x[i],tr.T_y[tr.T_x[i]]] for i in range(N)]
Cue11.extend([Q,i,tr.T_x[i],tr.T_y[i],tr.T_x[tr.T_y[i]]] for i in range(N))
#CueE = [[Q,i,tr.T_x[i],tr.T_y[i],tr.T_x[tr.T_y[i]]] for i in range(N)]

static = [["xx",Jay],["yy",Jay],["zz",Jay],["xxxx",Cue11],["xxyy",Cue11],["xxzz",Cue11],["yyxx",Cue11],["yyyy",Cue11],["yyzz",Cue11],["zzxx",Cue11],["zzyy",Cue11],["zzzz",Cue11]]#,["xxxx",CueE],["xxyy",CueE],["xxzz",CueE],["yyxx",CueE],["yyyy",CueE],["yyzz",CueE],["zzxx",CueE],["zzyy",CueE],["zzzz",CueE]]

H = hamiltonian(static,[],basis=basis,dtype=np.float64,check_pcon=True)
#H_full = hamiltonian(static,[],basis=basis_full,dtype=np.float64)
#[E2],_= H.eigsh(k=1,which="SA")
#[E1],_= H_full.eigsh(k=1,which="SA")

[E,V] = H.eigsh(k=1,which="SA")
#print("E",E)
print("V",V)

#assert(np.abs(E2-E1)<1.1e-10)

#Spin correlation operator:
olly = [[1.0,i,tr.T_x[tr.T_x[i]]] for i in range(N)]
olly.extend([1.0,i,tr.T_y[tr.T_y[i]]] for i in range(N))
op_list = [["zz",olly]]
O = hamiltonian(op_list,[],basis=basis,dtype=np.float64)
print((V.T).dot(O.dot(V))) #expectation value
print(E)
`
I've been trying to use the above code to calculate energies and spin correlations for the 2D JQ model.  The program's output changes depending on whether or not I have two separate lists for the Q interaction or just one list.  When I have two separate lists for the Q interaction (Cue11 and CueE, shaped like || and = respectively), the program seems to work fine except it returns a much-lower-than-expected energy for the ground state.  However, when I include both types of bonds in Cue11 (|| and =), quspin warns me that my hamiltonian does not conserve particle number, but I believe that the JQ interaction should conserve particle number.  Ignoring this warning (via check_pcon=False) results in a seemingly trustworthy ground state energy that does not match the low energy from before.

Finally there is an issue when I set Q=0 and I have both Cue11 and CueE as two separate lists in the hamiltonian.  I get this error message: 

Traceback (most recent call last):
  File "JQ_attempt.py", line 35, in <module>
    H = hamiltonian(static,[],basis=basis,dtype=np.float64,check_pcon=True)
  File "/usr3/graduate/tkhouw/.conda/envs/default/lib/python3.6/site-packages/quspin/operators/hamiltonian_core.py", line 304, in __init__
    self._static=make_static(self._basis,static_opstr_list,dtype)
  File "/usr3/graduate/tkhouw/.conda/envs/default/lib/python3.6/site-packages/quspin/operators/_make_hamiltonian.py", line 98, in make_static
    _consolidate_static(static_list)
  File "/usr3/graduate/tkhouw/.conda/envs/default/lib/python3.6/site-packages/quspin/operators/_make_hamiltonian.py", line 44, in _consolidate_static
    _consolidate_bonds(static_list[i][1])
  File "/usr3/graduate/tkhouw/.conda/envs/default/lib/python3.6/site-packages/quspin/operators/_make_hamiltonian.py", line 18, in _consolidate_bonds
    if bonds[i][1:] == bonds[j][1:]:
IndexError: list index out of range

However, I do not receive this message when I have just one list (Cue11) as the full Q interaction.  In fact, quspin does not warn me about particle conservation in this case when Q=0.

[JQ_attempt.txt](https://github.com/weinbe58/QuSpin/files/1325562/JQ_attempt.txt)

**Comment by weinbe58** [comment]
Thanks for sending me this! I can't work on it today but I will try to get to it sometime this weekend.

Phil
