### ISSUE TITLE
Error "ValueError: state must be representive state in basis." when increasing system size

### ISSUE THREAD

**Issue by speotta** [weinbe58/QuSpin#596]
The following error is raised when I increase the system size in the code below

>  File "./basis_test.py", line 35, in <module>
    i0 = basis.index(s_up, s_down)
>
>  File "/home/bastian/anaconda3/lib/python3.8/site-packages/quspin/basis/basis_general/fermion.py", line 696, in index
    raise ValueError("state must be representive state in basis.")
>
>ValueError: state must be representive state in basis.

The error occurs when the system size is larger then 32. I am working with an Ubuntu 22.04.1 LTS operating system and I use anaconda. Here is the code that generates the error

```python
from quspin.basis import spinful_fermion_basis_general

N_sites = 33 # number of lattice sites, specifies the system size
# the error occurs for N_sites > 33 in my computer
Nu = 2 # number of spin up particles
Nd = 1 # number of spin down particles

print('Number of lattice sites: {:d}'.format(N_sites))

site1_id = 14
site2_id = 15

basis = spinful_fermion_basis_general(N_sites, Nf=(Nu, Nd))

s_up = ''
s_down = ''
for ii in range(N_sites):
    if ii == site1_id:
        s_up += '1'
        s_down += '1'
    elif ii == site2_id:
        s_up += '1'
        s_down += '0'
    else:
        s_up += '0'
        s_down += '0'
print(s_up)
print(s_down)
i0 = basis.index(s_up, s_down)
print(i0)
```
The problem occurs when I use the basis.index method. The code above is so simple that I don't I think I am doing something wrong. In particular it works well for smaller system sizes `N_sites <= 32`. Solving this problem would be very useful for me since I would be able to perform the exact diagonalization of larger systems, which would be important for my current project.

Thanks in advance for your help!

**Comment by weinbe58** [comment]
This is because L=33 doesn't fit into uint64 datatype. we use larger integer representations inside the general basis and it looks like there is a bug. 


I will try to see what's going on, in the mean time you can use `spinful_fermion_basis_1d` which works here.

**Comment by weinbe58** [comment]
this should be a viable work-around until the next release:

```python


from quspin.basis.basis_general._basis_general_core.general_basis_utils import _get_basis_index

s_up = int(s_up,2)
s_down = int(s_down,2)

s = s_down + (s_up << (N_sites) )
i0 = _get_basis_index(basis.states,s)
print(i0)

```

**Comment by speotta** [comment]
The suggested work-around works for me. I was able to run the time evolution from an initial Fock state selected using the above code snippet in a system much larger then before. This is very helpful for my work.
I look forward for the release of the next version!
