### ISSUE TITLE
Error message: ImportError: cannot import name spin_basis_general

### ISSUE THREAD

**Issue by stefDeNicola** [weinbe58/QuSpin#62]
I have downloaded example9.py from the website and tried to run it without making any changes to it. However, I get the following error message:

File "example9.py", line 3, in <module>
  from quspin.basis import spin_basis_1d, spin_basis_general # spin basis constructor
ImportError: cannot import name spin_basis_general

I have downloaded QuSpin using the automatic installation via conda, and I think I have the most updated version. If I run:

conda install -c weinbe58 quspin

I get:

Fetching package metadata .............
Solving package specifications: .
# All requested packages already installed.
# packages in environment at /Users/stefanodenicola/anaconda2:
# quspin                    0.2.3                    py27_0    weinbe58

Where could the problem come from?

**Comment by weinbe58** [comment]
Yes sorry 0.2.3 doesn't support spin_basis_general. What platform are you running? We're updating quspin today and if you're running Linux and python 2.7 you can just update using 'conda update -c weinbe58 quspin'

**Comment by stefDeNicola** [comment]
Many thanks, I tried running example 9 today on 0.2.6 and it worked.
Kind regards

Stefano

**Comment by weinbe58** [comment]
Great!
