### ISSUE TITLE
problem with installing quspin 0.2.7 on ubuntu 17.10

### ISSUE THREAD

**Issue by aadonkov** [weinbe58/QuSpin#77]
Dear Developers, 
after updating to 0.2.7 and running the example3.py I get the error message listed below.
thank you,
alex
--------
aad@theory3:~/QuSpin$ python example3.py 
Traceback (most recent call last):
  File "example3.py", line 8, in <module>
    from quspin.basis import spin_basis_1d,photon_basis # Hilbert space bases
  File "/home/aad/anaconda3/lib/python3.6/site-packages/quspin/__init__.py", line 3, in <module>
    from . import operators
  File "/home/aad/anaconda3/lib/python3.6/site-packages/quspin/operators/__init__.py", line 52, in <module>
    from .hamiltonian_core import *
  File "/home/aad/anaconda3/lib/python3.6/site-packages/quspin/operators/hamiltonian_core.py", line 3, in <module>
    from ..basis import spin_basis_1d as _default_basis
  File "/home/aad/anaconda3/lib/python3.6/site-packages/quspin/basis/__init__.py", line 66, in <module>
    from .basis_general import *
  File "/home/aad/anaconda3/lib/python3.6/site-packages/quspin/basis/basis_general/__init__.py", line 1, in <module>
    from .spin import spin_basis_general
  File "/home/aad/anaconda3/lib/python3.6/site-packages/quspin/basis/basis_general/spin.py", line 1, in <module>
    from .base_hcb import hcb_basis_general
  File "/home/aad/anaconda3/lib/python3.6/site-packages/quspin/basis/basis_general/base_hcb.py", line 1, in <module>
    from ._basis_general_core import hcb_basis_core_wrap_32,hcb_basis_core_wrap_64
  File "/home/aad/anaconda3/lib/python3.6/site-packages/quspin/basis/basis_general/_basis_general_core/__init__.py", line 1, in <module>
    from .hcb_core import hcb_basis_core_wrap_32,hcb_basis_core_wrap_64
ImportError: /home/aad/anaconda3/lib/python3.6/site-packages/quspin/basis/basis_general/_basis_general_core/../../../../../../libgomp.so.1: version `GOMP_4.0' not found (required by /home/aad/anaconda3/lib/python3.6/site-packages/quspin/basis/basis_general/_basis_general_core/hcb_core.cpython-36m-x86_64-linux-gnu.so)

**Comment by weinbe58** [comment]
Which version of gcc do you have installed? to check you can type `gcc -v` in the command line. I'm running Ubuntu and mine says:

```
phillip@phillip-HP-EliteBook-8460p:~$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.5' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
```

**Comment by aadonkov** [comment]
I get the following:
conda list gcc
# packages in environment at /home/aad/anaconda3:
#
gcc_impl_linux-64         7.2.0                hc5ce805_2  
gcc_linux-64              7.2.0               hd763dfe_12  
libgcc                    4.8.5                         2 

and for gcc -v:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.2.0-8ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)

**Comment by aadonkov** [comment]
I get the following:
conda list gcc
packages in environment at /home/aad/anaconda3:
gcc_impl_linux-64 7.2.0 hc5ce805_2
gcc_linux-64 7.2.0 hd763dfe_12
libgcc 4.8.5 2

and for gcc -v:
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.2.0-8ubuntu3' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu3)

**Comment by weinbe58** [comment]
Perfect! I was able to reproduce the issue on my computer.

the issue is your libgcc is at 4.8.5 which doesn't support openmp 4.0, run `conda update libgcc`

conda

**Comment by aadonkov** [comment]
thank you!
the update of the libgcc did allow the example to run!

**Comment by weinbe58** [comment]
Great!
