### ISSUE TITLE
Problem occurring in basis module 

### ISSUE THREAD

**Issue by srujans** [weinbe58/QuSpin#81]
Dear Developers,
The issue I am facing while running any code (e.g. Many-Body Localization in the Fermi-Hubbard Model) on Anaconda "Spyder" interactive environment with python-3.6(Windows 10), is the message saying that "ImportError: cannot import name 'hcp_basis'". I am putting the screenshot of the same below and I really appreciate your help on this problem.

Thanking you.
Srujans.
![import error](https://user-images.githubusercontent.com/12464481/33515802-c59ddd20-d78d-11e7-85ca-0563b5c42279.PNG)

**Comment by weinbe58** [comment]
Which version of QuSpin are you using?

**Comment by srujans** [comment]
0.2.7

**Comment by mgbukov** [comment]
Hi srujans,

a few questions: 

1) what is your operating system, e.g. Mac OS X, Windows, Linux?
2) which version of anaconda are you using? To figure this out, can u post the output of this command

 `conda info --json`

when you type it in the terminal? This will give us information about your local conda version.

@ Phil: I've seen similar error messages when trying to run the code w/o compiling it cuz the code was missing the c++ libraries. Might be that something went wrong with conda build.

**Comment by srujans** [comment]
Hello Phillip, 
here is the partial screenshot of the output of the above commend. My OS is Windows 10 (64-bit) and for anaconda: 3.6.3 | Anaconda Custom (64-bit).

![json](https://user-images.githubusercontent.com/12464481/33519954-56d2ed82-d7d7-11e7-94fa-7d68f2b612f0.PNG)

**Comment by srujans** [comment]
Hello MgBukov, 
here is the complete screenshot of the output of the above command in two parts. My OS is Windows 10 (64-bit) and for anaconda, it is showing  "conda_env_version": "4.3.30".

![json1](https://user-images.githubusercontent.com/12464481/33520059-882bd4a0-d7d9-11e7-83cb-6ff4a22649c7.PNG)
![json2](https://user-images.githubusercontent.com/12464481/33520060-886bab3e-d7d9-11e7-830a-19ef0772a7eb.PNG)

Thanks.

**Comment by weinbe58** [comment]
Hi srujans ,

So I tried setting up QuSpin on my windows laptop and running spyder for python 3.6 I didn't have any trouble running the script. 

Could you double check that running the example with standard python works? aka run `python example6.py` in the command line or anaconda prompt. I would recommend you use the anaconda prompt.

**Comment by srujans** [comment]
Thanks a lot, Phillip.
           After running it on anaconda prompt I was finally able to understand that it was a path problem.
Now it is working fine.
