### ISSUE TITLE
Issue on correlators

### ISSUE THREAD

**Issue by srujans** [weinbe58/QuSpin#89]
Hello Developers,
This is not more than a query.
In MBL papers, many times they are based on the numerical study of correlation functions, like in above paper. Is there a possibility in the future about an update on correlation functions in Quspin?

**Comment by weinbe58** [comment]
Hi srujans,

I have some ideas about how to implement correlation functions in a very general way (e.g. making use of symmetries to do the time evolution in parallel) but right now both myself and MGBukov are pretty busy with adding in fermionic degrees of freedom to QuSpin.

One thing that might be helpful would be to look at the example we have which calculates the non-equal time correlation function http://weinbe58.github.io/QuSpin/examples/example5.html#example5-label

Notice that in this example we have to evolve two states, one the initial state and another state which has been acted on by the operators in the correlation function, then using the generator feature of the evolve function we can get the time dependent correlation function by taking the matrix element of the operator between the two evolved states.

**Comment by srujans** [comment]
Hello Phillip,
Thanks a lot, I will look at the example.
