### ISSUE TITLE
partial trace

### ISSUE THREAD

**Issue by qi-zakaria** [weinbe58/QuSpin#95]
Hello
i would like to use the partial trace command in QuSpin, but i don't know how to call it from the quspin libraries
thank you

**Comment by mgbukov** [comment]
Hi qi-zakaria,

did u check out the QuSpin documentation:

http://weinbe58.github.io/QuSpin/generated/quspin.basis.spin_basis_1d.html#quspin.basis.spin_basis_1d.partial_trace

Below every function, we show how to call it.

Don't hesitate to shout out if u find this confusing, but we'd appreciate if u specify which part is the source of confusion, so we can fix it in the future :)

**Comment by qi-zakaria** [comment]
Hi
in my code i already imported the quspin basis, operators and tools but
when i try to call the partial trace function, this error appears :

name 'partial_trace' is not defined


Thank you for your reply



‌
<https://mailtrack.io/> Sent with Mailtrack
<https://chrome.google.com/webstore/detail/mailtrack-for-gmail-inbox/ndnaehgpjlnokgebbaldlmgkapkpjkkb?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality>

**Comment by mgbukov** [comment]
Let's try the following. Suppose u created a basis object

```
basis=spin_basis_1d(L=4)
state=np.zeros((basis.Ns,),np.complex128)
state[basis.index('1001')]=1.0
```

Then, `partial_trace()` is a function method of this `basis` object. This means that it should be called as follows

```
new_state = basis.partial_trace(state, sub_sys_A=[1,4])
new_state2 = basis.partial_trace(state, sub_sys_A=[1])
print(new_state)
print(new_state2)
```
where you can read about what the various arguments mean in the online doc. 

Does this help?

**Comment by qi-zakaria** [comment]
Thank you sooo much, i solved my problem, your tutorial was very helpful
‌
